### ISSUE TITLE
Cloned ip repo does not show up in SourceTree

### ISSUE THREAD

**Issue by cyiting** [nus-cs2103-AY2223S2/forum#10]
Hello, I have cloned the ip repository (using CLI) according to the steps on the course website. I can open/view the project on IntelliJ, but on SourceTree, it shows up under "Remote" instead of "Local". Is there a way to fix this? Or should I delete the repo and try again?

**Comment by onepersonhere** [comment]
Hi, I think you haven't link the cloned local repo to source tree; to link it on source tree, you need to open the local repo on source tree itself. Hope that helps!

**Comment by cyiting** [comment]
Okay, thank you!
