### ISSUE TITLE
Cannot access Controller methods from SceneBuilder 

### ISSUE THREAD

**Issue by anunayajoshi** [nus-cs2103-AY2223S2/forum#101]
Remember to give sufficient details e.g.,
* Your development environment (IntelliJ version, Java version, OS, ...)
* Relevant code, error message, stack trace
* Relevant code snippet (an example given below), or link to the relevant code on your GitHub repo

Hello, I have a JavaFXML file in a "resources" folder, which I believe is under gradle. 
I also have a Controller class that is under my main/java/duke package. 
I would like to link these two together, and was unable to do so under SceneBuilder, so I changed my fxml file as follows to include `fx:controller="duke.Controller"`

This allowed me to see the controller under the "Controller tab" within SceneBuilder but I was not able to assign the methods given, as there is no drop down. 

If it matters, here's my start method to know that my filepath is correct. My GUI functions normally, but it is just that the controller methods do not show up. 

```java
@Override
    public void start(Stage stage) throws Exception {
        Parent root = FXMLLoader.load(getClass().getResource("/sample.fxml"));
        Scene scene = new Scene(root);
        stage.setScene(scene);
        stage.show();
    }
```

Hope someone could advise!

**Comment by hingen** [comment]
> I was not able to assign the methods given, as there is no drop down

Hi @anunayajoshi, not too sure what you mean by this. Forgive me if I interpret your question incorrectly.

If the goal is to assign a method to be called when some event occurs (e.g. when the send button is pressed), you can do the following:
1. Specify the name of the method to call under the appropriate event in Scene Builder
![image](https://user-images.githubusercontent.com/31367001/215661645-b51a844f-71da-4c56-a599-8e7308fb4509.png)

2. Create a method within your controller with the same name
```java
public class MainWindow extends AnchorPane {
    // some code

    @FXML
    private void handleUserInput() {
        // code to run when the event occurs
    }

    // some code
}
```

Scene Builder is oblivious of your code and is only aware of what is in the fxml file thus it cannot produce a dropdown menu for your methods if that is what you're trying to do.
