### ISSUE TITLE
Issue of Duke GUI truncating the input

### ISSUE THREAD

**Issue by heeeyi** [nus-cs2103-AY2223S2/forum#103]
Hi I am adding a GUI for my Duke, strictly following the JavaFX tutorial provided in the class.

However, I found that for both my input and Duke response, if they are too long, the GUI will not be able to completely show them, but instead show them in a truncated fashion, i.e. "something something..." towards the end. The long message will only be completely shown if there are no other dialog box behind it.

Here are the screenshots:

(No dialog box behind, show complete message)
![013120231526](https://user-images.githubusercontent.com/97591125/215694640-0751ff15-ab68-4823-90d8-3e9562396159.JPG)

(Has other dialog box, or reaching the end, truncated)
![013120231525](https://user-images.githubusercontent.com/97591125/215694803-71f2ce8b-1f08-4419-bd7b-d707781a14a6.JPG)

Does anyone know how to resolve this?

**Comment by hingen** [comment]
might be related to #102
