### ISSUE TITLE
CheckStyle for import statements

### ISSUE THREAD

**Issue by anchengyang** [nus-cs2103-AY2223S2/forum#106]
Attached is the checkstyle error that I am getting. Does anyone know why?
![image](https://user-images.githubusercontent.com/65301406/215716109-3b941962-8b0b-45ed-875a-ccc62c63a5e6.png)

This is my code for TaskList.java
![image](https://user-images.githubusercontent.com/65301406/215716289-03bebd4b-537a-42f8-b79e-0635ffda706a.png)

**Comment by wz2k** [comment]
The java imports should be above the duke imports.

**Comment by wz2k** [comment]
You can refer to [https://se-education.org/guides/tutorials/intellijCodeStyle.html](https://se-education.org/guides/tutorials/intellijCodeStyle.html) to set import ordering in your settings

**Comment by hingen** [comment]
Your import order isn't in violation of the module's java coding standard, it's just that it doesn't match the order specified in the `checkstyle.xml` file you are using.

To change the import order of checkstyle, change the code in the following section of  `checkstyle.xml`:
```xml
<module name="CustomImportOrder">
    <!-- some stuff -->
</module>
```

Looking at your current import style, it seems you group `duke` and `java` packages together so this import order might work for you:
```xml
<module name="CustomImportOrder">
    <property name="customImportOrderRules"
        value="STATIC###SPECIAL_IMPORTS###THIRD_PARTY_PACKAGE###STANDARD_JAVA_PACKAGE"/>
    <property name="specialImportsRegExp" value="^org\."/>
    <property name="thirdPartyPackageRegExp" value="^com\."/>
    <property name="standardPackageRegExp" value="^(duke|java)\."/>
    <property name="sortImportsInGroupAlphabetically" value="true"/>
</module>
```

You're likely going to have to modify it when you start bringing in `javafx` packages. You can find more info about checkstyle import order checks [here](https://checkstyle.sourceforge.io/apidocs/com/puppycrawl/tools/checkstyle/checks/imports/CustomImportOrderCheck.html).

**Comment by anchengyang** [comment]
Thanks @wz2k and @hingen
