### ISSUE TITLE
[Technical issue] Unable to start daemon after installing javaFx to build.gradle

### ISSUE THREAD

**Issue by SHni99** [nus-cs2103-AY2223S2/forum#107]
The following error does not allow me to continue and I had tried for the past few hours.

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/96757889/215720012-0b64c54a-8573-4ad0-8790-f48ad848efb0.png">

**Comment by SHni99** [comment]
I have gotten this issue "*Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found*" also

**Comment by hingen** [comment]
could you provide your `build.gradle` file?

**Comment by SHni99** [comment]
> could you provide your `build.gradle` file?

build.gradle

**Comment by Junyi00** [comment]
> could you provide your `build.gradle` file?

Just to add on, I believe in this situation, pushing your current codebase as a separate branch for us to see or try locally would give you a better response. (you can then delete it later once u resolve it or just merge into master after)

**Comment by SHni99** [comment]
> could you provide your `build.gradle` file?

I have pushed 'branch-Level-10' onto [branch-Level-10](https://github.com/SHni99/ip/tree/branch-Level-10)

**Comment by SHni99** [comment]
Had followed the instructions on [JavaFx](https://se-education.org/guides/tutorials/javaFxPart1.html).
Faced with the same error:
<img width="810" alt="image" src="https://user-images.githubusercontent.com/96757889/215740452-dbcc0c4c-ccdb-44cd-a927-e2d27cc76800.png">

**Comment by hingen** [comment]
Not sure if this will fix it but in your `build.gradle`, change `duke.Duke` to `duke.Launcher`

```
application {
    mainClassName = "duke.Launcher"
}
```

**Comment by hingen** [comment]
if it doesn't could you provide your Java version? That is what is your output if you run `java --version`?

**Comment by SHni99** [comment]
ah its jdk 18, but i remember i changed to jdk 11 😢

**Comment by hingen** [comment]
welp that's probably the issue haha

**Comment by SHni99** [comment]
I'm have switched and am running on openjdk version 11, but the problem persists
<img width="639" alt="image" src="https://user-images.githubusercontent.com/96757889/215749673-2a055a5f-539a-4d69-b631-73cc1bfca4c6.png">

**Comment by hingen** [comment]
Honestly not too sure how to fix this issue, maybe someone else can chime in.

In the meantime, maybe can try the following one at a time and see if they work:
1. If you haven't done so, restart your computer after installing jdk11
2. Push all your changes to your remote and clone to a separate directory (to clean out any files that are generated by gradle and intellij idea)

**Comment by SPWwj** [comment]
> I'm have switched and am running on openjdk version 11, but the problem persists <img alt="image" width="639" src="https://user-images.githubusercontent.com/96757889/215749673-2a055a5f-539a-4d69-b631-73cc1bfca4c6.png">

Hi I have run your code on my IDE and it work fine.
Just to give some suggest on the setup of IDE environemnt:
1. Make sure you have choose the correct SDK in the project structure
<img width="770" alt="image" src="https://user-images.githubusercontent.com/30100720/215764461-2f50394d-256f-4147-9723-d2e973d42c91.png">
2. After you edit on your gradle file you may try to do a reload on your project by click this button
<img width="772" alt="image" src="https://user-images.githubusercontent.com/30100720/215764999-efedcf71-40bc-40bb-8aee-c983cb78adc2.png">

**Comment by Junyi00** [comment]
Same here, I can compile and run your application successfully. This could suggest that your JavaFX dependencies have been installed wrongly.

**Comment by SHni99** [comment]
Thanks for the help everyone, it has been resolved 👍 
Problem was caused due to wrong installation of javaFx using Gradle, therefore I have tried to install javaFx lib without using Gradle and it worked

**Comment by domlimm** [comment]
Hello @SHni99, I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once your problem has been resolved. Have a great day! 😄
