### ISSUE TITLE
Renaming Duke Class?

### ISSUE THREAD

**Issue by ezeAng** [nus-cs2103-AY2223S2/forum#109]
Can I rename Duke class to my own bot name? Must the main bot class be named Duke specifically or can we name it anything we like?

**Comment by jundatan** [comment]
Don't think there is a restriction on what class names you must use. Just need to follow the coding standard guidelines and make sure the class name makes sense.

**Comment by RubyNguyen07** [comment]
@ezeAng yes, from what I read then you are even encouraged to create a new name and personality for your bot!

**Comment by francisyzy** [comment]
Just remember to update your gradle.build files and text-ui-test!

**Comment by damithc** [comment]
@ezeAng 
1. Yes, you may name the classes any way you wish, but keep the repo name as `ip`.
2. Can you also edit the issue subject and body to make it more presentable? Looks like you put the body into the subject by mistake.

**Comment by ezeAng** [comment]
Thanks!

**Comment by lhy-hoyin** [comment]
Hello! It appears that your issue have been resolved 😄

Perhaps @ezeAng  can mark this issue as Close as completed. Thank you!

(But it you think your question is still not answered, perhaps you can reiterate what you would like to clarify.)
