### ISSUE TITLE
Clarification on Error Handling Requirements

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#11]
Hi all,

I'm on Level-5 of Duke and I have implemented the error handling such that if an error is detected, Duke throws a DukeException and the whole program is terminated. 

I would like to clarify if we need to terminate the program if an error is detected.

If not, and an error message should simply be printed instead, does this mean that we don't need to throw a DukeException if an error is detected? 

Thank you.

**Comment by damithc** [comment]
Good question @Tempura-Person 
From a project requirements point of view, the answer for this case is "do what makes sense from the user point of view".
What behavior makes sense from the user's POV, in this case? That's a good question for a discussion here. 

Separately, can an Exception be used even when the expected behavior is printing an error message? That's another good question for a discussion.

**Comment by BoAi01** [comment]
> Good question @Tempura-Person From a project requirements point of view, the answer for this case is "do what makes sense from the user point of view". What behavior makes sense from the user's POV, in this case? That's a good question for a discussion here.

For this question, I think the program should not stop when a user-side error occurs (e.g., wrong commands). Instead, the program can let the user try again. 

> Separately, can an Exception be used even when the expected behavior is printing an error message? That's another good question for a discussion.

I am less sure about this one. To achieve the function of printing out an error message, we certainly do not have to use an Exception. But it seems that using an exception better separates normal function code from error-handling code. So it would be a better abstraction design.

**Comment by hingen** [comment]
> From a project requirements point of view, the answer for this case is "do what makes sense from the user point of view". What behavior makes sense from the user's POV, in this case?

I'm also of the opinion that the program should not stop. Since the current task list does not save to secondary storage, it seems unforgiving if the user loses his entire task list if he just types one command incorrectly.

> Separately, can an Exception be used even when the expected behavior is printing an error message?

For me, I want my error messages printed in a different way from normal output messages and using a custom exception is one way I achieve it. Although it could definitely be achieved via other means. Perhaps throwing an exception could be a way of stating explicitly that an error has occurred for whoever reads the code base in the future?

**Comment by Tempura-Person** [comment]
I can't think of how i can throw a DukeException yet also not terminate the program at the same time.
I have reverted all my exception throws to just print statements.

**Comment by hingen** [comment]
Have you tried using a try-catch block?

**Comment by SPWwj** [comment]
@Tempura-Person You may place your code in while loop and catch the exception using try-catch
` try {doSomeThing();} catch (DukException e) {}`
The exceptions which are handle by the try-catch will not terminate the program. Thus, the loop will continue.

**Comment by Tempura-Person** [comment]
I considered that, but i have different error messages depending on what type of exception it is.
I can't make DukeException extend one of these types of exceptions otherwise i feel it would defeat the purpose of creating DukeException to begin with.

**Comment by hingen** [comment]
@Tempura-Person  How about having `DukeException` extend `Exception` and give `DukeException` an `errorMessage` property that you set in the constructor. So whenever an error occurs, you throw a `DukeException` with an error message specific to the error. You can then handle the error by just printing out `errorMessage`.

If you feel that using `DukeException` is not specific, you can always extend `DukeException` (e.g. `DukeEmptyDescriptionException`) with each derived class having a preset `errorMessage`. You can then have different errors throw different exceptions all derived from `DukeException`. That way your catch block will only have to catch `DukeException` and print out whatever is stored in `errorMessage`.

**Comment by Tempura-Person** [comment]
It was throwing the exception that terminated the program, in my case (though I have doubts, myself)

```
case ("mark"):
                    try {
                        String MarkString = UserScan.nextLine().strip();
                        // ERROR: mark format is anything other than [ mark <insert integer> ]
                        if (MarkString.length()==0) {
                            throw new DukeException("\n" + border + "[ERROR]\nUh, mark command format is used wrongly.\nCorrect format is as follows:\n" +
                                    "[ mark <insert INTEGER> ]\n" + border);
                        }
                        int MarkInput = Integer.parseInt(MarkString) - 1;
                        TaskList.get(MarkInput).MarkDone();
                        System.out.println(border + "Okay, the following task is marked as done!\n");
                        System.out.println((MarkInput+1 + ". ") + TaskList.get(MarkInput).toString() + "\n" + border);
                        break;
                    }
                    // ERROR: mark is NOT paired with an integer (e.g. unmark two, unmark 2.3)
                    catch (NumberFormatException | InputMismatchException err) {
                        throw new DukeException("\n" + border + "[ERROR]\nUh, mark can only be used with an INTEGER. (e.g. 1, 2...)\n" + border);
                    }
                    // ERROR: mark target does not exist (e.g. task number is out of bounds)
                    catch (IndexOutOfBoundsException err) {
                        throw new DukeException("\n" + border + "[ERROR]\nUh, you can only mark task numbers that exist.\nYou have "
                                + TaskList.size() + " task(s) in your list.\n" + border);
                    }
```

**Comment by SPWwj** [comment]
This is what my understanding for DukeException: 
DukeException handle the scenario what we can expect.
The confusion here is "if we can expect the situation, we can just handle it without throwing the exception e.g if statement.
But let think about the following scenario.
./input/getUserInput.java // expect DukeException, but without the method that you want to handle this exception. 
./Duke.java // your main program, contain the method that you want to handle the duke exception.
you may use propagation feature of the Exception to help you handle the exception.

> 
To prevent terminating your program you need to catch the "throw new DukeException" somewhere in your code (e.g. `public void main()`).

You may catch all exception by just `catch(Exception e)  `

**Comment by hingen** [comment]
@Tempura-Person Looks about right. If you nest your switch block inside another try-catch block which catches `DukeException`, it shouldn't terminate the program

Something like this:
```java
while (true) {
        // some other code
        try {
            // your switch code block
        } catch (DukeException e) {
            System.out.println(e.errorMessage);
            continue;
        }
        // some other code
}
```

Also, probably would be good if you move the code for each command into it's own method or class. Else, you're going to have one massive method that is hard to read and debug with a lot of nesting (lots of tabs).

**Comment by Tempura-Person** [comment]
> @Tempura-Person Looks about right. If you nest your switch block inside another try-catch block which catches `DukeException`, it shouldn't terminate the program
> 
> Something like this:
> 
> ```java
> while (true) {
>         // some other code
>         try {
>             // your switch code block
>         } catch (DukeException e) {
>             System.out.println(e.errorMessage);
>             continue;
>         }
>         // some other code
> }
> ```
> 
> Also, probably would be good if you move the code for each command into it's own method or class. Else, you're going to have one massive method that is hard to read and debug with a lot of nesting (lots of tabs).

Thank you for that suggestion, I tried it and it worked properly.
Though the error message displays in the normal way and not the red font error messages normally print in, at least i feel like DukeException is useful now.

![image](https://user-images.githubusercontent.com/92144641/212867398-9bf3efd5-565d-4e0a-912a-6533f1dbaac8.png)
