### ISSUE TITLE
Unable to use checkstyle with Gradle

### ISSUE THREAD

**Issue by RubyNguyen07** [nus-cs2103-AY2223S2/forum#110]
Hello, I have created two files checkstyle.xml and suppressions.xml in the ./config/checkstyle folder. I also have included the checkstyle plugin in the build.gradle file and set the tool version to '10.2'. However, when I try to run "./gradlew checkstyleMain", there will be the following error: 

> Unable to create Root Module: config {{rootDir}/ip/config/checkstyle/checkstyle.xml}, classpath {/ip/build/classes/java/main:/{rootDir}/ip/build/resources/main}.

Did any of you run into the same issue?

**Comment by Junyi00** [comment]
Any chance your file name for `suppressions.xml` has a typo?

**Comment by RubyNguyen07** [comment]
@Junyi00 nopee i double checked both filenames

**Comment by damithc** [comment]
@RubyNguyen07 perhaps push your code to a branch and give the link here so that others can try to reproduce the error?

**Comment by RubyNguyen07** [comment]
I just checked again, it turned out it is because this URI "https://checkstyle.org/dtds/configuration_1_3.dtd" is not resolved. It works now, thanks!
