### ISSUE TITLE
Error when running gradlew for checkstyle

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#112]
![image](https://user-images.githubusercontent.com/108938188/215792007-793e5630-e3f7-4641-a789-7ad86aaca623.png)

I received this error when trying to run gradlew. This seems like I haven't installed gradlew correclty (?)

I have already updated my build.gradle files to include the relevant plugins and also included the checkstyle and suppression files

**Comment by wxxedu** [comment]
Hi! Have you tried running 
```sh
gradle wrapper
```
Because it appears to me that your gradlew file has not been generated. :-)

**Comment by Guo-KeCheng** [comment]
I think the issue is that you are inside your duke directory. 

Try navigating to the IP directory. The gradlew file is probably located there. 

From there you can try running 

```
// Linux or Mac
./gradlew checkstyleMain checkstyleTest


// Windows
gradlew.bat checkstyleMain checkstyleTest
```

Let me know if you manage to solve the issue.

p.s. Thank you @hingen for pointing out the command

**Comment by bojie3** [comment]
Maybe you can try to run the command using Gradle execute task.

![image](https://user-images.githubusercontent.com/95684564/215920301-1261dd0e-3a31-4961-9b85-5934f6a29545.png)

Click the gradle icon and the Execute Gradle Task icon.

![image](https://user-images.githubusercontent.com/95684564/215920417-bbd8008c-4c1d-4fc2-b618-e763669baaff.png)

Then you can try to run the command there, worked for me.

**Comment by francisyzy** [comment]
Have you tried restarting the IDE? Because my friend had a problem with dependencies not installing until he restarted that.

**Comment by hingen** [comment]
> I think the issue is that you are inside your duke directory.
> 
> Try navigating to the IP directory. The gradlew file is probably located there.

I think @Guo-KeCheng is probably right but the command provided is for Linux and Mac. If I'm not wrong, the command on Windows should be:
```
gradlew.bat checkstyleMain checkstyleTest
```

**Comment by kayyenl** [comment]
Just wanted to add to this, was having the same problem as the poster. 

for the Windows cmd terminal (or the integrated terminal within IntelliJ), using 

```
./gradlew.bat checkstyleMain checkstyleTest 
```

was the command that worked for me. 👍

**Comment by FredericChow00** [comment]
@kayyenl this worked thank you so much!
