### ISSUE TITLE
Scene Builder not showing that DialogBox.java is the controller class for DialogBox.fxml

### ISSUE THREAD

**Issue by linustws** [nus-cs2103-AY2223S2/forum#113]
Hi, I have finished the JavaFxPart4 tutorial about controller classes, and have updated the controller class for DialogBox.fxml to be DialogBox.java as specified. However, this change is not reflected in Scene Builder under the controller class. It still shows that it does not define a controller class as shown below.
<img width="306" alt="image" src="https://user-images.githubusercontent.com/97421565/215816684-da623840-9590-471d-8aae-361f563c0eeb.png">
I then added the `fx:controller="duke.DialogBox"` in the DialogBox.fxml, and this managed to reflect the change in Scene Builder. However, when running the launcher, after typing an input, there was this error: javafx.fxml.LoadException: Controller value already specified. I removed the `fxmlLoader.setController(this);` and `fxmlLoader.setRoot(this);` statements in DialogBox.java as I thought that the 2 ways to set a controller: 1. using the fx:controller attribute, and 2. using fxmlLoader.setController(this) were causing a conflict and hence the exception. I removed both statements and I received another error: javafx.fxml.LoadException: in my DialogBox.fxml and showed something about URI not registered.
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/97421565/215820130-e1bc3766-ca90-4e50-9c81-bff7605ab216.png">
Is there a way to fix this error and yet display that DialogBox.fxml has its own controller class in Scene Builder?

**Comment by immanuelhume** [comment]
The guide says

> Let’s repeat the process for DialogBox. The main difference here is that DialogBox checks Use fx:root construct and does not define a controller class.

Which means there shouldn't be any controller class set for DialogBox. Instead, the fx:root checkbox should be checked. So your initial fxml file was correct.

**Comment by linustws** [comment]
I see. It's the later part that says 

> For our custom DialogBox, we did not define a controller so let's create a controller for it.

and

> When we create a new instance of DialogBox, we set both the controller and root Node to DialogBox. From this point onwards we can interact with DialogBox as we have in the previous tutorials.

so I assumed setting the controller to DialogBox meant it now has a controller class. Is this not equivalent?

**Comment by hingen** [comment]
> so I assumed setting the controller to DialogBox meant it now has a controller class. Is this not equivalent?

Not super familiar with JavaFX but perhaps you can think of it this way.

You are able to set the controller object dynamically at runtime using code. That is what the `fxmlLoader.setRoot(this);` line in the `DialogBox` class constructor is for. This means that you are not constraint to having to use a class named `DialogBox` every time, all you need is a class that inherits from the same Node type as the root in the `DialogBox.fxml` file (in this case it is `HBox`).

Why is this useful? The first thing that comes to mind is reusability. If I have a generic `fxml` that I want to reuse for many different scenarios, I now can.

**Comment by ruiyigan** [comment]
I think @hingen provided a great answer. I believe these are just the two ways to set a controller for an FXML file. More can be found here: https://jenkov.com/tutorials/javafx/fxml.html#:~:text=There%20are%20two%20ways%20to,to%20load%20the%20FXML%20document.

**Comment by linustws** [comment]
> > so I assumed setting the controller to DialogBox meant it now has a controller class. Is this not equivalent?
> 
> Not super familiar with JavaFX but perhaps you can think of it this way.
> 
> You are able to set the controller object dynamically at runtime using code. That is what the `fxmlLoader.setRoot(this);` line in the `DialogBox` class constructor is for. This means that you are not constraint to having to use a class named `DialogBox` every time, all you need is a class that inherits from the same Node type as the root in the `DialogBox.fxml` file (in this case it is `HBox`).
> 
> Why is this useful? The first thing that comes to mind is reusability. If I have a generic `fxml` that I want to reuse for many different scenarios, I now can.

Thanks! I didn't think that controllers can be changed dynamically. I guess the setController method allows that whereas the fx:controller method only sets the controller at the start of runtime.
