### ISSUE TITLE
Exit GUI gracefully

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#115]
My current way of exiting from the GUI is to add the following lines at the start of the `handleUserInput` method 
```
private void handleUserInput() {
    if (duke.isExited()) {
        Platform.exit();
    }
    // ... things to do if the program has not exited
}
```
The effect is, after entering "bye", Duke will print out the final message, but the GUI only closes when the user enters the **next** command. However, ideally, we would like the GUI window to close **some time after** it reponds to our "bye" input. 

I tried using`TimeUnit.MINUTES.sleep(1);` and `Platform.exit();` at the end of `handleUserInput`, but it turns out that, the GUI will exit directly without printing out the last message, possibly because we cannot end the program inside `handleUserInput` method. Then what is the solution?

**Comment by hingen** [comment]
If I'm interpreting your question correctly, I think this question was sort of (but not fully) discussed in #99, maybe looking through the comments there would help a bit. The last [comment](https://github.com/nus-cs2103-AY2223S2/forum/issues/99#issuecomment-1410420911) in the post seems similar to what you're trying to accomplish

**Comment by BoAi01** [comment]
@hingen Great, thanks for pointing out!
