### ISSUE TITLE
[tP] Software Complexity Expectations for Evolve vs Morph

### ISSUE THREAD

**Issue by fahim-tazz** [nus-cs2103-AY2223S2/forum#116]
Prof @damithc, before my team decides on whether to Morph or Evolve AB3 for our tP, I would like to know, is there any difference in expected complexity of features? 
I.e. for Morph, since we are starting from scratch, will you be expecting less complex features, compared to Evolve where we are building on existing software, so we can build more complex functionality?

P.S. I understand we should not be worried about features yet, but we just wanted to gauge the workload for each direction.

**Comment by damithc** [comment]
@fahim-tazz When grading, we measure the effort, which will depend on many things e.g., evolve or morph (but also what you evolve/morph into), features (how many, how big, how complex), etc.
So, there is no fixed rule such as 'morph means less complex features'

**Comment by Hikoya** [comment]
Hello @fahim-tazz  , I'm a senior from a previous batch, gentle reminder to close the issue if your question has been answered by prof!
