### ISSUE TITLE
Query about resolving the link in xml check style file

### ISSUE THREAD

**Issue by heeeyi** [nus-cs2103-AY2223S2/forum#117]
Hi I encountered the same issue to #110, and in the end, the root cause of the issue turned out to be “the URL https://checkstyle.org/dtds/configuration_1_3.dtd is not resolved”. May I ask how can this URL be resolved? Will be so appreciated if anyone could help in pointing out what exactly I need to do, thanks so much!

![05809396-13C8-470C-A55D-EFD55D0D6C46](https://user-images.githubusercontent.com/97591125/215967714-ef96ad83-aee7-4e92-8cd1-158c0850fe68.jpeg)

**Comment by heeeyi** [comment]
Self-response:

I found that the issue are actually two-fold:
(1) To resolve the URL, hover the mouse over the red unresolved link until it shows "fetch external resources". After successful fetch, the link will turn green
(2) Property "scope" does not exist, please check the documentation
The problematic line is at the line 387 of checkstyle.xml, `<property name="scope" value="public"/>`. When I follows the method of this tutorial, https://github.com/jshiell/checkstyle-idea/issues/525 and change the line to `<property name="accessModifiers" value="public, protected"/>`, the issue is resolved.

Not sure if this is the best way though, or even the expected way.

**Comment by alson001** [comment]
Please close this issue for the bot to stop pinging random people.

**Comment by damithc** [comment]
@heeeyi Thanks for sharing your own solution here.
