### ISSUE TITLE
How to fix javafx.fxml.LoadException

### ISSUE THREAD

**Issue by anchengyang** [nus-cs2103-AY2223S2/forum#118]
![image](https://user-images.githubusercontent.com/65301406/215972745-043feb9a-33e4-4276-8d48-63332db95bc1.png)
How can I fix this error?
My MainWindow.java file is the same as the one in the tutorial part 4 [here](https://se-education.org/guides/tutorials/javaFxPart4.html#using-controllers)

My code currently looks like [this](https://github.com/anchengyang/ip/tree/branch-Level-10) with the error

**Comment by damithc** [comment]
@anchengyang While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

**Comment by Junyi00** [comment]
Your JavaFX installation seems to be slightly different from the [given guide](https://se-education.org/guides/tutorials/javaFxPart1.html#setting-up-java-fx) and so is your targeted JavaFX version. Following the official installation fixed this issue.

Also, an additional bug in `MainWindow.java`, your images are not in the `images` folder.

**Comment by daitenshionyan** [comment]
Other than the images not being in `images` folder that @Junyi00 mentioned, the `duke` class field was not yet initialised when the `initialize()` method is called somewhere in the loader.

By only tweeking your code a bit to something like this in `MainWindow` I was able to get the window to show!!

```java
// changed path to remove images
private Image userImage = new Image(this.getClass().getResourceAsStream("/DaUser.png"));
private Image dukeImage = new Image(this.getClass().getResourceAsStream("/DaDuke.png"));

@FXML
public void initialize() {
    /* new addition here >>>>> */ this.duke = new Duke();
    scrollPane.vvalueProperty().bind(dialogContainer.heightProperty());
    dialogContainer.getChildren().addAll(
            DialogBox.getDukeDialog(this.duke.showWelcomeMessage(), dukeImage)
    );
}
```

**Comment by anchengyang** [comment]
thanks so much @daitenshionyan @Junyi00
