### ISSUE TITLE
Issue with committing after finishing everything

### ISSUE THREAD

**Issue by yitong241** [nus-cs2103-AY2223S2/forum#12]
Hello prof, I only committed after I finished till level 6, is there anything I can do to fix this?

**Comment by damithc** [comment]
@yitong241 To satisfy the progress tracking script, an easy solution is to tag that commit with all the tags you should have added until now. 
More info in this FAQ https://nus-cs2103-ay2223s2.github.io/website/schedule/week2/project.html#faq-about-ip-increments

**Comment by yitong241** [comment]
Hello prof thank you for the response, but what if the commit does not satidfy the earlier requirements? For example, "blah" would be considered as a valid input as we should echo it according to Level 1; but in Level 5, it is considered as an error.

**Comment by damithc** [comment]
> Hello prof thank you for the response, but what if the commit does not satidfy the earlier requirements? For example, "blah" would be considered as a valid input as we should echo it according to Level 1; but in Level 5, it is considered as an error.

@yitong241 That's fine. When a later requirement overrides an earlier requirement, only the later requirement needs to be satisfied.

**Comment by BoAi01** [comment]
> > Hello prof thank you for the response, but what if the commit does not satidfy the earlier requirements? For example, "blah" would be considered as a valid input as we should echo it according to Level 1; but in Level 5, it is considered as an error.
> 
> @yitong241 That's fine. When a later requirement overrides an earlier requirement, only the later requirement needs to be satisfied.

Great. I was wondering about this too.

**Comment by yitong241** [comment]
thanks a lot prof!
