### ISSUE TITLE
Issue with JavaFX Label Ellipsis

### ISSUE THREAD

**Issue by angjunkang** [nus-cs2103-AY2223S2/forum#123]
Hi! I faced a few issue with ellipsis and truncated string with labels. I also noticed there are several issues raised regarding this. I have followed the solution provided in #102 and it solved most of the problem. However, one issue I am still facing is how the last line of my output is not shown. 

As you can see from the picture, it appears that the height is already dynamic except for the fact that the last line is always hidden/truncated. Would appreciate any help and advise on this! Thanks!

![image](https://user-images.githubusercontent.com/33411270/216099216-d95971c6-4c5e-4c4a-92c6-9880c183562a.png)

**Comment by hansstanley** [comment]
@Irminrics I added `minHeight="-Infinity"` to my `Label`, like so:

```fxml
<Label fx:id="messageText" text="Label" wrapText="true" minHeight="-Infinity">
    ...
</Label>
```

Here's a comparison with and without `minHeight="-Infinity"`:

> Without `minHeight="-Infinity"`

<img width="512" alt="Screenshot 2023-02-02 at 07 55 40" src="https://user-images.githubusercontent.com/20805849/216195086-2a61c28b-584c-40f2-a4bc-2bd1cfb8b429.png">

> With `minHeight="-Infinity"`

<img width="512" alt="Screenshot 2023-02-02 at 07 56 30" src="https://user-images.githubusercontent.com/20805849/216195305-2b564bec-a8c9-4e63-8a4c-faf358101196.png">

Hope this helps!

**Comment by angjunkang** [comment]
Thanks! I implemented this too but apparently what caused my error was my usage of custom font and font size for the text in the label. Hope this thread would help someone out there!
