### ISSUE TITLE
JavaFX missing components

### ISSUE THREAD

**Issue by thennant** [nus-cs2103-AY2223S2/forum#125]
Error message from running Crystal:
![image](https://user-images.githubusercontent.com/97217532/216232089-c88e6ebd-c6bd-441c-93dd-a29e1442fe15.png)

Build.gradle:
![image](https://user-images.githubusercontent.com/97217532/216232328-b899f920-dd7e-48bf-b5ad-cb08ab56cb0f.png)

The gui from running launcher class:
![image](https://user-images.githubusercontent.com/97217532/216232800-59a8e10d-ffbc-4fbd-832f-91a9ade0627d.png)

Hi, i am having issues with the javafx installation. I have added the necessary plugins, javafx version and modules as well as dependencies to the build.gradle. Upon running my Crystal class (the Duke class), it says missing javafx components. However, i am able to run my launcher class with the gui window popping up. Is this a normal thing or do i need to install the missing components and if so how do I go about that? Thanks.

**Comment by hingen** [comment]
Yup, seems like this is normal. If you look at the `addressbook-level3` code base, there is an explanation for it in the `Main.java` [file](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/Main.java).

```java
/**
 * The main entry point to the application.
 *
 * This is a workaround for the following error when MainApp is made the
 * entry point of the application:
 *
 *     Error: JavaFX runtime components are missing, and are required to run this application
 *
 * The reason is that MainApp extends Application. In that case, the
 * LauncherHelper will check for the javafx.graphics module to be present
 * as a named module. We don't use JavaFX via the module system so it can't
 * find the javafx.graphics module, and so the launch is aborted.
 *
 * By having a separate main class (Main) that doesn't extend Application
 * to be the entry point of the application, we avoid this issue.
 */
```

**Comment by hingen** [comment]
Yup, seems like this is normal. If you look at the `addressbook-level3` code base, there is an explanation for it in the `Main.java` [file](https://github.com/se-edu/addressbook-level3/blob/master/src/main/java/seedu/address/Main.java).

**Comment by thennant** [comment]
ok thanks!
