### ISSUE TITLE
JavaFX: Classes Loaded from Unnamed Module

### ISSUE THREAD

**Issue by IsabelChong** [nus-cs2103-AY2223S2/forum#127]
I'm now at `Level-10` doing the part on "1. learning JavaFX basics" and have completed the [JavaFX tutorial @SE-EDU/guides](https://se-education.org/guides/tutorials/javaFx.html). 

After running `Launcher.java`, I always get this error below, but the basic GUI does start up.

 <img width="765" alt="image" src="https://user-images.githubusercontent.com/71481877/216247417-f3925c4b-a1bd-4671-bc27-5ef1e738b65d.png">

Searching online led me to [stackoverflow](https://stackoverflow.com/questions/67854139/javafx-warning-unsupported-javafx-configuration-classes-were-loaded-from-unna) but I'm not sure where I am supposed to make sense out of it in my code. Below is a snipshot of the solution given:
<img width="668" alt="image" src="https://user-images.githubusercontent.com/71481877/216248310-8159f0a7-7255-42e0-85ce-b3aacad03b0e.png">

Anyone knows why and what this error is coming up?

**Comment by damithc** [comment]
@IsabelChong You can ignore that warning.
