### ISSUE TITLE
Checkstyle import statement 

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S2/forum#129]
![image](https://user-images.githubusercontent.com/77482097/216384338-778f077b-6f90-4fcf-b1fe-cb932bf33e9c.png)

This checkstyle error baffles me. When i remove the import statement, no errors from checkstyle but the code wont work.

**Comment by Lava-Iris** [comment]
Oh I got the same errors. It went away when I put the java io (and any external import statements) before the duke import statements.

**Comment by Junyi00** [comment]
I believe @hingen has addressed this by suggesting a fix here #108
