### ISSUE TITLE
Can I move Duke.java into a package?

### ISSUE THREAD

**Issue by hingen** [nus-cs2103-AY2223S2/forum#13]
Currently, I've placed `Duke.java` in the `duke` package but I realize that `./text-ui-test/runtest.sh` assumes that `Duke.java` is not in a package.

I've modified `runtest.sh` to support having `Duke.java` in the `duke` package but am wondering if this will cause any issue with grading later on.

**Comment by damithc** [comment]
@hingen You can modify `runtest.sh` as you wish.

**Comment by hingen** [comment]
> @hingen You can modify `runtest.sh` as you wish.

Noted! Thank you prof
