### ISSUE TITLE
How to resolve iP Level-10 Error: java.lang.NoSuchMethodException: Duke.<init>()💡

### ISSUE THREAD

**Issue by rmj1405** [nus-cs2103-AY2223S2/forum#133]
I followed the JavaFX tutorial but was faced with `java.lang.NoSuchMethodException: Duke.<init>()` in `Launcher.java` after adding some modifications to my code structure. This issue can be solved by simply **adding a default constructor in your Duke class**. Hope this helps anyone facing this issue!

``` java
 public Duke() {}

**Comment by Tariq-droid** [comment]
Thank you man. I spent an hour trying to figure out the solution

**Comment by rmj1405** [comment]
> Thank you man. I spent an hour trying to figure out the solution

Happy to help! I was stuck for quite a while too 🥲

**Comment by bryansendeavour** [comment]
Life saver!
