### ISSUE TITLE
Did not do Level-10 on branch

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#137]
I did Level-10 on master, so it was not reflected in the IP progress dashboard. Is the best way to rectify this to create a Level-10 branch (with dummy changes) and merge it with master?

**Comment by damithc** [comment]
> Is the best way to rectify this to create a Level-10 branch (with dummy changes) and merge it with master?

Yes, that works @seadragon2000341 
Also remember to push a `Level-10` tag.
