### ISSUE TITLE
How do we read multiplicity?

### ISSUE THREAD

**Issue by venuslimm** [nus-cs2103-AY2223S2/forum#139]
During yesterday's lecture, I think the way multiplicity was read for Canvas questions 1 and 2 contradicted with what was indicated in the textbook. 

Textbook definition of Multiplicity:
![image](https://user-images.githubusercontent.com/50315976/216754834-2e8b54f2-939b-41bc-8394-739e984c6915.png)

Question 1 stated that one or more Bar can be associated with a Foo, instead of one or more Foo are associated with 1 Bar.
![image](https://user-images.githubusercontent.com/50315976/216755020-437b7f43-98a5-4e88-9c7d-c963d26d4a4c.png)

Question 2 stated that a Bar should be connected to at least 1 Foo, instead of a Foo should be connected to at least 1 Bar.
![image](https://user-images.githubusercontent.com/50315976/216755059-e2605845-6994-4c94-b63a-32aee14e0a46.png)

May I know which is the correct way to read multiplicity?

**Comment by damithc** [comment]
@venuslimm As this pertains to the lecture, I'll leave it to be answered by prof Ganesh. He is away from his computer right now but should be back by tonight or tomorrow.

**Comment by ganeshniyer** [comment]
@venuslimm 

Let me confirm that, text book explanation is right. When we interpret multiplicity, we should start interpreting from the other end. i.e., 

For the first question,  it is, "one or more Foo are associated with 1 Bar"

For the second question, "one foo object must be pointed to 1 or more bar objects."

Hope this is clear now. I will correct it in the next lecture to the class as well. Please let me know if you have any further questions.

**Comment by euph00** [comment]
Thanks for this issue, got really confused right off the bat while I was watching the lecture recording just now. Also thanks to profs for responding on a Saturday afternoon/night.

**Comment by venuslimm** [comment]
Thanks profs for the response!
