### ISSUE TITLE
Scoping in Switch Statements

### ISSUE THREAD

**Issue by PeanutButters93** [nus-cs2103-AY2223S2/forum#143]
The following code gives me an error
```
switch (foo) {
case 1:
    int bar = 1;
    /* ... */
case 2:
    int bar = 2;
    /* ... */
}
```
```
variable bar is already defined in method main(String[])
```
To circumvent it, I declared the variable outside the switch statement, but now it is not in the least possible scope
```
int bar;
switch (foo) {
case 1:
    bar = 1;
    /* ... */
case 2:
    bar = 2;
    /* ... */
}
```

After reading #130, I realized I could write it like this with braces, but it does not look very clean
```
switch (foo) {
case 1: {
    int bar = 1;
    /* ... */
}
case 2: {
    int bar = 2;
    /* ... */
}
}
```

I often run across this problem when doing regex and need to access the Matcher object twice so I have to give it a name. Which is the better option? or is there an alternative?

**Comment by ryanchua00** [comment]
I often run into the same dilemma, and declare the variable outside the switch statement. Funnily enough, [Oracle docs](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/switch.html) also declares the variable outside the statement.
Would the fall through condition help in your case?

**Comment by hingen** [comment]
Hard to give an exact solution as I think the "best" way depends on the exact scenario.

Personally, in most situations, I avoid the problem entirely by having each of my case blocks simply call a method that handles that specific case. I find that it keeps the method short, helps in maintaining SLAP, and also makes it easier for me to find the relevant code when I need to.

```java
void bar() {
    switch (foo) {
    case 1:
        handleCase1();
    case 2:
        handleCase2();
    default:
        // <some code>
}

void handleCase1() {
    int bar = 1;
    // <code for case 1>
}

void handleCase2() {
    int bar = 2;
    // <code for case 2>
}
```

Alternatively, sometimes, I prefer extracting the switch block into it's own method:
```java
void bar(Foo foo) {
    int baz = bar(foo);
    // <some code>
}

int bar(Foo foo) {
    switch (foo) {
    case 1:
        return 1;
    case 2:
        return 2;
    default:
        // <some code>
}
```

**Comment by Lava-Iris** [comment]
If the two cases are entirely separate, i.e., you don't need to check for case 2 after it checks true for case 1, you can add a break after the case statement. Otherwise, the switch will keep checking and executing the code for case 2, case 3 and so on even after case 1 is true.
```
switch (foo) {
case 1:
    int bar = 1;
    /* ... */
    break;
case 2:
   int bar = 2;
    /* ... */
    break;
default:
    /*...*/
}
```
should do the trick.

**Comment by BoAi01** [comment]
Here is one side comment: It may not be good to use braces in switch structure, as switch is normally intended for switching between short statements. If there are many lines of code in each case, it might be better to use if-else instead, and in this case we are free to declare new variables.

**Comment by PeanutButters93** [comment]
Thanks for all the advice everyone.
I think extracting the cases to separate function seems to be the most elegant and is what I'll use.
