### ISSUE TITLE
[A-CI] unable to push my changes to GitHub

### ISSUE THREAD

**Issue by Merrickneo** [nus-cs2103-AY2223S2/forum#144]
Followed the instructions listed for A-CI but I am unable to push my changes to Github for some reason.
 [https://se-education.org/guides/tutorials/githubActions.html](https://se-education.org/guides/tutorials/githubActions.html)

The error message is attached here.
<img width="551" alt="Screenshot 2023-02-07 at 12 51 13 AM" src="https://user-images.githubusercontent.com/71166759/217033993-405203e9-3196-4800-a5c1-cee58fd2a83f.png">

My directory is attached here as well
<img width="1285" alt="Screenshot 2023-02-07 at 12 57 25 AM" src="https://user-images.githubusercontent.com/71166759/217035026-026e3ae2-b7cf-44d5-93dc-064fccb1b764.png">

I think it has got to do with the "OAuth scope" of GitHub but I'm not sure of how to address this. Would appreciate any help on the matter!

**Comment by Junyi00** [comment]
Are you using a personal access token for authentication? If so, the problem could be that your personal access token does not have this option enabled:

<img width="673" alt="image" src="https://user-images.githubusercontent.com/54541329/217041636-a8c16314-dea5-47db-9194-97e83bee4d72.png">

Enabling this should allow you to push `gradle.yml` that updates the GitHub action workflows

**Comment by Irminrics** [comment]
Hi. You need to rename your folder from workflows to workflow. This would solve the problem!

**Comment by Merrickneo** [comment]
Created a new PAT and it worked! Thanks, everyone 👍
