### ISSUE TITLE
Regarding Week 5 Jar File

### ISSUE THREAD

**Issue by MrTwit99** [nus-cs2103-AY2223S2/forum#146]
Supposed I created the JAR file with JavaFX libraries successfully, is the JAR file supposed to show the GUI when i run the following command?

```ruby
java -jar XX.jar
```

Or is this suppose to only show the CLI since it is on Command Prompt when the JAR file is being executed. Not sure if there's any error in my JAR file creation, it is 11MB > 5MB so i suppose quite likely my JavaFX files are inside. I will upload my JAR file with JavaFX libraries onto my release for referencing.

**Comment by Junyi00** [comment]
Referencing your `build.gradle` file, it seems that the property`mainClassName` is not correctly configured to point towards your `Launcher` class.

```gradle
application {
    mainClassName = "seedu.duke.Duke"
}
```

Updating the property to point towards the `Launcher` class instead could be the fix for this issue.

**Comment by MrTwit99** [comment]
@Junyi00 
Thanks for the help but unfortunately, it did not manage to solve this issue. Still no GUI being opened.

my `build.gradle` file currently looks like this after the change:
```ruby
application {
    mainClassName = "seedu.duke.Launcher"
}
```

**Comment by muhammadreyaaz** [comment]
@MrTwit99 it is because you have no seedu package in your directory. Change it to just duke.Launcher and it should work. I tested it and the jar file launches the GUI

`
application {
    mainClassName = "duke.Launcher"
}
`

**Comment by MrTwit99** [comment]
Alright, thanks!

**Comment by MrTwit99** [comment]
@ARPspoofing Could I just clarify with you on the steps you took to create the JAR file again?

Is it File > Project Structure > Artifacts > + > JAR > From modules with dependencies > Main class = Launcher (duke) > Build Artifacts? 

Or do I need to select JavaFX application instead of JAR?

**Comment by SPWwj** [comment]
> @ARPspoofing Could I just clarify with you on the steps you took to create the JAR file again?
> 
> Is it File > Project Structure > Artifacts > + > JAR > From modules with dependencies > Main class = Launcher (duke) > Build Artifacts?
> 
> Or do I need to select JavaFX application instead of JAR?

Do not build from intelliJ.
Use gradle.
Output jar will appear in the ~ip/build/libs
<img width="755" alt="shadowJar" src="https://user-images.githubusercontent.com/30100720/217470177-a12b63ff-e8bf-4ed1-9cc3-f1d9a14c10dd.png">

**Comment by MrTwit99** [comment]
Oh! I was wondering what they meant by building via gradle. Thanks!

**Comment by muhammadreyaaz** [comment]
@MrTwit99 yeap like what @SPWwj said, I did not build using intelliJ. But it seems that your issue is already resolved :)
