### ISSUE TITLE
Unable to get the images to appear on my GUI

### ISSUE THREAD

**Issue by benjamin-wee** [nus-cs2103-AY2223S2/forum#147]
I followed the code for tutorial 4 on Using JavaFX and FXML completely, and the other features of my GUI are working completely fine, but I am simply unable to get my images to load on the GUI.

The code that I used to initialise the images is attached below:
<img width="853" alt="Screenshot 2023-02-08 at 8 02 26 AM" src="https://user-images.githubusercontent.com/77018967/217395269-0603fb38-ac32-4c0f-b6e7-9e3adeb4cb8e.png">

The following is my project directory
<img width="321" alt="Screenshot 2023-02-08 at 8 02 51 AM" src="https://user-images.githubusercontent.com/77018967/217395369-d2085a40-2c9a-41a5-a2b1-e2f1d21d66b6.png">

Has anyone else faced a similar issue and know how to fix this? Thank you!

**Comment by Guo-KeCheng** [comment]
Hi @benjamin-wee , I also had this issue when I did my GUI but I solved it by adding the 'images' directory. But from your screenshot, it looks like you did that already. 

Could you try using an absolute path from the root?

**Comment by damithc** [comment]
@benjamin-wee while waiting for inputs from others, some things you can try:
1. compare your code with others who posted in #104 
2. Push the code to a branch and share here so that other can try to replicate the problem.

**Comment by francisyzy** [comment]
Have you tried another set of images? Sometimes the image is actually `.jpeg` but it's labeled as `.png` and java might not render it properly.

**Comment by benjamin-wee** [comment]
> Have you tried another set of images? Sometimes the image is actually `.jpeg` but it's labeled as `.png` and java might not render it properly.

Turns out this was the issue! I actually downloaded a .webp image and converted it to png to be used and maybe that's why it didn't work. I just tried downloading a png image from the sort to be used and my gui works fine now! Thank you so much for your help!
