### ISSUE TITLE
Question regarding assertions

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#148]
When my program meets an assertion that is supposed to be true (but is false), is my GUI supposed to terminate immediately? Or is the user supposed to see the message that is accompanied by the AssertionError? Currently I am only receiving the AssertionError on my console

**Comment by damithc** [comment]
@FredericChow00 that should be good enough, as it is the default Java behavior. After all, the assertion failure can happen even before the GUI is started up.

**Comment by FredericChow00** [comment]
> @FredericChow00 that should be good enough, as it is the default Java behavior. After all, the assertion failure can happen even before the GUI is started up.

Got it thanks prof!
