### ISSUE TITLE
GUI not in English?

### ISSUE THREAD

**Issue by kalarisng** [nus-cs2103-AY2223S2/forum#149]
hi, does anyone know why the GUI did not appear in English?
<img width="1269" alt="Screenshot 2023-02-08 at 4 35 47 PM" src="https://user-images.githubusercontent.com/97084261/217508541-a1cf43f7-72f6-4dfd-9758-6d74ce166f3c.png">

**Comment by francisyzy** [comment]
Similar issues:
https://github.com/nus-cs2103-AY2223S2/forum/issues/68
https://github.com/nus-cs2103-AY2223S2/forum/issues/78

Try and see if those solutions will help with Mac Java issues

**Comment by kalarisng** [comment]
> Similar issues: #68 #78
> 
> Try and see if those solutions will help with Mac Java issues

addressbook.jar returns a version with the correct form
<img width="742" alt="Screenshot 2023-02-08 at 10 00 35 PM" src="https://user-images.githubusercontent.com/97084261/217551123-2c99d3ba-021f-46a6-a120-22d70be24b00.png">

however, launching the GUI is still giving me the wrong font. the error is as such:
<img width="1314" alt="Screenshot 2023-02-08 at 9 54 55 PM" src="https://user-images.githubusercontent.com/97084261/217551271-5966e3e8-fd62-4d1a-ad64-b8a84eb5e931.png">
