### ISSUE TITLE
Automated Duke Testing Query

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#15]
Hi there,

Sorry for opening yet another query so soon, but I feel that the instructions given in the page here, for automating the Duke testing using runtest.bat, are a little hard to understand for me.

https://se-education.org/guides/tutorials/textUiTesting.html

Step 4 and 5 in particular are confusing, where we need to set up the EXPECTED.txt and input.txt files with the outputs and commands. I have no idea how they are supposed to be formatted. (especially since my Duke messages have borders around them)

Could there be an example EXPECTED.txt and input.txt file for us to see and get a better idea of how to format the text inside?

**Comment by hingen** [comment]
`input.txt` should contain each command, line-by-line, in the order you want to feed it to the program.
For example:
```
todo lorem ipsum
mark 1
bye
```
This would be the same as running the program and inputting the command `todo lorem ipsum`, then after the program has taken the command and printed the output, you enter the line `mark 1`, and so on. Note that empty lines in `input.txt` will be inputted as is. That is it is treated the same as if you entered nothing and just press enter.

`EXPECTED.txt` is what you expect the output of the program to be given the input that you put in via `input.txt`.
So from the above example input, the expected output could be this (or something else depending on your program):
```
    ____________________________________________________________
     Hello from
      ____        _        
     |  _ \ _   _| | _____ 
     | | | | | | | |/ / _ \
     | |_| | |_| |   <  __/
     |____/ \__,_|_|\_\___|
     
     What can I do for you?
    ____________________________________________________________

    ____________________________________________________________
     Got it. I've added this task:
       [T][ ] lorem ipsum
     Now you have 1 tasks in the list.
    ____________________________________________________________

    ____________________________________________________________
     Nice! I've marked this task as done:
       [T][X] lorem ipsum
    ____________________________________________________________

    ____________________________________________________________
     Bye. Hope to see you again soon!
    ____________________________________________________________
```

When you run the script, an `ACTUAL.txt` file will be produced that is the actual output of the program given `input.txt`. The script will then attempt to compare the contents of `EXPECTED.txt` and `ACTUAL.txt`. If they match, then your test will pass, else it fails.

**Comment by hingen** [comment]
To create `EXPECTED.txt`, make sure you have an empty or placeholder `EXPECTED.txt` then run the test script. The test will fail but you would get an `ACTUAL.txt` file from it. Look through `ACTUAL.txt`. If you deem that it's output is correct, then delete your current `EXPECTED.txt` and rename `ACTUAL.txt` to `EXPECTED.txt`.

**Comment by BoAi01** [comment]
I agree with the above example. 

To add on, `input.txt` should contain exactly the strings that go into `System.in` (e.g., input to the `Scanner` read from keyboard), and `EXPECTED.txt` should contain exactly the string that should go out from `System.out` (i.e., printed values). These are standard I/O streams. See [here](https://www.javatpoint.com/linux-input-output-redirection) for more information about I/O steams and redirection.

**Comment by damithc** [comment]
> To create `EXPECTED.txt`, make sure you have an empty or placeholder `EXPECTED.txt` then run the test script. The test will fail but you would get an `ACTUAL.txt` file from it. Look through `ACTUAL.txt`. If you deem that it's output is correct, then delete your current `EXPECTED.txt` and rename `ACTUAL.txt` to `EXPECTED.txt`.

Good tip @hingen -- this is a good strategy to create the first version of the `EXPECTED.txt`.
Alternatively, you can run the program once while directing the actual output to the `EXPECTED.txt` 
(i.e., `java .... < input.txt > EXPECTED.txt`).

**Comment by Zxun2** [comment]
> To create `EXPECTED.txt`, make sure you have an empty or placeholder `EXPECTED.txt` then run the test script. The test will fail but you would get an `ACTUAL.txt` file from it. Look through `ACTUAL.txt`. If you deem that it's output is correct, then delete your current `EXPECTED.txt` and rename `ACTUAL.txt` to `EXPECTED.txt`.

Another tip: if you are using Intellij, you can click on `ACTUAL.TXT` and right-click on "Compare with..." to produce a visual plot of the difference between `ACTUAL.TXT` and `EXPECTED.TXT`. To make it even easier, there's an option for you to accept the changes in the `ACTUAL.TXT` file.

**Comment by Tempura-Person** [comment]
Hi there,

Step 3 of the automation needs me to 
"Update the javac and java commands in the script to match the name/location of your main class."

how exactly do we do that?
I assume its this line in the runtest.bat file that has to be "updated"?
many thanks.

`
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`

**Comment by Tempura-Person** [comment]
Another thing, the following error pops up if i try to run runtest.bat as is:

cmd.exe /c runtest.bat
'javac' is not recognized as an internal or external command,
operable program or batch file.
********** BUILD FAILURE **********

Process finished with exit code 1

what exactly is this?

**Comment by hingen** [comment]
> cmd.exe /c runtest.bat 'javac' is not recognized as an internal or external command, operable program or batch file. ********** BUILD FAILURE **********
> 
> Process finished with exit code 1

Can you try opening a command prompt and running `javac --version`?
If you get a `'javac' is not recognized as an internal or external command`, then most likely your environment variables were not set up correctly.

**Comment by hingen** [comment]
> Hi there,
> 
> Step 3 of the automation needs me to "Update the javac and java commands in the script to match the name/location of your main class."
> 
> how exactly do we do that? I assume its this line in the runtest.bat file that has to be "updated"? many thanks.
> 
> ` javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java`

I believe this is only applicable if you move your `Duke.java` into a package. So let's say, `Duke.java` is in the `duke` package, then you will have to update the command to be
 ` javac -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\*.java`

Also, on a side note, probably better to create a new GitHub issue for each problem you face. Else this issue thread is going to get extremely messy with a mixture of comments addressing the different problems.

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213438810-50d33fac-a320-4ac7-aa7f-6d8087158f75.png)
oh, uh...
is this cause for concern?

**Comment by hingen** [comment]
> ![image](https://user-images.githubusercontent.com/92144641/213438810-50d33fac-a320-4ac7-aa7f-6d8087158f75.png) oh, uh... is this cause for concern?

Could you try using a normal command prompt instead of Windows Powershell? As in, use cmd, not powershell. This seems to be the recommendation on the [CS2103 site](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/testing.html#automated-testing-of-cli-apps)

**Comment by Tempura-Person** [comment]
ah, yep.
![image](https://user-images.githubusercontent.com/92144641/213439441-7c8d5275-bddf-4121-b9fb-850f445c5793.png)

**Comment by hingen** [comment]
Just want to check to be 100% sure, but have you installed java11?

If so, then your environment path variable is likely not configured properly. Perhaps try watching this [video](https://youtu.be/RBuZHg6eyIs). Skip to 3:00 in the video.

**Comment by zm-l** [comment]
For me I reinstalled Java as I previously have JRE only not JDK, I think you can check in the "c:\program files\java\".

**Comment by Tempura-Person** [comment]
Alright, so it was apparently that i did NOT install JDK.
oops.
