### ISSUE TITLE
Question on tagging of commits

### ISSUE THREAD

**Issue by tohyuting** [nus-cs2103-AY2223S2/forum#150]
[tutor here posting a question on behalf of a student]

When are we suppose to add tag for A-Assertions and A-CodeQuality? More specifically, do we need to tag them when pushing the respective branches to GitHub, or do we tag them after we merge the branches with the Main branch.

If we need to add tag after merge, how am I suppose to do it for the first branch that has been merged to Main branch as it is considered merged at GitHub instead of inside SourceTree?

**Comment by jundatan** [comment]
I think you can pull the merged into your local repo and tag them and push it to github.

**Comment by damithc** [comment]
> When are we suppose to add tag for A-Assertions and A-CodeQuality? More specifically, do we need to tag them when pushing the respective branches to GitHub, or do we tag them after we merge the branches with the Main branch.

As before, after merging.
![image](https://user-images.githubusercontent.com/1673303/217712803-82ad3abe-1d13-4b02-a1ea-5137f442f561.png)

Specifically for PRs:
![image](https://user-images.githubusercontent.com/1673303/217713329-6d3ae31c-a55d-426c-b120-70c04956d504.png)

**Comment by tohyuting** [comment]
Hi all, thank you for the answers provided above by Jun Da and Prof. Damith. Those answers managed to resolve the question and issue faced by the student.
