### ISSUE TITLE
unreported exception error when implementing streams

### ISSUE THREAD

**Issue by PeanutButters93** [nus-cs2103-AY2223S2/forum#153]
I have an issue trying to implement streams. This is my code:

```java
    public void loadFromStorage() throws FileNotFoundException, InvalidFormatException {
        storage.retrieveContents()
                .stream()
                .map(row -> Task.factoryMethod( //This is the method that throws InvalidFormatException
                        row.charAt(1),
                        row.charAt(4),
                        row.substring(7),
                        parser))
                .forEach(x -> tasks.add(x));
    }
```
And I am having this error
```java
error: unreported exception InvalidFormatException; must be caught or declared to be thrown
                .map(row -> Task.factoryMethod(
    }
```
Instead of streams, i was using a for loop and it worked fine. Now, my compiler does not seem to recognise my InvalidFormatException  is being thrown (it is greyed out). Does anyone know how to solve this issue?

**Comment by SPWwj** [comment]
Hi you may refer to this post for solutions: [Java Stream with exception handling ](https://dzone.com/articles/exception-handling-in-java-streams)

**Comment by PeanutButters93** [comment]
Thanks for the swift reply! It slipped my mind that streams don't work with checkedExceptions. I've extracted out the lambda function and threw a runtime exception instead - as suggested in the post.

**Comment by domlimm** [comment]
Hello @PeanutButters93, I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once your problem has been resolved. Have a great day! 😄

**Comment by PeanutButters93** [comment]
Thanks for the reminder! I must have accidentally unchecked the close with comment button.
