### ISSUE TITLE
Encounter exception when building with gradle 

### ISSUE THREAD

**Issue by cmang12** [nus-cs2103-AY2223S2/forum#154]
Hello, I tried to run gradle but it threw an error. 

![image](https://user-images.githubusercontent.com/85399634/217794098-0012ee32-039c-4b23-a4ae-1378534d1763.png)

My build.gradle file looks like this:
```
plugins {
    id 'checkstyle' 
    id 'java'
    id 'application'
    id 'com.github.johnrengelman.shadow' version '5.1.0'
}
```
```
dependencies {
    testImplementation group: 'org.junit.jupiter', name: 'junit-jupiter-api', version: '5.5.0'
    testRuntimeOnly group: 'org.junit.jupiter', name: 'junit-jupiter-engine', version: '5.5.0'

    String javaFxVersion = '11'

    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-base', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-controls', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-fxml', version: javaFxVersion, classifier: 'linux'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'win'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'mac'
    implementation group: 'org.openjfx', name: 'javafx-graphics', version: javaFxVersion, classifier: 'linux'
}

application {
    mainClassName = "seedu.duke.Main"
}

shadowJar {
    archiveBaseName = "duke"
    archiveClassifier = null
}
```
Does anyone know what's wrong? Thank you!

**Comment by hingen** [comment]
Likely caused by this part of your `build.gradle`
```
application {
    mainClassName = "seedu.duke.Main"
}
```

Perhaps, try changing `seedu.duke.Main` to `<package_name>.Main` where `<package_name>` is the name of the package containing your `Main` class.

Looking at your code, it should probably be:
```
application {
    mainClassName = "duke.Main"
}
```

**Comment by cmang12** [comment]
Hmm it still doesn't work. I also tried duke.Launcher, it showed this: 
![image](https://user-images.githubusercontent.com/85399634/217877148-21d4ac29-4602-444e-a3f2-91c15dec2afe.png)

**Comment by Junyi00** [comment]
I believe the correct configuration should be `duke.Launcher`. Nonetheless, I believe this error could mean you are using the wrong JDK version?

**Comment by cmang12** [comment]
I checked my project structure and I'm using JDK 11. Also, inside the gradle-wrapper.properties file, the distribution url is: distributionUrl=https\://services.gradle.org/distributions/gradle-6.2-bin.zip, 
if it matters.

**Comment by BoAi01** [comment]
I am not sure if Java version would lead to such an issue, but I have been using the Azul build of OpenJDK 11 version as suggested [here](https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html#programming-language) and I have not encountered any version-related issues so far. 

P.S. I am using an M1 mac.

**Comment by muhammadreyaaz** [comment]
Perhaps you could try the --status command to see which Daemon is giving problem and stop it using --stop? It seems that is the one causing the issue

**Comment by danielk0k** [comment]
Hi, I believe @hingen and @Junyi00 are on the right track. `java.lang.NoClassDefFoundError` is usually caused by incorrect application path. I've checked your repo and the correct path should be `duke.Launcher` as that is the entry point of the program.

**Comment by florentianayuwono** [comment]
Hi, I am from senior batch, encountered similar error last semester, here is the [Issue link](https://github.com/nus-cs2103-AY2223S1/forum/issues/68).

Summary of what I did:
1. Change the application path. In my case it is `duke.Duke` instead.
2. To avoid configuration conflict, can try running the test not from terminal, by: click the dropdown menu next to the `ip [assemble]` Run button in your top right of Intellij, click on Edit Configurations, Click the Add new Configuration (+), choose the name for your configuration, then add the gradlew test types you want to run. Click Apply and now you can run the tests by selecting from the dropdown menu instead from the terminal.

Hope this helps!

**Comment by johnrhimawan** [comment]
Hi @cmang12 , I'm from your senior batch. A quick reminder too to restart your IDE after editing your `build.gradle` file so that the changes will take place!

**Comment by RussellDash332** [comment]
Hi @cmang12, I'm from your senior batch. Here's the summary of what you should do and what to do in case a similar issue happens again:
1. Restart your IDE as mentioned by @johnrhimawan. This will reload all the changes done in your configuration files such as `build.gradle` and the `.idea` directory.
2. Make sure your entry point inside `build.gradle` is correct as mentioned by @florentianayuwono . Depending on your code implementation, the class path must be adjusted manually. Seems that most comments have figured out that the application path must be `duke.Duke` and the launcher path must be `duke.Launcher`.

Hopefully this summarizes the comments well!

**Comment by Hongyi6328** [comment]
Hi @cmang12, I am also from your senior batch. If all abovementioned solutions don't work, you can also try invalidating the cache and cleaning the project.

**Comment by Guanzhou03** [comment]
Hi @cmang12, I'm from your senior batch.
If the aforementioned methods do not work, it might be a problem with your gradle version that has some compatibility issues with your JDK. 
Similar to @BoAi01, I ran the Azul build of OpenJDK 11 with no problems, so you could consider changing to that build.

**Comment by cmang12** [comment]
Hi everyone thank you for the suggestions, I changed the application path and restarted my IDE. Still, running gradle through terminal doesn't work. However, I ran shadowJar through the gradle tab and the build was successful. Is this a JDK compatibility issue?

**Comment by florentianayuwono** [comment]
Most likely compatibility issue. It might be that your IntelliJ is indeed in JDK 11, but your actual terminal is running on different JDK version. You can check by typing `java -version` in your terminal! :)

**Comment by cmang12** [comment]
Ah I see the problem now, thanks everyone!
