### ISSUE TITLE
Adding extension for BCD

### ISSUE THREAD

**Issue by thennant** [nus-cs2103-AY2223S2/forum#155]
Hi can i check for adding extension-BCD, by extension does it means adding it as a new task type (like the user will enter a new command and the task executes it) or the extension is supposed to be extending off an existing task type and does the job automatically or are we free to decide this ourselves?

**Comment by JamesLiuZX** [comment]
Hi, I think it depends on the exact extension you choose. For example for `C-Help`, it likely requires adding a new 'help' command to display a help page; while for `C-FriendlierSyntax`, it involves modifying existing commands. So it is up to you and based on which exact one you choose.

**Comment by damithc** [comment]
> Hi, I think it depends on the exact extension you choose. For example for `C-Help`, it likely requires adding a new 'help' command to display a help page; while for `C-FriendlierSyntax`, it involves modifying existing commands. So it is up to you and based on which exact one you choose.

@JamesLiuZX is correct.

**Comment by thennant** [comment]
ok tks!
