### ISSUE TITLE
Editing commit message after pushing

### ISSUE THREAD

**Issue by ZhuLeYao** [nus-cs2103-AY2223S2/forum#157]
It is not my latest commit but it is my latest commit of another branch. Will it be a good idea to check out the branch of the message I want to edit, go under the repository and select interactive rebase? Will the edit cause me to just rebase this branch onto itself or will my latest commit in other branches be rebased into this branch too? Also there is a noop message when I select interactive rebase, not sure what it means

**Comment by JamesLiuZX** [comment]
Hi, if its the latest commit in branch B that you want to edit, normally I'd just `git reset HEAD `and recommit the changes with the updated committed message then push. 

In response to your question, AFAIK it only affects the branch that you run interactive rebase on. Where rebase plays back the latest n commits, interactive replay gives you the chance to edit the individual commits, by editing the interactive rebase script. You can achieve this by changing the `pick` to `edit`. 

For example, if these are your latest commits and you want to change the latest one, 
```
310154e Update README formatting and add blame
f7f3f6d Change my name a bit 
```
This should be your script:
```
edit 310154e Update README formatting and add blame
pick f7f3f6d Change my name a bit
```
You can refer to this[ tutorial](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#:~:text=The%20interactive%20rebase%20gives%20you,first%20one%20it%20will%20replay.) for more information. 
What `noop `(no operation) essentially means is that you either did not edit the commits, or when you rebase a branch that's ahead in commits to a branch that's behind in commits, e.g. when you rebase `master` onto `branchA`.

In your case it should be the former and you can try editing the script in the manner shown in the tutorial.

Let me know if you need any further clarification. Cheers :)

**Comment by ZhuLeYao** [comment]
Thank you so much! Based on your first paragraph, I tried git commit amend instead as I realised it works for the latest commit of the branch too instead of the latest commit of the entire repo. Read up on the tutorial too and it was useful!
