### ISSUE TITLE
Issues building gradle

### ISSUE THREAD

**Issue by shenchenzizoe** [nus-cs2103-AY2223S2/forum#158]
Has someone encountered similar gradle building issues before? After I installed the gradle, it keeps throwing the error "Could not find or load main class worker.org.gradle.process.internal.worker.GradleWorkerMain" when I click the "build".  However, for the functions like "clean" and "shadowJar", it works fine. I thought it might be a path problem, so I changed mainClassName and archive base name in build.gradle several times, but I haven't figure out the right one. Other things I tried including adding new path to local environment, and running "gradle —stop" and rebuilding, none of them works.
The following are the list of my ip directories and my build.gradle content.  I have been dealing with it for hours and can really use some help :<< (save me!
<img width="310" alt="image" src="https://user-images.githubusercontent.com/97273558/218030113-83a96572-e779-4df7-8c9b-04ec7b0e5113.png">
<img width="760" alt="image" src="https://user-images.githubusercontent.com/97273558/218030375-4a15e10b-ea6f-4f6d-864d-9846f256b2ff.png">
<img width="883" alt="image" src="https://user-images.githubusercontent.com/97273558/218030433-a88312ba-757b-49ec-9de5-71d8ae399f2b.png">

**Comment by SPWwj** [comment]
Hi the correct configuration is:
`
application {
    mainClassName = "Duke.Duke"
}
`
The mainClassName is defines as the pakage name follow by the class name.
Your package name is: `Duke`
Your class name is also: `Duke`
the the full qualifier name should be `Duke.Duke.`

Just a small suggestion that you might want to change your Duke directory folder to duke or something else that start with small letter, else you will encounter checkstyle error if you use the checkstyle plugin.

**Comment by shenchenzizoe** [comment]
@SPWwj Hiii thank you for the kind reply! I just tried this and the same error occurs, but I will change the directory name to duke then :)

**Comment by SPWwj** [comment]
> @SPWwj Hiii thank you for the kind reply! I just tried this and the same error occurs, but I will change the directory name to duke then :)

My bad did not pay attention to your screenshot 😅 .
I check your github repo and from your screenshot you have move your `Duke.class `outside of `Duke `package.
Thus your Fully qualified Name should be `Duke ` only

**Comment by damithc** [comment]
@shenchenzizoe Do get rid of all other folders/files inside `src/main/java` except folders that represent Java packages. It is for Java packages/files only. Gradle expects the package folders to reside exactly in that folder. You can compare yours with the folder structure of the iP of others who has replied here.
Also, put all classes inside a package. It's not advisable to put some inside packages while keeping others in the root.

**Comment by shenchenzizoe** [comment]
Thank you for the suggestions Prof! I have just removed other folders in src/main/java as well as changed folder structures referring to others'. For now I kind of can't find any more differences but the building function still does not work...still trying hard to figure it out

**Comment by damithc** [comment]
@shenchenzizoe Try running Gradle using the terminal e.g., `.\gradlew clean run`

While waiting for inputs from others, you can push the code to a branch and share here so that other can try to replicate the problem.

**Comment by JamesLiuZX** [comment]
Hi, it could be a problem with the gradle cache. Perhaps you could try emptying the `.gradle/caches` after running `./gradlew --stop`.

**Comment by shenchenzizoe** [comment]
hii! I tried .\gradlw clean as well as .\gradlew stop, but the build function (by clicking the button under gradle list) still does not work. However I am able to run my code on gradle. I can also build jar file with it, so I suppose the issue might not matter for now?

**Comment by damithc** [comment]
@shenchenzizoe Is it that all gradle commands work via the command line but not via the Intellij UI?
Anyway, it might help if you push the code to a branch and share here so that other can try to replicate the problem.

**Comment by Hikoya** [comment]
Hello @shenchenzizoe  , I'm a senior from a previous batch, is there any updates to this issue? If the issue has been resolved, please remember to close the issue or share your branch here as per what prof recommends.
