### ISSUE TITLE
Mistakenly did Level-10 on master 

### ISSUE THREAD

**Issue by benjamin-wee** [nus-cs2103-AY2223S2/forum#159]
I did my GUI implementation on master and did not do it on a separate branch by mistake. I have already pushed my changes and moved on to week 5 increments. May I ask if there is any way to resolve this? Thank you!

**Comment by FredericChow00** [comment]
I did the same too... I just literally created the new level 10 branch on the spot and pushed it to my fork haha.

Not sure if I should've done it diffferently though

**Comment by francisyzy** [comment]
See: https://github.com/nus-cs2103-AY2223S2/forum/issues/137#issuecomment-1416647054

**Comment by benjamin-wee** [comment]
> See: [#137 (comment)](https://github.com/nus-cs2103-AY2223S2/forum/issues/137#issuecomment-1416647054)

thank you so much!
