### ISSUE TITLE
tP Team Repo Setup: Point 6 Create team PR

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#163]
Hey all,

For tP Team Repo Setup: Point 6 Create team PR, im unable to create a PR unless there are some changes made. So does this mean we have to "force" to do some changes before making PR?

Thanks!

**Comment by damithc** [comment]
@seadragon2000341 you can create the PR _after_ some changes have been committed.

**Comment by Merrickneo** [comment]
For my group, we just edited the README.md file. After pushing to GitHub, we were able to do the Pull Request. Hope this helps!

**Comment by Hikoya** [comment]
Hello @seadragon2000341  , I'm a senior from a previous batch, is there any updates to this issue? If the issue has been resolved, please remember to close the issue! :)
