### ISSUE TITLE
Error in online textbook:   UML → Sequence Diagrams → Minimal Notation

### ISSUE THREAD

**Issue by tituswe** [nus-cs2103-AY2223S2/forum#164]
Just for clarity, as this might be a very obvious question, is there a slight error in the sequence diagram shown below?

![Screenshot 2023-02-12 at 2 01 20 AM](https://user-images.githubusercontent.com/97359862/218273834-f0bc2a6d-0f59-4ba5-a2cd-dfd456b2d3f4.png)

I believe that the return value should be a dashed arrow line pointing left.

Thank you in advance for the clarification!

**Comment by damithc** [comment]
> I believe that the return value should be a dashed arrow line pointing left.

That's correct @tituswe , but some return arrows can be omitted altogether, which is the case for this diagram.

**Comment by tituswe** [comment]
@damithc Oh okay thanks prof! I just realized that the function call was _get minefield info_... Thanks for the clarification!!
