### ISSUE TITLE
Clarification about branch creation for week5 iP tasks

### ISSUE THREAD

**Issue by glyfy** [nus-cs2103-AY2223S2/forum#166]
Hi can I check the branches A-Assertions, A-CodeQuality, A-Streams are branching off from the master branch at the same point as the level-10 branch?
Therefore at the point that I am branching them off the changes in Level-10 branch have not been implemented yet?

**Comment by damithc** [comment]
@glyfy ![image](https://user-images.githubusercontent.com/1673303/218292363-a8c1986e-9637-4585-94f0-9f5dade49b64.png)

A-Checkstyle, Level-10, and A-Varargs are to be done as branches. The branches need not be parallel. 
That is, for each of them,
1. start a branch, 
2. add the increment in the branch, 
3. merge to master branch when ready.

A-Assertions, A-CodeQuality, A-Streams are not even in that week, so there is no relation between Level-10 and those increments.

**Comment by Hikoya** [comment]
Hello @glyfy  , I'm a senior from a previous batch, is there any updates to this issue? If the issue has been resolved, please remember to close the issue! :)

**Comment by glyfy** [comment]
Yes it has been resolved. I now understand that after starting branch and incrementing I was supposed to merge it back to master.
Thank you.
