### ISSUE TITLE
Messed up git tagging & branching

### ISSUE THREAD

**Issue by tricixg** [nus-cs2103-AY2223S2/forum#167]
When completing week 3's task that required parallel branching. I did not use branches and committed them straight to master. After trying to rectify the branching my code for tags A-JavaDoc, A-CodingStandard and Level-9 were all the same. Will this affect the IP grading in the future? if so how can I rectify this

**Comment by JamesLiuZX** [comment]
Hi, for git tagging a previous commit, you can use
`git tag -a tagname commitId -m "Message here"`
You can refer to [here](https://stackoverflow.com/questions/4404172/how-to-tag-an-older-commit-in-git) for the example.

For branching a previous commit, you can `git branch` a new branch with the new branch name and commitid, as seen [here](https://stackoverflow.com/questions/2816715/branch-from-a-previous-commit-using-git#:~:text=First%2C%20checkout%20the%20branch%20that,name%20then%20create%20a%20branch!) 

Hope that helps!

**Comment by damithc** [comment]
> Will this affect the IP grading in the future? if so how can I rectify this

@tricixg Unlikely, as we allow for a some margin of error when doing the iP. Try to miss more requirements in the future. Also, keep trying until you are confident that the intended learning outcome of the increment has been achieved (e.g., learning how to branch/tag).

**Comment by Hikoya** [comment]
Hello @tricixg , I'm a senior from a previous batch, is there any updates to this issue? If the issue has been resolved, please remember to close the issue! :)
