### ISSUE TITLE
[ip] Number of JUnit test cases needed

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#168]
If I recall correctly, we only need to test public methods. But among them, some are not easy to be tested, e.g., due to dependencies on other classes or other methods, which makes Junit testing not straightforward. Is there a hard requirement on the proportion of the code that must be covered by JUnit test cases?

**Comment by damithc** [comment]
@BoAi01 the official requirement is as follows:
![image](https://user-images.githubusercontent.com/1673303/218297598-32f39602-053a-4b5f-8a80-1e106dd3a67b.png)

**Comment by BoAi01** [comment]
@damithc  Thank you for the prompt reply!

Does this requirement also apply to `A-MoreTesting`?

**Comment by damithc** [comment]
> Does this requirement also apply to `A-MoreTesting`?

`A-MoreTesting` is more like the _stretch goal_ of `A-JUnit`. It is open-ended i.e., no strict bar to meet.

**Comment by BoAi01** [comment]
Noted. I think my testing has covered more than half of the public methods. Should be good then. 

Thank you!
