### ISSUE TITLE
Are we supposed to directly push code from local repo to master branch?

### ISSUE THREAD

**Issue by alextang809** [nus-cs2103-AY2223S2/forum#17]
When I was doing ip for this week locally at my IDE, I can see editing histories in SourceTree. But I am worrying that if directly push all the changes to my master branch, is it considered a not-so-good coding behavior?

**Comment by damithc** [comment]
@alextang809 to give more context for others to respond to, 'directly push all the changes to my master branch' as opposed to what other alternatives?

**Comment by alextang809** [comment]
like should we create separate branches corresponding to level 1 to level 5? and push changes to those branches first. And push them to the master branch later.

**Comment by damithc** [comment]
> like should we create separate branches corresponding to level 1 to level 5? and push changes to those branches first. And push them to the master branch later.

@alextang809 You are welcome to use branches but that is not required at this time. We have not come to the topic of git branching yet.

**Comment by alextang809** [comment]
thx for your timely reply prof!!
