### ISSUE TITLE
Issue with continuous integration

### ISSUE THREAD

**Issue by wz2k** [nus-cs2103-AY2223S2/forum#170]
After setting up the workflow, there I have encountered an issue when building

![image](https://user-images.githubusercontent.com/87819279/218303100-b8c971a3-0f93-4848-92f9-0d4b950601d2.png)
```
Run ./gradlew check
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
Error: Process completed with exit code 1.
```

I have fixed the issue by deleting the gradle wrapper files ```gradle-wrapper.jar``` and ```gradle-wrapper.properties``` which was provided by the gradle branch that we had to merged and regenerating new versions of them.
I noticed after regenerating that the distribution url has changed from 'https\://services.gradle.org/distributions/gradle-6.2-bin.zip' to 'https\://services.gradle.org/distributions/gradle-7.5.1-bin.zip'

I am wondering if such version issues will affect grading.

**Comment by damithc** [comment]
> I am wondering if such version issues will affect grading.

@wz2k No, it will not.

**Comment by wz2k** [comment]
Thanks for the reply
