### ISSUE TITLE
Accessing .txt file in resources folder

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#172]
![image](https://user-images.githubusercontent.com/92144641/218317252-ad14ebf4-8036-476f-bc1e-469d922ac391.png)

Hi there, i've implemented the D-Trivia extension in Week 5, and i realized that it won't work when exported to a jar file because it relies on facts.txt, which contains all the facts that the extension needs to access.

I can't place facts.txt in the data folder where i keep my save, since that won't be bundled into the jar file upon building.
I can only place it in the resources folder. However, I am unable to access the file itself through the usual methods.
I have tried "resources/facts/facts.txt" too.

```

  /**
     * Loads facts from the facts/facts.txt file into the facts ArrayList.
     * @throws DukeException Thrown if the facts/facts.txt file is not found.
     */
    public void loadFacts() throws DukeException {
        File dukeFactsPath = new File("facts/facts.txt");
        ......
```

How do i access the facts.txt file in my resources folder so I can read it?

**Comment by domlimm** [comment]
Hello @Tempura-Person! I'm a senior from a previous batch, dropping by to look at the issues posted by you guys.

I did a bit of digging and this is kind of a unique situation where you can't exactly access it the way you did in the code snippet.

Perhaps, you could take a look at [this](https://howtodoinjava.com/java/io/read-file-from-resources-folder/) and a [post](https://stackoverflow.com/questions/15749192/how-do-i-load-a-file-from-resource-folder) from Stackoverflow!

Let us know how it goes!

**Comment by Guanzhou03** [comment]
Hey @Tempura-Person, I'm from your senior batch. 
It turns out that resources are not files and file operations will not work inside your JAR.
You can use getResourceAsStream or getResource to read from the fact.txt. More information can be found from this [tutorial](https://mkyong.com/java/java-read-a-file-from-resources-folder/).

**Comment by parnikkapore** [comment]
Hi, fellow senior from a previous batch here! Using getResourceAsStream or getResource seems to be the correct solution here.

**Comment by Hongyi6328** [comment]
Hi, I am also from your senior batch. When you are using `getResourceAsStream()` and `getResource()`, please make sure the class from which you call these methods is in the same module as the resource you want. Apart from that, you may also want to check if your JAR file is a fat jar file.

**Comment by Tempura-Person** [comment]
Hi all, I've tried implementing getResourceAsStream() from the tutorial sent by Guanzhou03 and I have been finding great difficulty.

below are the methods i have implemented to load an ArrayList<String> with facts from the facts.txt file.

    `public void loadFacts() throws DukeException {
        InputStream dukeFactStream = new Trivia().getFileFromResourceAsStream();
        transferFactsFromStream(dukeFactStream);
    }`
    
    `private InputStream getFileFromResourceAsStream() throws DukeException {
        Ui ui = new Ui();
        ClassLoader classLoader = getClass().getClassLoader();
        InputStream inputStream = classLoader.getResourceAsStream("/facts/facts.txt");
        if (inputStream == null) {
            throw new DukeException(ui.formatLogicError("I can't find facts.txt!"));
        } else {
            return inputStream;
        }
    }`
    
    `private void transferFactsFromStream(InputStream is) throws DukeException {
        Ui ui = new Ui();
        try {
            InputStreamReader streamReader = new InputStreamReader(is, StandardCharsets.UTF_8);
            BufferedReader factReader = new BufferedReader(streamReader);
            String factLine = factReader.readLine();
            while (!factLine.equals("")) {
                this.facts.add(factLine);
                factLine = factReader.readLine();
            }
        } catch (IOException ex) {
            throw new DukeException(ui.formatLogicError("error getting facts from facts.txt!"));
        }
    }`
    
when i call loadFacts(), it gives me a very long StackOverflow error. I am not sure why this is the case.
![image](https://user-images.githubusercontent.com/92144641/218381287-e6a60d95-2276-4676-87e9-a3c2241d8c45.png)

it points to the line in loadFacts() (line 31):
`InputStream dukeFactStream = new Trivia().getFileFromResourceAsStream();`

any idea why this is the case?

**Comment by damithc** [comment]
> when i call loadFacts(), it gives me a very long StackOverflow error.

@Tempura-Person  StackOverflow is typically caused by self-recursion or infinite loop scenarios. So, take another look at any loops or recursions you have.

**Comment by Tempura-Person** [comment]
i have considered that it may be the while loop in transferFactsFromStream(), but i removed that and the error still persists regardless.

There are no other loops regarding the Trivia function

**Comment by damithc** [comment]
@Tempura-Person consider pushing the code to a branch and sharing it here so that others can play around with the code to see what's wrong.

**Comment by Tempura-Person** [comment]
https://github.com/Tempura-Person/ip/tree/TestBranch_Trivia

here it is, any help is much appreciated! 
note, my goal for changing all this code is to make sure the fact command works in the GUI when exported to a jar file.

To test, type in
" fact "
in the Duke GUI.

**Comment by teekaytai** [comment]
Hi @Tempura-Person! I'm from your senior batch. Based on the stack trace you sent, it looks like your `Trivia` class' constructor calls the `loadFacts()` method, while the `loadFacts()` method itself also calls `new Trivia()` on this line:

```
InputStream dukeFactStream = new Trivia().getFileFromResourceAsStream();
```

Removing the `new Trivia()` bit should fix the issue. Additionally, perhaps `getFileFromResourceAsStream` should be made a static method instead since its behaviour is not specific to an instance of `Trivia` (notice how you don't need to refer to any fields or methods of `this` object). Note you would need to replace `getClass` with `Trivia.class` to be able to make the method static.

**Comment by Tempura-Person** [comment]
@teekaytai I tried out your suggestions, but now the GUI simply defaults to not being able to find the facts.txt file.
Somehow, the inputStream is null.

![image](https://user-images.githubusercontent.com/92144641/218389217-b298bf05-1040-4b88-bbf3-c4eb86eb8b17.png)

for reference, this is the filepath to facts.txt in resources.
![image](https://user-images.githubusercontent.com/92144641/218389273-7afd773b-4ed7-48c6-b898-45caaedd4763.png)

**Comment by teekaytai** [comment]
@Tempura-Person
After some tinkering, it seems like the issue has to do with the file path. I found this [stackoverflow post](https://stackoverflow.com/a/6608848) and managed to get the code working after changing the code inside `getFileFromResourceAsStream` to either

```java
ClassLoader classLoader = Trivia.class.getClassLoader();
InputStream inputStream = classLoader.getResourceAsStream("facts/facts.txt"); // Removed leading slash
```
OR
```java
InputStream inputStream = Trivia.class.getResourceAsStream("/facts/facts.txt"); // Keep leading slash
```
The fact command worked for me after making this change! (and also changing `!factLine.equals("")` to `factLine != null`)

Hope that solves the problem. Cheers!

**Comment by Tempura-Person** [comment]
Thanks, it started working again with your tips!
