### ISSUE TITLE
💡 Tip on dealing with inconsistency between GitHub file preview and GitHub Page 

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#177]
GitHub README file preview and GitHub Page use different Markdown processors, i.e., kramdown and GFM respectively, thus the rendering may not be the same. Take the following Markdown code for a table as an example:
```
| Action              |                        Format                        |                                        Examples |
|:--------------------|:----------------------------------------------------:|------------------------------------------------:|
| List tasks          |                         list                         |                                            list |
| Add a todo task     |                   todo [task name]                   |                                       todo task |
| Add a deadline task |       deadline [task name] /by [deadline date]       |                     deadline task /by 2023-2-14 |
| Add an event        | event [event name] /from [start date] /to [end date] | event recess week /from 2023-2-20 /to 2023-2-26 |
| Find a task         |                 find [keyword 1] ...                 |                                find recess 2022 |
| delete a task       |                    delete [index]                    |                                       delete 10 |
```
In README preview, it looks like following
| Action              |                        Format                        |                                        Examples |
|:--------------------|:----------------------------------------------------:|------------------------------------------------:|
| List tasks          |                         list                         |                                            list |
| Add a todo task     |                   todo [task name]                   |                                       todo task |
| Add a deadline task |       deadline [task name] /by [deadline date]       |                     deadline task /by 2023-2-14 |
| Add an event        | event [event name] /from [start date] /to [end date] | event recess week /from 2023-2-20 /to 2023-2-26 |
| Find a task         |                 find [keyword 1] ...                 |                                find recess 2022 |
| delete a task       |                    delete [index]                    |                                       delete 10 |

However, on GitHub Page, it renders like below
<img width="999" alt="Screenshot 2023-02-13 at 4 54 14 PM" src="https://user-images.githubusercontent.com/53465243/218413278-2008dc5f-dd91-471d-9a08-db186765732e.png">

The solution is to change the Markdown processor for GitHub Page. Do these steps:
1. create a file `_config.yml` in the `docs` folder
2. write this single line and push it to the remote repo: `markdown: GFM`
3. ~~Go to `settings` again, unpublish the page, and wait for it to automatically publishes itself~~ Wait a few minutes for the website to update itself (updated 14 Feb, thanks to @eugenetangkj )
4. Access the GitHub Page and check it renders properly

Some further reading, if you are interested:
1. An example of a complete `_config.yml` file (not need in our case): [here](https://github.com/daattali/beautiful-jekyll/blob/master/_config.yml)
2. Official guide on how to change the Markdown processor: [here](https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/setting-a-markdown-processor-for-your-github-pages-site-using-jekyll)

Hope this helps those who wish to use tables in their user guide. : )

**Comment by eugenetangkj** [comment]
Hi @BoAi01, thank you for the detailed write-up above! It helped me to correctly render the table on GitHub pages. On a small note, my GitHub pages automatically refreshed itself after pushing to the remote repo so I think there is no need to unpublish the page and the changes would be automatically published. 😄

**Comment by BoAi01** [comment]
> GitHub pages automatically refreshed itself after pushing to the remote repo

I didn't notice this. Thanks for pointing out!

**Comment by damithc** [comment]
> > GitHub pages automatically refreshed itself after pushing to the remote repo
> 
> I didn't notice this. Thanks for pointing out!

@BoAi01 Perhaps you can update the original post based on this? e.g.,

>3\. ~~Go to settings again, unpublish the page, and wait for it to automatically publishes itself~~ Commit, push to the repo, and wait a few minutes for the website to get updated.

**Comment by BoAi01** [comment]
@damithc I have updated the original post. Thanks for the suggestion!

**Comment by BoAi01** [comment]
Closing this issue, since IP has been submitted.
