### ISSUE TITLE
Gradle sync failed: zip END header not found

### ISSUE THREAD

**Issue by daytona65** [nus-cs2103-AY2223S2/forum#178]
My last commit was working perfectly, but when I reopened it today, I was met with this error emssage:

![image](https://user-images.githubusercontent.com/74140641/218437177-784b4537-dac6-41cb-9266-2633c8cbe7f3.png)

However, when I got my friend to clone from my repo, my code works fine.

I have tried:
- deleting my gradle files
- invalidating cache
- deleting idea folder
- deleting .gradle folder
- reinstalling Intellij

and whatever I could find online on this issue.

As far as I know, I did not do anything to modify my code after making that last commit and it even works on my friend's computer. So I really have no idea why it cannot run on mine. Any help is appreciated, thanks!

Here is the link to my repo if you'd like to try it out:
https://github.com/daytona65/ip

**Comment by hingen** [comment]
If the code works when your friend clones from your repo, how about pushing all your local changes to your remote repo, deleting the local repo, and clone your remote repo to a different local directory?

**Comment by daytona65** [comment]
Alright just an update:

**Comment by daytona65** [comment]
Alright just an update:

Tested this error by cloning the original Duke repo then immediately merging the add-gradle-support branch and the error came up immediately.

In the end this solution from stackoverflow solved it:

![image](https://user-images.githubusercontent.com/74140641/218633156-3ecae199-8bf4-4360-833d-e680d22d7add.png)

An additional error came up: [Error:Unknown host services.gradle.org. You may need to adjust the proxy settings in Gradle]

Fixed it by going to File > Settings > Appearance and Behaviour > System & Settings > HTPP Proxy and unchecking No Proxy, and checking Auto Proxy

**Comment by damithc** [comment]
Thanks for sharing the solution @daytona65
