### ISSUE TITLE
jar file runs on Windows but not Linux

### ISSUE THREAD

**Issue by 0x787af25e** [nus-cs2103-AY2223S2/forum#179]
I have created the final jar file, and on the second smoke test involving asking team members running other operating systems to run my jar file, an unexpected error has occurred. 

![image](https://user-images.githubusercontent.com/74492257/218466049-1370d467-09d8-43cb-af4d-97068f81a5b4.png)

The host operating system is Ubuntu 22.04, and it is able to run other iP jar files.

**Comment by hingen** [comment]
Interesting, I'm running Linux on bare metal and have not gotten this issue. Base on the issue, I think a possible cause is that you're using a wayland window system while JavaFX is looking for an x11 window system. Perhaps try switching to x11 by following this [guide](https://beebom.com/how-switch-between-wayland-xorg-ubuntu/)?

If it doesn't work, may I know more info about your setup? Are you running Ubuntu within a virtual machine or on bare metal? And just to be sure, are you running Ubuntu with a desktop environment or just on terminal?

**Comment by VietAnh1010** [comment]
I guess that you are running your program in WSL.

To solve this:
- Make sure that your WSL is WSL 2. GUI apps **cannot** run in WSL 1.
- Check whether gtk is running using version 3 or not by adding `-Djdk.gtk.verbose=true` to the JVM arguments.
- If your WSL does not have gtk, or gtk is running with version 3, you need to install gtk version 2. It seems like JavaFX 11 does not work with gtk version 3.
- Run your app using gtk version 2 by adding `-Djdk.gtk.version=2`.

You can read this [thread](https://github.com/bisq-network/bisq/issues/2279) for more information about this error.

**Comment by hingen** [comment]
Just tested on an Ubuntu 22.04 virtual machine. Was able to recreate the issue when running using wayland. The issue does not occur after switching to xorg.

![image](https://user-images.githubusercontent.com/31367001/218480285-c8914e13-701b-4ee9-99d4-c65cd2a660c3.png)

From what I gather, there isn't much you can do with regards to your code or build settings. The issue has to be solved by the user.
