### ISSUE TITLE
Running the runtest.bat file

### ISSUE THREAD

**Issue by kayyenl** [nus-cs2103-AY2223S2/forum#18]
Hi everyone.

I have a small problem at stage A-TextUiTesting. Specifically, I'm not too sure how to run the runtime.bat file, since there is no option to run it on the IDE. Is this file supposed to be run on the CLI by some command? Do let me know if I am misunderstanding the task or something. Thanks so much!

**Comment by arkarsg** [comment]
For Shell scripts `.sh` files, you can try `chmod +x sample.sh` followed by `./sample.sh`

.bat should be similar too

**Comment by Junyi00** [comment]
If you're using IntelliJ, you can start a terminal instance (there's a terminal tab at the bottom on the default layout). From there, navigate to `text-ui-test` folder, and just run batch files like `runtest.bat`

**Comment by kayyenl** [comment]
Alright, it seems like I went with @Junyi00 's one and it worked. Thanks so much everyone!
