### ISSUE TITLE
[ip] Put past commits into a branch

### ISSUE THREAD

**Issue by fahim-tazz** [nus-cs2103-AY2223S2/forum#181]
I have several commits in my master branch that were supposed to go into their separate branches. 

How can I put those past commits in separate branches according to the iP instructions (without undoing all my subsequent work)?

PS. I am using Sourcetree.

**Comment by fahim-tazz** [comment]
Found a duplicate issue [here.](https://github.com/nus-cs2103-AY2223S2/forum/issues/167)

**Comment by EvitanRelta** [comment]
## Separating commits into different branches

If you're asking how to separate commits from the master branch, into their separate branches, u can use `git cherry-pick`. Specifically:

- From ur Git-graph / SourceTree, and figure out which commit do u wanna separate them at.
  As in, which commit do u want to be the root/base where the branches start branching-off from.

- Checkout to that commit via: `git checkout [ROOT_COMMIT]` or via SourceTree

- Create one of the branches _(lets call it `BRANCH-A`)_ at that commit: `git checkout -b BRANCH_A`

- From ur Git-graph / SourceTree, figure out which commits should belong to `BRANCH-A`,  
  then, while on `BRANCH-A` cherry-pick every one of those commits off the `master` branch:   
  `git cherry-pick [COMMIT_HASH]` or via SourceTree (idk how to use SourceTree, but i think u can right-click > `cherry-pick commit` or something similar)
  
- Congrats! You've just separated `BRANCH-A` 's commits from the `master` branch

- Do the same for the other branches.

<br>

PS: Separating changes in a commit is much harder tho. lmk if u're trying to separate changes in a commit

<hr>

<br>

But based on ur Git-graph seems like u managed to separate them already.   
Nice

![image](https://user-images.githubusercontent.com/35413456/218705962-1d54da6b-5a96-4607-965f-e0ad0879137b.png)
