### ISSUE TITLE
Default tasks with .jar file

### ISSUE THREAD

**Issue by ajjajjajjajj** [nus-cs2103-AY2223S2/forum#182]
For the final submission, we're required to create a .jar file using Gradle, and submit just the .jar.

While I was doing this, I found that my default tasks will not be carried over. This is because my `data/` folder containing the text file for storage is located in the project's root directory, and is independent of the Java files. When I add new tasks in the standalone .jar application, a new data folder is created wherever the .jar file is.

I've tried moving the `data/` folder into `src/main/`, but when the .jar is built, the storage text file is empty, and is separate from the .jar file anyway.

The only solution I can come up with to this is to write a separate class to create default tasks when the .jar is launched. But this will result in the default tasks to be loaded in each time, and writing a new class to circumvent the text file storage method doesn't seem appropriate. 

Does anyone have any alternative suggestions for this? Or should I just not bother having default tasks for the final submission?

Thanks!

**Comment by dillongoh** [comment]
What is the behaviour of your code when a save file doesn’t exist? Perhaps you can add your template tasks during the creation of a new save file.

**Comment by ajjajjajjajj** [comment]
> What is the behaviour of your code when a save file doesn’t exist? Perhaps you can add your template tasks during the creation of a new save file.

Currently it just creates a folder with an empty text file. This sounds like a sensible solution though. Thank you!

**Comment by damithc** [comment]
@ajjajjajjajj If you wish to bundle a copy of the initial tasks inside the JAR file, #172 may be relevant. You still need to copy it over to the data folder outside of the JAR file upon first use.
