### ISSUE TITLE
Dynamic GUI - How to prevent longer response messages from being cut off? 

### ISSUE THREAD

**Issue by jytheawesome** [nus-cs2103-AY2223S2/forum#184]
Is there a way to configure the layout settings on Scene Builder such that longer response messages by the bot are not cut off, either via an ellipsis (...) or completely discarded? An example is shown in the screenshot below. 

<img width="400" alt="Screenshot 2023-02-14 at 11 28 09 AM" src="https://user-images.githubusercontent.com/95480800/218632031-212949e1-c9d5-4cd3-b08c-b13f771ce6d9.png">

**Comment by francisyzy** [comment]
I believe u need to add `minHeight="-Infinity"` to your label tag in your `DialogBox.fxml`

Something like this. 

https://github.com/francisyzy/ip/blame/a42cfc1b490ed9dacc07ef92d20e1ab4f93c08aa/src/main/resources/view/DialogBox.fxml

**Comment by jytheawesome** [comment]
> I believe u need to add `minHeight="-Infinity"` to your label tag in your `DialogBox.fxml`
> 
> Something like this.
> 
> https://github.com/francisyzy/ip/blame/a42cfc1b490ed9dacc07ef92d20e1ab4f93c08aa/src/main/resources/view/DialogBox.fxml

This is exactly what i am looking for. Thank you very much!

**Comment by EvitanRelta** [comment]
@jayhee3 rmb to close the issue if it's resolved :^)
