### ISSUE TITLE
Are we allowed to revert the repo to an older commit as a basis for our tp?

### ISSUE THREAD

**Issue by Nafeij** [nus-cs2103-AY2223S2/forum#187]
For direction 2 (Morphing)

**Comment by damithc** [comment]
@Nafeij Reverting to an older commit can move the project away from the intended brownfield nature of the project.
Therefore, you have to start with the current code and morph incrementally in reasonably-sized steps i.e., you are not allowed to revert to a previous commit.

**Comment by Nafeij** [comment]
Thanks Prof!

**Comment by Hikoya** [comment]
Hello @Nafeij  , I'm a senior from a previous batch, is there any updates to this issue? Please remember to close the issue if your question has been resolved by prof.
