### ISSUE TITLE
JAR file is corrupted and cannot be opened

### ISSUE THREAD

**Issue by Nicklelodeon** [nus-cs2103-AY2223S2/forum#188]
Hi, I'm using an M1 Mac and I'm trying to run the smoke tests on my JAR file. I've tried sending my JAR file through telegram, but when I download the JAR file and double click it to run it, it tells me that the file is damaged and can't be opened. 
However, I can run the downloaded file on terminal through the command java -jar duke.java. Is this supposed to be the default way to run JAR files (i.e through terminal), or should I be able to run the JAR file by double clicking it? 
The duke.jar file in my build/libs folder (which I get directly from gradlew shadowJar) is able to run when double clicked.

Appreciate any advice given!

**Comment by damithc** [comment]
> However, I can run the downloaded file on terminal through the command java -jar duke.java. Is this supposed to be the default way to run JAR files (i.e through terminal), or should I be able to run the JAR file by double clicking it?

@Nicklelodeon Normally, either should work, although the CLI method of running is enough for this module. 



>I've tried sending my JAR file through telegram, but when I download the JAR file and double click it to run it, it tells me that the file is damaged and can't be opened.
However, I can run the downloaded file on terminal through the command java -jar duke.java.

So, sending through Telegram corrupts the JAR? Perhaps you can upload the original JAR file here so that others can try it too?

**Comment by Nicklelodeon** [comment]
Ok sure, thank you prof! Attached below is my JAR file in a zip folder.  
[duke.jar.zip](https://github.com/nus-cs2103-AY2223S2/forum/files/10740296/duke.jar.zip)

**Comment by Nicklelodeon** [comment]
I tried downloading the file I uploaded here and it works. Thank you!

**Comment by francisyzy** [comment]
I face the same issue and I think its a Mac security issue. Downloading a file from a 'reputable' source such as GitHub will let gatekeeper prompt you and open it whereas a file with no source is more suspicious.
