### ISSUE TITLE
GUI Text issue gibberish

### ISSUE THREAD

**Issue by ChangGittyHub** [nus-cs2103-AY2223S2/forum#189]
Hi!! I need help. This is my GUI does anyone know how to fix this text issue? my java version is java 11 and my addressbook.jar works when I open it.I can read the words but my GUI is not readable.Apprecaite any help I can get!

<img width="474" alt="Screen Shot 2023-02-15 at 7 48 58 PM" src="https://user-images.githubusercontent.com/82028822/219019525-81357f50-3198-42dc-a432-58253c702210.png">

**Comment by Junyi00** [comment]
There are similar closed issues, these could be helpful
#68, #78

**Comment by damithc** [comment]
@ChangGittyHub are you using the `java -jar` command to run the jar file? If not, try that and see if that makes a difference. Also, post here the output for `java -version` command you get if you run it in the same terminal you ran `java -jar` command.

**Comment by francisyzy** [comment]
#149 is similar but closed his issue. Not sure what steps he took to solve his issue (if any). You can try attach your duke here as an zip for other Mac users to try it out.

**Comment by ChangGittyHub** [comment]
Thank you for the help! my com did not support the given font so I changed it to a different font instead thank you!
