### ISSUE TITLE
Help with "Permission denied (publickey). fatal: Could not read from remote repository."

### ISSUE THREAD

**Issue by alextang809** [nus-cs2103-AY2223S2/forum#19]
I had everything working with the Sourcetree app and git remote. But when I try to push my local changes, it fails and then gives the following prompt:
<img width="586" alt="Screenshot 2023-01-18 at 11 06 05 PM" src="https://user-images.githubusercontent.com/62707493/213207446-f9a0af1d-4155-4bc8-aeb2-9b51aa86aa11.png">

I am wondering if it is caused by my account settings in Sourcetree, as there is a warning regarding the account settings.
<img width="877" alt="Screenshot 2023-01-18 at 11 06 24 PM" src="https://user-images.githubusercontent.com/62707493/213207739-d0c7402a-f66d-4d51-8c6a-22a164205ef4.png">

And then I tried to address this issue by generating a ssh key. However it gives me another error.
<img width="465" alt="Screenshot 2023-01-18 at 11 09 14 PM" src="https://user-images.githubusercontent.com/62707493/213208056-dc698bf0-a4ef-4168-869b-f9875645fba8.png">
<img width="467" alt="Screenshot 2023-01-18 at 11 09 22 PM" src="https://user-images.githubusercontent.com/62707493/213208066-a025f7a5-9703-4809-909a-d89dece177a6.png">
I feel this issue is a bit beyond my scope at this moment because after checking the problem online, some article indicates that the problem is related to the OS.

Below is a answer from:
https://community.atlassian.com/t5/Bitbucket-questions/Help-with-quot-Permission-denied-publickey-fatal-Could-not-read/qaq-p/786747

_"Sierra or High Sierra? This is a remarkably common problem that users of those two specific revisions of macOS have, due to changes in the OS's handling of SSH identities. I suspect that most of the "related content" linked here is this exact issue.

Go to the Terminal and run `ssh-add -l` - your key should be listed there. If it isn't, run `ssh-add /path/to/key` (using the actual path to the private key, of course) and try again."_

**Comment by Beebeeoii** [comment]
just sanity check, did you add the ssh key to your github account? could you try executing `ssh -T git@github.com` in terminal, you should get a response similar to:
```
Hi Beebeeoii! You've successfully authenticated, but GitHub does not provide shell access.
```

**Comment by alextang809** [comment]
<img width="391" alt="Screenshot 2023-01-18 at 11 45 55 PM" src="https://user-images.githubusercontent.com/62707493/213218746-06449230-add2-4863-ab36-bea13e389063.png">
the same issue appeared. Where should I get the public key from? As I cannot save my SSH in account setting from Sourcetree and the prompt is couldn't connect to github with my cresidentials. I may have encountered more than one issue, I guess

**Comment by Beebeeoii** [comment]
by default the public and private keys should be stored in `~/.ssh`. from your screenshot above, you should have the files `alextang809-GitHub.pub` and `alextang809-GitHub` in the directory `~/.ssh`.

could you try logging into github, navigate to Settings -> SSH and GPG Keys. If you have yet to add your SSH key here, copy the contents from the `.pub` file and create a new SSH key

**Comment by alextang809** [comment]
Thanks! I am now able to push changes to git.
However, may I ask if the SSH warning in Sourcetree account setting matters?

**Comment by alextang809** [comment]
Finished!
