### ISSUE TITLE
Citation of SE EDU tutorial

### ISSUE THREAD

**Issue by potty10** [nus-cs2103-AY2223S2/forum#190]
I copied some code for my GUI from [https://se-education.org/guides/tutorials/javaFxPart4.html](https://se-education.org/guides/tutorials/javaFxPart4.html). Do I still need to cite using the format below?
```
persons = getList()
//@@author johndoe-reused
//Reused from https://stackoverflow.com/a/34646172
// with minor modifications
Collections.sort(persons, new Comparator<CustomData>() {
    @Override
    public int compare(CustomData lhs, CustomData rhs) {
        return lhs.customInt > rhs.customInt ? -1 : 0;
    }
});
//@@author
return persons;
```

**Comment by damithc** [comment]
@potty10 those resources are provide by us and are free to be reused. So, it's fine if you don't specifically cite them as reused, but you are welcome to do so.

**Comment by Hikoya** [comment]
Hi @potty10 , I am a senior from the previous batch. Please remember to close the issue if prof has answered your question.
