### ISSUE TITLE
How to update source code in releases?

### ISSUE THREAD

**Issue by joyngjr** [nus-cs2103-AY2223S2/forum#191]
Hello,

I made some changes to my code after releasing v0.2 and updated the jar file in my v0.2 release. However, I realised that the source code that is attached with it is not updated. I tried deleting the release and creating a new one, but git somehow generates my old source code. May I know what I should do?

<img width="1213" alt="image" src="https://user-images.githubusercontent.com/97519138/219217405-8741e43d-4693-4894-b6f3-e25227f5ed26.png">

**Comment by Junyi00** [comment]
On top of removing the release, you have to remove the ‘A-Release’ tag. I believe the behaviour you are seeing is due to reusing the old A-Release tag which is tied to that particular commit from when you first created it.
