### ISSUE TITLE
Hardcoded file path

### ISSUE THREAD

**Issue by jamieeeleow** [nus-cs2103-AY2223S2/forum#192]
Hello, may I know how to solve hardcoded file path. I have my jar file in an empty folder and it works other than finding the storage file for the hard disk to store the tasks.

How do I go about it and not hardcode the file path? 
Or is it normal to have this hardcoded file path issue? Because I remember from Level-7: Save in week 3 project, it did say that 'You may hard-code the file name and location e.g., ```[project_root]/data/duke.txt```'

**Comment by yyj-02** [comment]
How I will approach this is I will take in the `filepath` as an input string. And I will use `new File(filepath).getParentFile().mkdirs()` to create the directories if they don't exist. Lastly, do a check if the file exists with `new File(filepath).exists()`. And if it doesn't exist, create it with `new File(filepath).createNewFile()`. @jamieeeleow

**Comment by Junyi00** [comment]
Looking at your current implementation, it is already using relative pathing. I believe you just lack the check for file existence and consequently create the data file/folders if they are missing, which is what @yyj-02 have mentioned above.

**Comment by jamieeeleow** [comment]
@yyj-02 @Junyi00 

I managed to do it yay 😄 Thank you for your help!!
