### ISSUE TITLE
Unable to import javafx

### ISSUE THREAD

**Issue by panpannnnn** [nus-cs2103-AY2223S2/forum#193]
I have followed the javafx guide to import javafx but it still gives me the "Cannot resolve symbol javafx" error
![image](https://user-images.githubusercontent.com/85011179/219287006-bf5b052a-33ab-412b-85b2-9d5ff6b1bf62.png)

**Comment by yyj-02** [comment]
![image](https://user-images.githubusercontent.com/82926691/219287448-5c0318b8-30b4-4c6a-ab62-f4920cd36d7b.png)
Try clicking this elephant with the refresh icon 🐘🔃 or use `Ctrl+Shift+O` to load gradle change.

**Comment by clevon-w** [comment]
> ![image](https://user-images.githubusercontent.com/82926691/219287448-5c0318b8-30b4-4c6a-ab62-f4920cd36d7b.png) Try clicking this elephant with the refresh icon 🐘🔃 or use `Ctrl+Shift+O` to load gradle change.

Yep this works for me! Thanks for the help!

**Comment by Hikoya** [comment]
Hello @panpannnnn , I am a senior from the previous batch. Please remember to close the issue if the solutions posted by others has helped you, else please do update the post with additional messages encountered.
