### ISSUE TITLE
Running jar file with Java Platform SE Binary fails to create data folder 

### ISSUE THREAD

**Issue by glyfy** [nus-cs2103-AY2223S2/forum#194]
However, running it in command line with the command `java -jar your_jar_file.jar` results in data folder being created. Anyone know why this is happening?

**Comment by damithc** [comment]
@glyfy can you refine the subject and the body of this issue? It will improve the searchability of the forum. Right now you seem to split the body into subject and body.

**Comment by tituswe** [comment]
Hi, i'm also facing a similar problem... running the command in command line will execute the jar file and the application runs, however when I try to double click the application icon nothing happens.

**Comment by damithc** [comment]
@glyfy @tituswe Which OS are you using?

**Comment by tituswe** [comment]
@damithc I'm using macOS

**Comment by tituswe** [comment]
@glyfy I managed to figure out the problem, originally in my `build.gradle` file I had my shadowJar archiveBaseName the same name as my package. Not sure why it caused a problem tho... 

My original set up:

```
application {
    mainClassName = "saturday.Launcher"
}

shadowJar {
    archiveBaseName = "saturday"
    archiveClassifier = null
}
```

Fixed set up:
```
application {
    mainClassName = "saturday.Launcher"
}

shadowJar {
    archiveBaseName = "Saturday"
    archiveClassifier = null
}
```

Not sure if you have the same situation but this fix worked for me!

**Comment by glyfy** [comment]
My jar file seems to run fine on my friend's computers. This could be an issue with running the jar using Java Platform SE Binary application.

**Comment by WesleyBLDC** [comment]
In terms of storage file creation, 

if you run the jar file using terminal, it will not create the storage file as there it is locally stored on the terminal.

if you run the jar file by double-clicking, if your storage code is working correctly then it will create a local file directory within the same folder it was ran in.

So I recommend testing both ways.

For error handling, run launcher it on intellij and see if the terminal gives any errors.

**Comment by fahim-tazz** [comment]
@WesleyBLDC For me running the jar file via terminal creates the data file perfectly. But running it by double-clicking doesn't (the opposite of what you said). Any ideas how to fix this?
![SCR-20230220-nby](https://user-images.githubusercontent.com/86123134/220057154-8152c30c-1724-47b4-8b1f-a85a0f4de9d0.png)
