### ISSUE TITLE
iP deadline

### ISSUE THREAD

**Issue by clevon-w** [nus-cs2103-AY2223S2/forum#199]
![image](https://user-images.githubusercontent.com/88370247/219552903-c1cc00a9-cb21-4037-a980-6f7f26c9e22c.png)
This is a pretty dumb question but what does this mean? So when is the deadline of the iP and is there a hard deadline for it? If there is a hard deadline, when is it?

**Comment by damithc** [comment]
@clevon-w Hard deadline:
![image](https://user-images.githubusercontent.com/1673303/219554628-c765d09e-e71d-4308-8a1a-2123aac8b47d.png)

**Comment by clevon-w** [comment]
thanks prof
