### ISSUE TITLE
A class implementing an interface results in an is-a relationship, just like in class inheritance

### ISSUE THREAD

**Issue by shirsho-12** [nus-cs2103-AY2223S2/forum#2]
I am confused about the statement here. While both are instances of is-a relationships, are they both really similar?

In class inheritance, a subclass inherits properties and methods from its parent class, and it creates an "is-a" relationship between the subclass and the parent class. This means that an object of the subclass is considered to be an object of the parent class as well.

But when a class implements an interface, it is not inheriting properties and methods, instead, it is promising to provide an implementation for all the methods defined in the interface. The class is not inheriting any properties or methods from the interface, but it is providing an implementation for them. This creates an "is-a" relationship between the class and the interface, which means that the class is considered to be an implementation of the interface.

In a sense, class inheritance is a standard is-a relationship, but interfaces are more of a "can-do" relationship. 

Is my understanding here correct?

**Comment by BoAi01** [comment]
I think so. The "is-a" relationship in the interface case is more loosely defined than that for class inheritance. But in both cases, inheritance implies that the class has functionalities that the parent class/interface prescribes.

**Comment by FredericChow00** [comment]
Hmmm I think what u explained about the relationship between interfaces and classes is correct but the "Is-A" relationship is just a standard way of describing OOP concepts between child and parent classes/interfaces. So instead of "can-do" you can just view it as "is-a" because i dont think there's an official "can-do" terminology.

**Comment by hingen** [comment]
As others have pointed out, this is how it has been defined in OOP. However, perhaps you can look at it in another way. Think of "is-a" as "can be treated as".

So let's say we have a class `Engineer` and an interface `Person` and `Engineer` implements `Person`. Then we can thus treat `Engineer` as a `Person` meaning anything we can do on a `Person` object (the methods and properties we expect to exist) can be done on an `Engineer` object as well.

**Comment by damithc** [comment]
@shirsho-12 Is the issue resolved? If so, you can close this issue. If no, post more details so that others can follow up.

**Comment by shirsho-12** [comment]
> @shirsho-12 Is the issue resolved? If so, you can close this issue. If no, post more details so that others can follow up.

Alright prof, apologies for not closing sooner.
