### ISSUE TITLE
Deadline for IP

### ISSUE THREAD

**Issue by homuntan02** [nus-cs2103-AY2223S2/forum#200]
Hi, the website says that the deadline for the ip is today (17 Feb 2023) however the email states that we will automatically get a 3 day extension if not submitted by then. However, in issue#199, Prof mentioned that the hard deadline is today. Can I confirm that this extension wont penalise our grades as mentioned in the email?

**Comment by homuntan02** [comment]
![image](https://user-images.githubusercontent.com/64577613/219559657-c869e5a5-af60-4119-81f1-53bc29e67b25.png)

**Comment by damithc** [comment]
@homuntan02 The said deadline extension is an extension for the hard deadline. Yes, there will be no penalty for the deadline extension.

**Comment by homuntan02** [comment]
thank you prof @damithc!
