### ISSUE TITLE
How to compile in a less recent Java Runtime

### ISSUE THREAD

**Issue by zm-l** [nus-cs2103-AY2223S2/forum#201]
My project structure was at SDK 11 and my program could launch. However I try run in my Ubuntu which only has Java 11, the following error occurs:

```
Error: LinkageError occurred while loading main class duke.Launcher
        java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version 61.0), this version of the Java Runtime only recognizes class file versions up to 55.0
```
Running in my Powershell works as its java version is 17
May I know how to compile in a less recent Java Runtime?

**Comment by francisyzy** [comment]
Looking @ your [build.gradle](https://github.com/zm-l/ip/blob/master/build.gradle), I think there is a mismatch between the JavaFX version. Not sure if that is causing your compile problem. See also: #198

Just saw your update. Can you try compiling in your Ubuntu? It should work if its compiled and ran on the same machine. I think your other machine's Java is too recent. Need to switch back to an older version of SDK. If it is a unix based system, can use this utility to manage your java versions: http://sdkman.io

**Comment by zm-l** [comment]
@francisyzy Thanks for the suggestion. I have changed all JavaFX version including those in `build.gradle` and all the FXML files to 11.

The ubuntu I used to run is just a WSL but with different java version than my main machine. The confusing part is I have the project SDK at version 11 and the program runs fine, but ubuntu recognize the class file version as 61 which is at Java 17. Hence I suppose that's why my main machine runs fine.

I have also checked the Gradle JVM which is set at SDK 11.

Not too sure which mistakes causes it to compiles to a higher class file version.

**Comment by francisyzy** [comment]
I think it might be a mismatch in java version at the system level? Whats the output from `java --version` when running it in terminal?

**Comment by zm-l** [comment]
Powershell is 17, Ubuntu is 11

**Comment by damithc** [comment]
@zm-l in your original post you mentioned the following:

>Previously, I forgot to change the project SDK to java 11 (It was at java 13).

Perhaps there are leftover `.class` files that were compiled by Java 13? 

Try `./gradlew clean run`

**Comment by zm-l** [comment]
@damithc Hi prof, I tried `./gradlew clean` before running `./gradlew clean shadowJar`. But when running `java -jar duke.jar`, the class file version is still incorrect.

**Comment by damithc** [comment]
> @damithc Hi prof, I tried `./gradlew clean` before running `./gradlew clean shadowJar`. But when running `java -jar duke.jar`, the class file version is still incorrect.

@zm-l ensure you are not using an outdated jar file (check the timestamp). Also consider removing Java 13 altogether from the computer.

**Comment by zm-l** [comment]
Uninstalling later version of Java works. Thanks!
