### ISSUE TITLE
Published UG and Ui.png tag in ip dashboard not updated

### ISSUE THREAD

**Issue by shenchenzizoe** [nus-cs2103-AY2223S2/forum#206]
I have pushed my UG days ago, but the "Published UG" tag in admin task did not turn green. The A-UserGuide one is updated though. I also posted my Ui.png today before the update time, it is not updated either. 
Is there a difference between A-UserGuide and Published UG? Should I modify anything?

Here is link to my ip repository [branch](https://github.com/shenchenzizoe/ip)

Here's what's showing on my ip progress bar:
<img width="593" alt="image" src="https://user-images.githubusercontent.com/97273558/219697112-60d18320-2159-4727-aa88-c8fe0ac63848.png">

**Comment by damithc** [comment]
@shenchenzizoe if you did it correctly, the following two URLs should work
UG https://shenchenzizoe.github.io/ip/
UI.png https://shenchenzizoe.github.io/ip/Ui.png

The second one won't work if the first one isn't working

**Comment by IsabelChong** [comment]
Hi! In regards to the Published-UG, I believe it meant the enabling of github pages to the correct source. I tried accessing your [page](http://shenchenzizoe.github.io/ip) and it does not exist.

<img width="617" alt="image" src="https://user-images.githubusercontent.com/71481877/219699039-13fedf3b-c18b-4837-8922-4de6c59c8f18.png">


Have you done the following steps under [A-UserGuide](https://nus-cs2103-ay2223s2.github.io/website/schedule/week6/project.html)?

**Comment by CarrieLi1015** [comment]
Hello prof, I have faced similar issue here. Followed the steps given but the github page is not live.

<img width="730" alt="Screenshot 2023-02-18 at 12 06 25 AM" src="https://user-images.githubusercontent.com/97392685/219705022-58bf4047-4586-4b28-9e40-cbd9e7559fc8.png">

**Comment by damithc** [comment]
@CarrieLi1015 try changing the setting to something else, save, change again to the correct setting, and save again.
You can also try adding a Jekyll theme (link shown in your screenshot) to see if that triggers the site publishing.

**Comment by CarrieLi1015** [comment]
> 

Thank you prof! The problem is solved!

**Comment by francisyzy** [comment]
Remember to close the issue!

**Comment by shenchenzizoe** [comment]
Thanks Prof! mine is also solved!
