### ISSUE TITLE
Update iP after 23:59 of 17/2/2023

### ISSUE THREAD

**Issue by jiasheng59** [nus-cs2103-AY2223S2/forum#207]
Hi, I would like to further improve my GUI and I have already published a release v0.2 (because I don't want to be penalized for submitting beyond hard deadline).

However, it seems like we still have the 3-day of deadline extension for iP. I'm not sure whether we are allowed to make any changes to my existing code right now. Will be any form of penalty (whether it is iP's mark or any bonus component of this module if there's any) for those who still modify their code within these 3-day extension? 

Thanks in advance!

**Comment by damithc** [comment]
@jiasheng59 Yes, you may do another release (or update the current release) by Thursday of week 7 if you need to (e.g., to fix a bug you found after the previous release) -- there is no need to get our permission to do so, and there is no penalty for doing so either.

**Comment by jiasheng59** [comment]
Thanks!

*I will leave this issue open for 1-day so that everyone can see.*
