### ISSUE TITLE
Camelcase or all-caps for constants within methods?

### ISSUE THREAD

**Issue by niekis** [nus-cs2103-AY2223S2/forum#210]
![image](https://user-images.githubusercontent.com/96820906/219944439-4daaeff8-4529-4b12-8c64-c6bdad373653.png)

This was how I initially saved the string constant. However checkstyle flags this since it is not a static constant.

![6ec8215f-d69a-483c-979d-07606b1e4049](https://user-images.githubusercontent.com/96820906/219944529-c93f77a0-71a5-4781-a370-43711d3d43ad.png)

I personally feel that this constant should be constained within the scope of the method. So perhaps leaving it in camelcase could be the correct option. Am I right? 
I'm also thinking it might be better to override the checkstyle instead.

**Comment by damithc** [comment]
@niekis You may change Checkstyle rules, but the code is still expected to comply with the coding standard.

**Comment by parth-io** [comment]
I'm a senior dropping in from the previous batch. As this is an advanced use-case not covered by the coding standard, I took this from the Google Java Style Guide linked to in the CS2103/T website.

>5.2.7 Local variable names
Local variable names are written in [lowerCamelCase](https://google.github.io/styleguide/javaguide.html#s5.3-camel-case).
Even when final and immutable, local variables are not considered to be constants, and should not be styled as constants.

So if you consider the minimal scope to be the method itself, you can follow the guide.
