### ISSUE TITLE
Product User Guide and Screenshot not Displayed

### ISSUE THREAD

**Issue by shittake** [nus-cs2103-AY2223S2/forum#211]
Hi everyone,

As per the screenshot below, I believe I had followed all the instructions required for submission. However, it has been more than 24 hours and I still do not see my Ui.png and screenshot displayed. Did anyone face a similar issue and has it resolved? Thank you!

![image](https://user-images.githubusercontent.com/40803540/219947248-e75ce95a-3f7e-4f1b-8ed6-04779dda8a69.png)

**Comment by IsabelChong** [comment]
Hi! Here's a relevant issue #206 which you can look into.

**Comment by shittake** [comment]
@IsabelChong thank you, that worked!
