### ISSUE TITLE
Releasing a new JAR file after v0.2

### ISSUE THREAD

**Issue by IsabelChong** [nus-cs2103-AY2223S2/forum#212]
I want to release a new JAR file. Here is a snippet of the instruction in the email sent:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/71481877/219948676-1c30f850-e5f4-44f5-8434-444626c3cfda.png">

Since we already have a `v0.2` tagged with `A-Release`, do we release our new file as `v0.3`?

Also, there seems to be a need to tag this release. Can I just tag it as `v0.3` as well?

**Comment by damithc** [comment]
> Since we already have a `v0.2` tagged with `A-Release`, do we release our new file as `v0.3`?
> 
> Also, there seems to be a need to tag this release. Can I just tag it as `v0.3` as well?

@IsabelChong You may use any tag or version number. We simply take the latest release as your final submission.

**Comment by IsabelChong** [comment]
Alright thanks prof!
