### ISSUE TITLE
Grading Script not detecting my tags

### ISSUE THREAD

**Issue by daytona65** [nus-cs2103-AY2223S2/forum#213]
I've already pushed A-UserGuide tags, user guide is up on my site, and Ui.png is visible in the showcase site since yesterday. 
In addition I have other optional tags like A-BetterGui, A-Personality and A-MoreErrorHandling. 
I have these tags on my other branches, not my master branch.
Any clue why the dashboard doesn't seem to update? Thanks!

![image](https://user-images.githubusercontent.com/74140641/220002204-eae3782e-7ade-4701-a091-d59a1b988cd5.png)

**Comment by damithc** [comment]
@daytona65 Seems they are all green after the latest update to the dashboard?
