### ISSUE TITLE
Linkage Error

### ISSUE THREAD

**Issue by junlee1991** [nus-cs2103-AY2223S2/forum#214]
<img width="454" alt="image" src="https://user-images.githubusercontent.com/77482097/220020968-57453645-3eed-4ccb-809c-f9dfeba414bb.png">

Error: LinkageError occurred while loading main class duke.Launcher java.lang.UnsupportedClassVersionError: duke/Launcher has been compiled by a more recent version of the Java Runtime (class file version 56.0), this version of the Java Runtime only recognizes class file versions up to 55.0 

My jar works on my laptop but i received an email that my smoke test fails. Any idea how to fix?

**Comment by jiasheng59** [comment]
I tried to launch your application (downloaded from your release v0.2), I got the same error you mentioned above.
<img width="960" alt="error" src="https://user-images.githubusercontent.com/96868229/220029908-4b7fd063-90b6-48a0-a971-2e1e94cb349d.png">

**Comment by hingen** [comment]
The error message seems to imply that your jar file was not compiled using Java 11. Could you run a `java --version` on your laptop to check if you have installed Java 11 and not some other version? If you're using IntelliJ, perhaps also check that your project is using the correct jdk.

**Comment by jiasheng59** [comment]
May I know if you are using Gradle to create the jar file?

**Comment by junlee1991** [comment]
Upon running `java --version`
java version "15.0.1" 2020-10-20

yes i used gradle to create the jar file. shadow clean command i believe

**Comment by francisyzy** [comment]
Similar issue: https://github.com/nus-cs2103-AY2223S2/forum/issues/216

Need to uninstall the wrong java and install the right java.

**Comment by junlee1991** [comment]
ok i've applied the necessary fix. May i know if the issue still persists?

[Here](https://github.com/junlee1991/ip/releases/tag/A-Release2) is my latest release.

**Comment by francisyzy** [comment]
![image](https://user-images.githubusercontent.com/24467184/221369333-c4c0d887-929e-4373-909f-b281e908ba08.png)
tested on a Mac and it seems to launch fine. Let me test on windows and update this comment

works fine on windows too!
![IMAGE 2023-02-26 00:53:16](https://user-images.githubusercontent.com/24467184/221369425-fd93afca-42c4-4106-8060-c2ff8ae010e8.jpg)
