### ISSUE TITLE
Error initializing QuantumRenderer: no suitable pipeline found java.lang.RuntimeException:

### ISSUE THREAD

**Issue by anchengyang** [nus-cs2103-AY2223S2/forum#215]
![image](https://user-images.githubusercontent.com/65301406/220041203-39904c6d-0455-4d9a-9794-c554c0e44edb.png)

Is anyone facing the same problem? Not quite sure what the error is.

**Comment by anchengyang** [comment]
@damithc I'm not sure if the issue for mine is resolved because when I run my application it works fine. This error was from the smoke testing bot and I don't know how to achieve this error or what is causing it.

My code can be found [here](https://github.com/anchengyang/ip)

**Comment by damithc** [comment]
@anchengyang which OS did you use to create the JAR file? Other Linux users, are you able to reproduce this error for @anchengyang's JAR file?

**Comment by anchengyang** [comment]
@damithc im using windows actually

**Comment by gohyongjing** [comment]
I'm using windows, and the jar file seems to work properly for my computer
![image](https://user-images.githubusercontent.com/39022090/220523910-0e659624-281f-48d2-8314-f83cb4f6683c.png)

**Comment by anchengyang** [comment]
@gohyongjing thanks for downloading and helping me to check!

**Comment by owen-yap** [comment]
Are you building the project from gradle in WSL2? That might be what's causing the issue because I faced the same errors but it worked fine once I switched to building the project from windows.

**Comment by damithc** [comment]
> I'm using windows, and the jar file seems to work properly for my computer

The JAR passed the smoke test on Windows and Mac. The error is specific to Linux.

**Comment by anchengyang** [comment]
> Are you building the project from gradle in WSL2? That might be what's causing the issue because I faced the same errors but it worked fine once I switched to building the project from windows.

ohh but currently i build the project on windows in intellij. According to @damithc its failing the linux one

**Comment by anchengyang** [comment]
> > I'm using windows, and the jar file seems to work properly for my computer
> 
> The JAR passed the smoke test on Windows and Mac. The error is specific to Linux.

How can I resolve this issue?

**Comment by damithc** [comment]
> How can I resolve this issue?

@anchengyang Two things that can help:
1. Find a Windows user whose JAR didn't fail the smoke test on Linux, and compare to see what you are doing differently.
2. Find a Linux user who can reproduce the error for your JAR file so that s/he can help you verify when the problem is fixed.

You can ask team members while waiting for other classmates to reply here if they fit the bill in 1 or 2.

**Comment by MrJeremyKhoo** [comment]
I have your v1.1 release (from 11 mins ago). I run Arch Linux. it is working on Arch Linux

**Comment by szejiancheng** [comment]
Encountering this problem as well! Do update when you've found the solution!

**Comment by anchengyang** [comment]
> I have your v1.1 release (from 11 mins ago). I run Arch Linux. it is working on Arch Linux

Wah thank you sir so I guess the issue is fixed now

@szejiancheng What i changed can be found [here](https://github.com/anchengyang/ip/commit/c94962c958fd671c439a8a0632e6dbcdd4d3b33a)

**Comment by szejiancheng** [comment]
woah @anchengyang just to be clear, you removed the javafx dependency in your build.gradle file and that solved the problem?

**Comment by anchengyang** [comment]
> woah @anchengyang just to be clear, you removed the javafx dependency in your build.gradle file and that solved the problem?

That and I also added the other stuff in dependencies to make sure the javafx is on version 11 and can run on linux, windows and mac. I think? Because previously the javafx {} was version 19 I think cos I followed some random tutorial online.
