### ISSUE TITLE
Question regarding "Do not merge PRs failing CI" 

### ISSUE THREAD

**Issue by lywich** [nus-cs2103-AY2223S2/forum#217]
![image](https://user-images.githubusercontent.com/89989103/220052448-0b0cce48-fb48-4871-9600-f8db6018188d.png)

Came across this under week 8 -> project -> Add the first functionality increment -> workflow. 

I would like to ask how strict should we adhere to this requirement? For context, my commit has failed the CI due to code coverage. This was largely due to changes to the codebase that included renaming and deletion of class/testcase. Otherwise, everything was fine. The DevOps guide says to take action if the code coverage drops below desired levels but it is said on the week 8 project tab that we are "required to follow" the workflow.

Is it alright to merge anyway if we have analyzed the codecov report and determined that the change in coverage was due to the deletion of unwanted classes?

**Comment by damithc** [comment]
> Is it alright to merge anyway if we have analyzed the codecov report and determined that the change in coverage was due to the deletion of unwanted classes?

@lywich Yes, CI is a safety mechanism. You may choose to override it if the situation permits.
