### ISSUE TITLE
Should README.md on the root folder of the repo be changed?

### ISSUE THREAD

**Issue by fahim-tazz** [nus-cs2103-AY2223S2/forum#218]
The `README.md` file on the root folder shows the original Duke Project Template readme. Should I change it to show my User Guide, my PR description, or leave it as is?

**Comment by damithc** [comment]
@fahim-tazz Good point. While not 'required' (for grading purposes), it's good to do so.

**Comment by fahim-tazz** [comment]
Understood Prof, thank you.
