### ISSUE TITLE
corrupted font when I run AB3 code, but no font problem with addressbook.jar

### ISSUE THREAD

**Issue by ChangGittyHub** [nus-cs2103-AY2223S2/forum#221]
I have no font issue with the addressbook.jar file that we had to test weeks before, however, I have an issue of corrupted fonts when I run the tp code that I forked and clone into my computer.
I checked if my mac has the right version using java --version and it is correct as shown below.
Not sure what is causing this issue, appreciate any help I can get! Thank you

#AB3 addressbook.jar
![IMAGE 2023-02-21 17:40:07](https://user-images.githubusercontent.com/82028822/220307474-00cc8df3-49d3-4285-8e75-e1e5c930635a.jpg)

#AB3 tp code
![IMAGE 2023-02-21 17:33:29](https://user-images.githubusercontent.com/82028822/220305833-5e8f8b26-a371-4db6-b42e-ee8d62b31cef.jpg)
![IMAGE 2023-02-21 17:36:53](https://user-images.githubusercontent.com/82028822/220306617-b9449336-4a47-4786-9ba1-9a1509129caa.jpg)

**Comment by francisyzy** [comment]
Have you tried other SDKs? Can use http://sdkman.io/ to switch SDKs easily

**Comment by afiqzu** [comment]
Hi, I had the same issue so I trawled through past semester's forums and found a fix! Just update your build.grade file and change

`
String javaFxVersion = '11'
`
to
`
String javaFxVersion = '16'
`

under dependencies.

Hope it works for you!

Reference:
https://github.com/nus-cs2103-AY2122S1/forum/issues/112

**Comment by damithc** [comment]
@ChangGittyHub to avoid using the wrong JDK by mistake, you can consider removing all other JDKs except the one recommended in https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html

When running the AB3 code, how exactly do you run it? Using Intellij?
