### ISSUE TITLE
Requesting for smoke testing on Linux!

### ISSUE THREAD

**Issue by szejiancheng** [nus-cs2103-AY2223S2/forum#222]
Requesting any kind Linux users to help smoke test [this ](https://github.com/szejiancheng/ip/releases/tag/v0.3)jar file, the usual method of opening applies using the command `java -jar duke.jar` after navigating to the directory.

This is to check if the error detailed in #215 still exists after the fixes recommended by @anchengyang

**Comment by glozxi** [comment]
It works on Ubuntu 20.04 in VirtualBox.
![2023-02-23 10_28_10-CS2106-2010-VM  Running  - Oracle VM VirtualBox](https://user-images.githubusercontent.com/82697998/220808585-bee0741d-3cd9-4d92-8204-5ddaa55dfd34.png)

**Comment by MrJeremyKhoo** [comment]
![smoke test](https://user-images.githubusercontent.com/73585045/220836410-55d5f0de-527c-478c-9429-3f6daf1ced5b.png)
runs on native Arch Linux

**Comment by szejiancheng** [comment]
Thank you all, closed
