### ISSUE TITLE
What happens after branch merge with master

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#223]
Based on the forking workflow, we do our work on a branch, push to fork and then merge with master branch on upstream. So after we do all these, do we still need to keep the branch in our local repo/origin?

**Comment by damithc** [comment]
@seadragon2000341 While it is common practice to delete a branch after merging it, we require you to keep those branches in the team repo so that our scripts can confirm that you used branches when adding changes.

**Comment by francisyzy** [comment]
I have deleted some branches in my own tP fork, should I recreate it?

**Comment by damithc** [comment]
> I have deleted some branches in my own tP fork, should I recreate it?

@francisyzy Should be fine, provided you don't delete branches used for future PRs.

**Comment by Hikoya** [comment]
Hello @seadragon2000341 , I am a senior from the previous batch. Is there any other updates to the issue? If prof has managed to answer your question, please remember to close the issue :), else do update the post if needed.
