### ISSUE TITLE
Requesting for smoke test on Linux

### ISSUE THREAD

**Issue by HmuuMyatMoe** [nus-cs2103-AY2223S2/forum#225]
Would appreciate any help from Linux users to help smoke test [this ](https://github.com/HmuuMyatMoe/ip/releases/tag/A-Release)jar file with the usual method of navigating to the directory and using the command `java -jar botanic.jar`. Thank you!

**Comment by IsabelChong** [comment]
I would also really appreciate it if someone could help me test as well! Thought it would be better to not split it into several issues.

You can download my file [here](https://github.com/IsabelChong/ip/releases/download/v0.3/berry.jar). Similarly, just navigate to the directory and run `java -jar berry.jar`.

Thank you!

**Comment by Lava-Iris** [comment]
@HmuuMyatMoe Just tested your jar file. It's working without any issues on Linux. 

P.S. Your UI is super cute!!!!

**Comment by Lava-Iris** [comment]
@IsabelChong your jar file is executing without any issues on Linux. 

P.S. How do you guys come up with such cute UIs?

**Comment by IsabelChong** [comment]
@Lava-Iris Thanks for letting me know, and I'm glad that it is running without any issues!

It's great to hear that you find the UI cute as well. I just added in two of my favourite characters~

**Comment by MrJeremyKhoo** [comment]
Both run fine on Native arch linux

**Comment by damithc** [comment]
@Lava-Iris @IsabelChong @jeremykhoo-NUS Thanks for your help 💯 
Linux users are fewer in numbers, highly in demand 😀

**Comment by HmuuMyatMoe** [comment]
@Lava-Iris @jeremykhoo-NUS Thank you for your help!
