### ISSUE TITLE
tutorial-adding-command PR not tracked?

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#226]
Hi, i've checked the tp progress boards and i noticed that the item !Tutorial has not been marked as done despite me having sent the PR to my team's repo several days ago.

![image](https://user-images.githubusercontent.com/92144641/221397821-91d02c9f-fdc4-4c16-a8cb-25599f3d347d.png)

The proof of me having done the tutorial 2 pull request is below:
https://github.com/AY2223S2-CS2103T-W13-2/tp/pull/1

Why is this the case?

**Comment by damithc** [comment]
@Tempura-Person It's likely because your PR doesn't match the following description:
![image](https://user-images.githubusercontent.com/1673303/221398393-40a72f4a-e337-43ba-8570-59240e002c71.png)

**Comment by Tempura-Person** [comment]
ok, i am creating the pull request directly from the branch now.
will it still detect it if i close the pull request immediately after?

**Comment by damithc** [comment]
> will it still detect it if i close the pull request immediately after?

@Tempura-Person Yes, IIRC. You can check again after the next dashboard update and let me know if it is still not green.

**Comment by Tempura-Person** [comment]
Hi, i checked the tp progress dashboard again and the tutorial has been counted,
but the v1.1 PRs one has still not been checked. this is confusing as i have already done several PRs and have assigned them to milestone v1.1.
i do not know where i have gone wrong.

**Comment by damithc** [comment]
> Hi, i checked the tp progress dashboard again and the tutorial has been counted,
> but the v1.1 PRs one has still not been checked. this is confusing as i have already done several PRs and have assigned them to milestone v1.1.
> i do not know where i have gone wrong.

@Tempura-Person it's due to the same problem as the tutorial PR. 
![image](https://user-images.githubusercontent.com/1673303/221455710-cf701c5f-b0d3-4c08-b956-9dfb0933dc6e.png)

**Comment by Tempura-Person** [comment]
ah, i see. i should probably start branching.
