### ISSUE TITLE
Why does option F indicate coupling between A and B?

### ISSUE THREAD

**Issue by cjyothika** [nus-cs2103-AY2223S2/forum#227]
![image](https://user-images.githubusercontent.com/59786385/221419007-cb0c560b-be4a-4ecc-8045-ddd34eecc4d0.png)

Could it be possible that option F indicates the coupling of A and B with another component instead?

![image](https://user-images.githubusercontent.com/59786385/221419168-3bae46ff-1cf5-4db5-88e1-e6910a285216.png)

I know it's written here (as shown above) but why is the last statement so?

**Comment by tituswe** [comment]
I believe that if two components share the same data format/communication protocol, this implies that they are highly likely to work together in a programme. 

I get that there is the possibility of there being rare cases where two components share the same data format but are not coupled. But I guess in your average software programme if two components have data structured in the same way it his highly likely that they share some sort of dependency.

I would say that its not **necessary** that two components with the same data format implies coupling, but I can understand the high likelihood of it.

Hope someone can clarify!!

**Comment by damithc** [comment]
Good question @cjyothika 
@tituswe is on the right track.

If A and B is supposed to follow the same data format or protocol, whenever one of them is changed, there is a good chance that the other needs changing too. That satisfies the definition of coupling.

e.g., Suppose you have a HtmlReader and a HtmlWriter class. Initially the two classes support only a subset of the HTML syntax but later you change one of the classes to support one more HTML tag. You have to at least consider the possibility that the other class needs support that tag as well.

**Comment by cjyothika** [comment]
I see. Thank you for the explanation @damithc and @tituswe!
