### ISSUE TITLE
Requesting for help for smoke testing on Linux

### ISSUE THREAD

**Issue by Bisceto** [nus-cs2103-AY2223S2/forum#228]
Sorry to create a new issue for this since the other issue regarding linux smoke testing was closed. Would greatly appreciate any users on linux to help me test my [jar](https://github.com/Bisceto/ip/releases/tag/A-Release_2) file!

Same method of running the command `java -jar duke.jar` in an empty directory.

**Comment by cheeheng** [comment]
Hi @Bisceto , I am from your senior batch. I smoke-tested your product on Linux and it almost works, except for a missing window title. The images appear to display correctly. This is a screenshot of your product tested on Ubuntu 22.10.

![Screenshot from 2023-02-27 15-07-28](https://user-images.githubusercontent.com/13196670/221497556-4254db89-9a0f-4512-8650-ea07113729b8.png)

**Comment by Bisceto** [comment]
@cheeheng Thank you for your help! I'll leave this issue up until tomorrow in case anybody wants to request for help for smoke testing as well.

**Comment by parnikkapore** [comment]
Works here too! Ubuntu 22 LTS based, X11.
![image](https://user-images.githubusercontent.com/9170353/221566199-12b74952-719e-41bb-8c05-a3bc04e93d3d.png)
