### ISSUE TITLE
Requesting for help for smoke testing on Linux

### ISSUE THREAD

**Issue by Zhongli5712** [nus-cs2103-AY2223S2/forum#229]
Can anyone smoke test my [duke.jar](https://github.com/Zhongli5712/ip/releases/tag/Linux-Compatible-codeupdated) on Linux? I really appreciate your help! Thanks in advance :satisfied:

To run the file: run with command line ```java -jar duke.jar```

**Comment by seanfirefox** [comment]
@Zhongli5712 your duke.jar works on Arch Linux, just that the `Type your command` appears as a editable text rather than a hint. Not sure if that was intended.

**Comment by Zhongli5712** [comment]
> @Zhongli5712 your duke.jar works on Arch Linux, just that the `Type your command` appears as a editable text rather than a hint. Not sure if that was intended.

Hi Sean thank you for helping me! For the "Type your command" editable, that's intended as you can type directly without having to delete it so I thought it would be useful to have something indicating where to type command. I think I will try to fade the phrase instead.

**Comment by seanfirefox** [comment]
No problem. By editable text I mean that I can delete the `Type your command` text. If you want to show something indicating where to type, maybe you can try [hints](https://stackoverflow.com/questions/34069030/how-to-add-hint-text-in-a-textfield-in-javafx) instead.

**Comment by Zhongli5712** [comment]
> No problem. By editable text I mean that I can delete the `Type your command` text. If you want to show something indicating where to type, maybe you can try [hints](https://stackoverflow.com/questions/34069030/how-to-add-hint-text-in-a-textfield-in-javafx) instead.

I will try this. Thanks for the recommendation!
