### ISSUE TITLE
Help with smoke testing on mac

### ISSUE THREAD

**Issue by RyanQiu1** [nus-cs2103-AY2223S2/forum#231]
Can anyone smoke test my [TheTaskMechanic.jar](https://github.com/RyanQiu1/ip/releases/download/A-Release/TheTaskMechanic.jar) on Mac? Thank you very much!

run with command line java -jar TheTaskMechanic.jar

**Comment by muhammadreyaaz** [comment]
<img width="409" alt="Screenshot 2023-03-01 at 7 51 19 AM" src="https://user-images.githubusercontent.com/67105732/222009483-bd77b58d-732a-489f-913a-c1f871b65f8d.png">
<img width="399" alt="Screenshot 2023-03-01 at 7 51 30 AM" src="https://user-images.githubusercontent.com/67105732/222009495-f004ea70-e304-41c6-830b-b2544dbd2de5.png">
<img width="401" alt="Screenshot 2023-03-01 at 7 51 43 AM" src="https://user-images.githubusercontent.com/67105732/222009516-cf7037ad-db6b-4bed-8270-83bf8abe1d27.png">

Everything looks alright!

**Comment by RyanQiu1** [comment]
@ARPspoofing Thank you!
