### ISSUE TITLE
Changing name of tP on tP Teams List

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#233]
Hello, i am speaking on behalf of team CS2103T-W13-2 as a member.

We have decided to change our tP name to SportSync (previously, it was Unibook)
This was because we decided that the new name better describes the functionality of the product and its value to the end user.

However, the tP name on the tP Teams List is still logged under 'Unibook'.
Is there a way to change it to SportSync? Would this cause any unforeseen problems to the logging of our code progress?

**Comment by damithc** [comment]
@Tempura-Person we'll change the product name in our records in due course. No, it will not affect the grading or progress tracking.
