### ISSUE TITLE
v1.1 milestone not detected in tP Progress 

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#234]
Hi prof,

my team W14-4 has completed all v1.1 milestones and closed all issues as well as the milestone itself but we are not sure why the tracker isnt detecting it.

Are you able to help us out on this?

**Comment by damithc** [comment]
@FredericChow00 the milestone was closed _after_ the last update to the dashboard. You can wait till the next dashboard update and let me know if it is still not green.

**Comment by Hikoya** [comment]
Hello @FredericChow00 , I am a senior from the previous batch. Is there any updates to this issue?
