### ISSUE TITLE
_config.yml file

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#235]
Can I check if it's okay to change the markdown inside the .yml file? 

<img width="397" alt="Screenshot 2023-03-02 at 12 20 46 PM" src="https://user-images.githubusercontent.com/76247607/222330378-47f7d888-9a16-4872-b900-5e002f157bcc.png">

In this case from kramdown to GFM like I did.

**Comment by damithc** [comment]
@pangrwa Yes, you may/should change those settings files as needed.

**Comment by Hikoya** [comment]
Hello @pangrwa , I am a senior from the previous batch. Is there any updates to this issue? If not, please do remember to close the issue! :)
