### ISSUE TITLE
What is the recommended way to split the work amongst our teammates?

### ISSUE THREAD

**Issue by anunayajoshi** [nus-cs2103-AY2223S2/forum#237]
Hello, 

We have been facing some struggles trying to split up the work for the team project. 
I read from one of the forums that we should split the work based on user stories and user tasks, so each person is given 1 feature to implement. 

However, we felt that that would lead to a lot of merge conflicts and issues down the road. We tried to split it so that each person is in charge of UI, Logic, Model, Storage classes, so that we do not clash too much with each other's codebase, and helps to abstract out how each class needs from each other. That came with its own issues as to implement a single feature required small changes from all teammates, and could potentially slow down progress. Additionally, doing as such meant that those in charge of the Logic and Model could not visually see the changes and test it until the UI was added for it. 

As such, I'm unsure how other teams are delegating the work such that we can collaborate together seamlessly. 

Could anyone share any advise?

**Comment by damithc** [comment]
@anunayajoshi our recommendation is to divide the tP work by feature  but someone to be put _in charge_ of each component.

See https://nus-cs2103-ay2223s2.github.io/website/admin/tp-expectations.html#individual-expectations-on-implementation

**Comment by jiasheng59** [comment]
It seems that the "expected" or "advised" way of dividing the work is dividing by features (enhancement), as such, you will work on some (if not all) components of the project for the particular enhancement you're in charge of.
