### ISSUE TITLE
iP A-Enums: Is this increment optional? 

### ISSUE THREAD

**Issue by RubyNguyen07** [nus-cs2103-AY2223S2/forum#24]
Hello, I am wondering whether not implementing A-Enums will affect grading because for now I could not see any benefits of using Java enums in my code.

**Comment by BoAi01** [comment]
I guess not, since it is indicated as "if applicable" in the instruction.

I think `enums` can be used to include all possible commands (e.g., `list`, `mark`), though the benefit is marginal for now.

**Comment by damithc** [comment]
@RubyNguyen07 it's fine to omit it as it's an optional item.

**Comment by RubyNguyen07** [comment]
@BoAi01 Yes thats what I thought too :) Thanks for your comment! 
@damithc Okay I got it, thanks!
