### ISSUE TITLE
Testing of UI for JavaFX

### ISSUE THREAD

**Issue by angjunkang** [nus-cs2103-AY2223S2/forum#240]
I have managed to done up some UI using JavaFX and it appears that codecov requires me to test those codes. I check the test files given in AB3 and it seems like they did not test much of the UI to begin with. Does anyone have any advice on how to work on this?

**Comment by damithc** [comment]
@Irminrics You can ignore the Codecov requirement for code that you decide not to have automated tests for. 
AB3 does not have automated tests for the GUI. 
Some background: [AB4](https://github.com/se-edu/addressbook-level4) has automated GUI tests (written using the TestFX library) and was used as the base repository for CS2103/T sometime back. But we found it is too much effort for students to maintain GUI tests. So we switched to using AB3 instead (one main difference between AB3 and AB4 is the automated GUI tests).

**Comment by angjunkang** [comment]
@damithc Thanks for the prompt reply prof! However, the codecov cause the CI status to fail in my PR, and according to the tp workflow given to us, we are not supposed to merge any failed CI into the master branch? Is there any workaround for this?

**Comment by damithc** [comment]
@Irminrics You can make an exception to that rule when circumstances justify it. An admin user can merge a PR even when CI is failing.

**Comment by angjunkang** [comment]
Got it! Thanks prof :)
