### ISSUE TITLE
error initializing QuantumRenderer no suitable pipeline found

### ISSUE THREAD

**Issue by JunHao247** [nus-cs2103-AY2223S2/forum#241]
Hello, below are the versions of my intellij, Java and macOS. My java files are detected for individual project, however for the tP, after forking, I am unable to run the Main class. This issue arises in the screenshot below. Any help?

IntelliJ version: 2022.3.2
Java version: 
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.62+17-CA (build 11.0.18+10-LTS, mixed mode)
macOS: Ventura 13.1 
Chip: Apple M1.

![photo_2023-03-07 00 18 31](https://user-images.githubusercontent.com/122423527/223168777-3bec4cd2-53db-45fa-ae5a-ec7460f1e09a.jpeg)

**Comment by damithc** [comment]
@JunHao247 it might help if you post a screenshot of your project settings in Intellij. 
Also, what happens when you run the following commands outside of intellij, in a terminal, at the project root folder?
```
java -version
./gradlew clean run
```

**Comment by damithc** [comment]
@JunHao247 BTW, you might want to update the issue title to match the actual problem. The error seems to be `error initializing QuantumRenderer no suitable pipeline found` (as per your screenshot)

**Comment by JunHao247** [comment]
@damithc Thank you for the replies, have also updated the title to match the problem. After updating my laptop, the issue has been solved, with regards to running the command at the project root folder, the following shows up:
openjdk 11.0.18 2023-01-17 LTS
OpenJDK Runtime Environment Zulu11.62+17-CA (build 11.0.18+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.62+17-CA (build 11.0.18+10-LTS, mixed mode)

I will now close the issue, thank you so much!
