### ISSUE TITLE
iP Peer Evaluation

### ISSUE THREAD

**Issue by jamieeeleow** [nus-cs2103-AY2223S2/forum#243]
Hello, may I know what is the procedure if the person I am supposed to peer review has not released their JAR file yet? Thank you.

**Comment by damithc** [comment]
@jamieeeleow here is the answer:
![image](https://user-images.githubusercontent.com/1673303/223467875-943f3f64-cefd-4854-a5e6-7307703bd7fe.png)

**Comment by jamieeeleow** [comment]
Okay! Thank you
