### ISSUE TITLE
CS2103 website redirect broke

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#248]
https://www.comp.nus.edu.sg/~cs2103

![image](https://user-images.githubusercontent.com/24467184/224309047-c256f397-3eb6-4e2d-8952-f52d8bf01225.jpeg)

**Comment by slackernoob** [comment]
Redirect not working for me too, but you can still access the website through this [link](https://nus-cs2103-ay2223s2.github.io/website/index.html)!

**Comment by damithc** [comment]
Seems to be an SoC-wide problem, and none of the `/~abc` sites are working. I'll inform SoC IT.

**Comment by damithc** [comment]
They've fixed the issue. Closing ...
