### ISSUE TITLE
A-TextUiTesting test failing

### ISSUE THREAD

**Issue by Lava-Iris** [nus-cs2103-AY2223S2/forum#25]
I'm trying to do the A-TextUiTesting task and my test result fails every time. I'm working on Ubuntu (running runtest.sh). I tried to copy the actual.txt to the expected.txt and it still gives the following error:

```bash
dos2unix: converting file ACTUAL.TXT to Unix format...
dos2unix: converting file EXPECTED-UNIX.TXT to Unix format...
1,2c1,2
< Welcome to Lavender Network! 
< I'm Iris, your favourite teenage chatbot. 
---
> Welcome to Lavender Network!
> I'm Iris, your favourite teenage chatbot.
13c13
< A task marked with a X is done. To close me, type "bye". 
---
> A task marked with a X is done. To close me, type "bye".
Test result: FAILED
```

They both look the same to me, so I don't know why the error is coming (and it's only coming in the first and last output)

Background: 

Before this, I was getting 
```bash
dos2unix: Binary symbol 0x1B found at line 1
dos2unix: Skipping binary file ACTUAL.TXT
dos2unix: Binary symbol 0x1B found at line 1
dos2unix: Skipping binary file EXPECTED-UNIX.TXT
1,2c1,2
< Welcome to Lavender Network! 
< I'm Iris, your favourite teenage chatbot. 
---
> Welcome to Lavender Network!
> I'm Iris, your favourite teenage chatbot.
13c13
< A task marked with a X is done. To close me, type "bye". 
---
> A task marked with a X is done. To close me, type "bye".
Test result: FAILED
```

I searched online and added -f for the dos2unix command. Apart from that, I've only changed the filepaths in the.sh file

**Comment by Lava-Iris** [comment]
Update: I figured out what made the lines different from everything else.

Everywhere else, my code was "blah blah.\n" but only for these 3 lines, I had a space before the newline ("blah blah. \n")

I removed the space before the newline and it passed the test!

Can anyone tell me what just happened? Why did a space before the newline fail the tests?

**Comment by BoAi01** [comment]
In `runtest.sh`, the command`diff` is used to compare `ACTUAL.TXT` and `EXPECTED-UNIX.TXT` (line 30). It only returns true if the two text files are exactly the same (i.e., character by character), I think.

More info about `diff` can be found [here](https://man7.org/linux/man-pages/man1/diff.1.html)

Hope this helps!
