### ISSUE TITLE
Password for Lecture Recording

### ISSUE THREAD

**Issue by angjunkang** [nus-cs2103-AY2223S2/forum#250]
There seems to be a password set for the today's lecture recording. Anyone knows the password?

**Comment by damithc** [comment]
@Irminrics I removed the password requirement. Try this link https://nus-sg.zoom.us/rec/share/pM6lZgRX-_r7TTtk71cVpovzS0trrIM_Ry6Hfew9PuCVKFt3etEGwyISiCDusPIQ.6I4FwZ39MuUiOuT8

**Comment by angjunkang** [comment]
Thanks for the prompt reply prof :)
