### ISSUE TITLE
Is it ok to omit arguments for method invocation in sequence diagrams?

### ISSUE THREAD

**Issue by weekiat-douze** [nus-cs2103-AY2223S2/forum#253]
<img width="708" alt="sequence" src="https://user-images.githubusercontent.com/58362911/224536236-8bf243c8-c7f0-4b94-862d-10f5180b915d.png">

The example here is also not in the method() format. Is there any restrictions when drawing invocations in sequence diagram?

**Comment by damithc** [comment]
@weekiat-douze 

This is a user typing a command, not a method call.

Also note:
1. Sequence diagrams model interaction between entities for a specific scenario, not necessarily execution of a code segment
2. When appropriate, you can use pseudo code in sequence diagrams

**Comment by weekiat-douze** [comment]
@damithc 
I see. Then would it be wrong if arguments are excluded in the pseudo code? 
For example, Week 8 Tutorial, 
addPerson() instead of addPerson(p) or Person() instead of Person("Adam", "friend")
```
PersonList personList = new PersonList();
while (hasRoom) {
    Person p = new Person("Adam", "friend");
    personList.addPerson(p);
}

```

**Comment by damithc** [comment]
> I see. Then would it be wrong if arguments are excluded in the pseudo code? For example, Week 8 Tutorial, addPerson() instead of addPerson(p) or Person() instead of Person("Adam", "friend")
> 
> ```
> PersonList personList = new PersonList();
> while (hasRoom) {
>     Person p = new Person("Adam", "friend");
>     personList.addPerson(p);
> }
> ```

@weekiat-douze Depends on the context. It could be misleading as `foo(x)` and `foo()` are technically two different methods. Perhaps something like `foo(...)` might be better to clearly show that parameters have been omitted.

**Comment by weekiat-douze** [comment]
I see, understood. Thank you!
