### ISSUE TITLE
Stuck on "Job is about to start running on the hosted runner"

### ISSUE THREAD

**Issue by eugenetangkj** [nus-cs2103-AY2223S2/forum#254]
Hi, I recently followed the GUI tests that AB4 has, to conduct testing for my team's updates to the GUI. However, I encountered an issue of being stuck at the `ubuntu-latest` CI build, where on GitHub, it would be stuck at `Build and check with Gradle`, having no progress in doing the required checks. There is no problem for `macos-latest` and `windows-latest` where the builds managed to successfully complete.

Loading:
![image](https://user-images.githubusercontent.com/86542359/224614809-4b73f917-e4d4-4876-9d5c-d13670844c86.png)

Log message:
![image](https://user-images.githubusercontent.com/86542359/224614004-2693d2c6-6ce2-461f-b320-55473b9d0816.png)

I thought that it might be a problem with my `build.gradle` file but the `ubuntu-latest` build managed to complete when I push only my changes to `build.gradle` without my GUI unit tests. Hence, the problem might be with my GUI unit tests, but I am not sure whether that would be the case because all tests managed to complete successfully locally and the CI builds for `macos-latest` and `windows-latest` were complete.

Could I kindly seek some advice on this issue? Thank you!

**Comment by damithc** [comment]
@eugenetangkj This is the kind of problem one encounters with GUI tests, especially in CI, and especially on Linux. Quite hard to debug. 

Some suggestions: 
* See if you can get a team member to run GUI tests on Linux locally. 
* Configure CI to skip GUI tests on Linux. Testing the GUI on two OS'es is still much better than not doing it all.

**Comment by eugenetangkj** [comment]
Hi Prof @damithc, thank you for your reply! I managed to resolve it with the help of a method in `GuiUnitTest` from a past [CS2103T project](https://github.com/AY2223S1-CS2103T-W17-4/tp). I have given credit for the method accordingly in my code as well. Appreciate the guidance!
