### ISSUE TITLE
Codecov suddenly not working

### ISSUE THREAD

**Issue by Mehvin** [nus-cs2103-AY2223S2/forum#255]
Codecov has always worked, however it suddenly didnt work/appear on my latest pull request, [here](https://github.com/AY2223S2-CS2103-W16-1/tp/pull/66)

On the codecov dashboard, the error seems to be Missing Head Commit as seen below:
![image](https://user-images.githubusercontent.com/19343031/224634945-58442055-8614-43ac-a7fd-06e0319d0670.png)

Anyone faced similar problems before and know the fix?

**Comment by damithc** [comment]
@Mehvin CodeCov is known to run into problems intermittently. Perhaps try re-running the CI a few times?

**Comment by Mehvin** [comment]
Rerunning the CI works, CodeCov ran too now. Thanks!
