### ISSUE TITLE
AssertNotEquals for comparing reference (not value)

### ISSUE THREAD

**Issue by adam07018** [nus-cs2103-AY2223S2/forum#256]
Basically, I use a clone method to **deep copy** the Addressbook. 

For example, **AB2 = AB1.clone()**; AB2 and AB1 has **same userList but they got different reference**.

Thus, If I write **AssertNotEquals(AB1, AB2)**, it should pass test.

 However, I found out that there is a **equal method overloaded in Addressbook class** which make my **AssertNotEquals** fail. 
 Because equal method in Addressbook will return true if their userList are same. 

```
public boolean equals(Object other) {
return other == this // short circuit if same object
                || (other instanceof AddressBook // instanceof handles nulls
                && clients.equals(((AddressBook) other).clients));
}
```
Is there anyway to bypass the overload equal and let test method (use the java object equal) **directly compare their reference**?

**Comment by daitenshionyan** [comment]
`assertFalse(AB1 == AB2)` should compare the references.

However I think a combination of both would be better. One to compare if they are different references and the other to check if they have the same state.
```java
assertFalse(AB1 == AB2)
assertEquals(AB1, AB2)
```

**Comment by adam07018** [comment]
Answer is found
