### ISSUE TITLE
Should we add the `A-Collections` tag together with/after `Level 6` tag?

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#26]
`A-Collections` extension from `Level-6` asks us to use collections for our tasks. But I've used `ArrayList` since `Level-2`.  
So should I tag the commit at `Level-2`?  
Or should I tag it at `Level-6` to follow the given order, as per @damithc in #8:
> @BoAi01 Yes, try to follow the given order as much as possible. No, we don't penalize if you don't follow the order.

**Comment by damithc** [comment]
Either way is fine, @EvitanRelta

**Comment by EvitanRelta** [comment]
Ok thanks!
