### ISSUE TITLE
Will like to check if can use this external API.

### ISSUE THREAD

**Issue by SFCoding123** [nus-cs2103-AY2223S2/forum#260]
## Library

[pdfBox](https://www.apache.org/dyn/closer.lua/pdfbox/3.0.0-alpha3/pdfbox-app-3.0.0-alpha3.jar)

## Purpose

{Intended to display PDF file that the user has uploaded}

## License

{Apache 2.0 https://www.apache.org/licenses/LICENSE-2.0}

@damithc

**Comment by damithc** [comment]
Approved.
