### ISSUE TITLE
Request to use Joda-Time library.

### ISSUE THREAD

**Issue by russelltankaimin** [nus-cs2103-AY2223S2/forum#261]
## Library

[Joda-Time](https://www.joda.org/joda-time/index.html)

## Purpose

It is easier to use compared to java's in-built LocalTime for my team's scheduler feature.

## License

Apache License, Version 2.0
[Link to Lisence Page](https://www.joda.org/joda-time/licenses.html)

**Comment by damithc** [comment]
Approved.
