### ISSUE TITLE
Irreparable Checkstyle errors

### ISSUE THREAD

**Issue by daytona65** [nus-cs2103-AY2223S2/forum#262]
I have tried alot of things so please help.
My import statements:
![image](https://user-images.githubusercontent.com/74140641/225933091-b659bf75-d66a-4e36-994e-90ce3fc670fd.png)

My error:
![image](https://user-images.githubusercontent.com/74140641/225933174-79d96bc5-d119-4671-9e66-937e4c683123.png)

How to fix? have tried rearranging the statements in every imaginable way possible

**Comment by daitenshionyan** [comment]
Try this:
```java
import static java.util.Objects.requireNonNull;
import static seedu.address.logic.parser.CliSyntax.PREFIX_NAME;
import static seedu.address.logic.parser.CliSyntax.PREFIX_NRIC;
import static seedu.address.logic.parser.CliSyntax.PREFIX_STATUS

import java.util.function.Predicate;

import seedu.address.commons.core.Messages;
import seedu.address.model.Model;
```

I think the checkstyle wants us to put static imports at the top.

**Comment by rexcyrio** [comment]
You can also try [configuring IntelliJ's import order to better match the checkstyle](https://se-education.org/guides/tutorials/intellijCodeStyle.html#tweak-import-order).

**Comment by daytona65** [comment]
Thanks daitenshionyan! seems like that works
