### ISSUE TITLE
PlantUML not rendering same image as original DG

### ISSUE THREAD

**Issue by jerome-neo** [nus-cs2103-AY2223S2/forum#266]
Following the steps to install `Graphviz` for Windows and MacOS in IntelliJ, the resulting diagram for `StorageClassDiagram.puml`  did not look like the one in the developer's guide in both operating systems.

The image attached shows the rendered diagram. The file `StorageClassDiagram.puml` was never modified.

![StorageClassDiagram](https://user-images.githubusercontent.com/83827415/226192717-2754d774-9e50-4be9-b2f8-c06b7842d12d.png)

Any help/advice is appreciated, thank you!

**Comment by damithc** [comment]
@jerome-neo might be related to the PlantUML version i.e., recent versions of PlantUML might render diagrams differently from earlier versions.
Let's wait to see if others are facing similar problems.

**Comment by jerome-neo** [comment]
My temporary get around for this issue is to run the files on Visual Studio Code with the extension, [PlantUML](https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml). This renders `StorageClassDiagram.puml` properly.

**Comment by kyueran** [comment]
I faced the same problem with IntelliJ IDEA 2022.3.3 (Ultimate Edition) with v1.2023.2 PlantUML.

I fixed it by changing to IntelliJ IDEA 2021.3.1 (Community Edition) with v1.2022.12 PlantUML.

You need to download the PlantUML for the old version of intellij cos the old version of PlantUML is not compatible with the new version of IntelliJ. This v1.2022.12 PlantUML version is automatically downloaded for IntelliJ IDEA 2021.3.1 (Community Edition).

**Comment by eugenetangkj** [comment]
I faced the same problem too! Might be a version issue. I think the problem is the package `Storage` and the interface `Storage` are both referred to `as Storage`, that's why the arrows are not pointing correctly. I just renamed the interface to `StorageInterface` and the arrows point correctly.  Referring to `StorageClassDiagram.puml`, I changed line 14 to `Class "<<interface>>\nStorage" as StorageInterface`.

**Comment by damithc** [comment]
Good catch @eugenetangkj Thanks for sharing this solution. Others, does that solution work for you too?

**Comment by jerome-neo** [comment]
Thank you all for the suggestions! Unfortunately, changing line 14 did not work for me. I'll try downgrading IntelliJ and PlantUML.

**Comment by eugenetangkj** [comment]
HI @jerome-neo, did you change lines 28, 30, 34 and 35 as well?

**Comment by jerome-neo** [comment]
Yes, that works! Thanks for saving me all that trouble @eugenetangkj, forgot about the rest of references to `Storage`.

**Comment by Creationsv2** [comment]
Can confirm that changing the Package name works. Similar problem in other diagrams such as ModelClassDiagram.puml as well.
