### ISSUE TITLE
Questions about JavaFX

### ISSUE THREAD

**Issue by StanleyNeoh** [nus-cs2103-AY2223S2/forum#267]
![image](https://user-images.githubusercontent.com/95394480/226194714-9c5a8937-54dd-4237-b4d1-6bb7cbf38021.png)
Hello there, why should we execute the show method before we fill out the content of the stage regarding JavaFX? The above code snippet is taken from [UiManager.java](https://github.com/nus-cs2103-AY2223S2/tp/blob/master/src/main/java/seedu/address/ui/UiManager.java#L44)

**Comment by damithc** [comment]
@StanleyNeoh did you try switching the order of those two statements? I'm curious to know if there is a visible change if the order is changed.

**Comment by StanleyNeoh** [comment]
I swapped the order between the 2 statements, and so far it doesn't seem to have any visible change, but I am not sure if it will introduce any bugs.

**Comment by dohaduong** [comment]
I was confused about this part too, cuz seems like both ways work. Theoretically, would there be any difference/issue if we swap the order?

**Comment by damithc** [comment]
As per git blame, this code was added long ago, at the early stages of AB3 development when quality control was not as strict as it was in later stages. It is possible the the prescribed order of statement was unnecessary to begin with (i.e., a misunderstanding by the developer), or was necessary at the time but became no longer necessary with the passage of time. In either case, it is something for the AB3 devs to look into. Feel free to file an issue at https://github.com/se-edu/addressbook-level3/issues

More importantly, this shows **the value of using comments to [explain the _WHY_ aspect](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/codeQuality.html#explain-what-and-why-not-how)**, not just the _WHAT_ aspect.

**Comment by dohaduong** [comment]
> [<img alt="@damithc" width="40" height="40" src="https://avatars.githubusercontent.com/u/1673303?s=80&amp;u=1732a87200a4da87271fefb1f5ebaa20a482f286&amp;v=4">](/damithc)
> Member
> ###
> ** [damithc](/damithc) ** commented [Mar 24, 2023](#issuecomment-1482664295)

Oh, I see, thank you prof for the clarification!
