### ISSUE TITLE
Importance of Proper RepoSense

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#268]
From the module website, it says that we should keep track of authorship of code. This may cause additional rigor if we have to use @@author tags everywhere. How important is this component, should we just use git history for tagging instead?

https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

**Comment by PhilipSchifofr** [comment]
It is important to keep track of authorship of code as it helps in maintaining code quality and accountability. Using Git history alone may not be enough to accurately determine who authored which lines of code, especially in collaborative projects where multiple contributors may have made changes to the same files.

Tools like RepoSense provide a more comprehensive way of tracking authorship of code by analyzing the Git repository and generating reports that show statistics on code contributions by author, file, and directory. This can be useful in identifying areas of the code that may need improvement or additional review, and can also help in identifying potential bottlenecks or single points of failure in the development process.

While it may add additional overhead to tag every file with authorship information, it is generally recommended to use tools like RepoSense to keep track of code authorship, as it provides a more accurate and detailed view of code contributions.

**Comment by francisyzy** [comment]
Nice try ChatGPT

![Screenshot 2023-03-20 at 1 45 15 AM](https://user-images.githubusercontent.com/24467184/226196207-210460f4-e243-4191-8bd6-b34c9271afb5.png)
![image](https://user-images.githubusercontent.com/24467184/226196225-68ded6d4-df99-4c7a-8f01-55f8cc2060dc.png)

**Comment by damithc** [comment]
> Nice try ChatGPT

Yup :-p

**Comment by damithc** [comment]
> From the module website, it says that we should keep track of authorship of code. This may cause additional rigor if we have to use @@author tags everywhere. How important is this component, should we just use git history for tagging instead?
> 
> https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

@francisyzy normally, you don't need to track authorship manually using `@@author` tags. RepoSense does that automatically using Git data. You only need to use `@@author` tags when you want to override the authorship allocation RepoSense generates based on Git data. You can do this closer to the final submission. In most cases, the authorship allocation generated by RepoSense will be close enough in which case you can let it be.

**Comment by francisyzy** [comment]
Thanks prof! Will close the issue in a couple of days so that people can see this question!
