### ISSUE TITLE
Use Git's lightweight tag or annotated tag?

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#27]
The [week 2 project page] didn't explicitly specify whether to use lightweight or annotated tags.

But since it didn't ask for the `-a` flag when doing `git tag` (eg. `git tag -a Level-1`),  
I'm assuming its lightweight?

The problem is if the tags were annotated, they could easily be pushed using `git push --follow-tags`.  
But this doesnt work for lightweights.

So I was wondering if we could use annotated tags instead of lightweights?  
And more importantly: <ins>**Will it mess up the grader script?**</ins>

[week 2 project page]: https://nus-cs2103-ay2223s2.github.io/website/schedule/week2/project.html#:~:text=git%20tag%20the%20commit%20with%20the%20exact%20increment%20ID%20e.g.%2C%20Level%2D2%2C%20A%2DTextUiTesting

> Edit: I just found out that u could push all tags via: `git push --tags`.  
> But i still would like to know if annotated ones are allowed just in case.

**Comment by damithc** [comment]
@EvitanRelta the expectation is lightweight (i.e., default) tags. But annotated tags should be fine too. You can try one first and confirm it is detected by the [iP dashboard](https://nus-cs2103-ay2223s2.github.io/dashboards/contents/ip-progress.html) on the following day.

**Comment by Junyi00** [comment]
@EvitanRelta I am using annotated tags and the iP dashboard seems to detect them as well.

**Comment by EvitanRelta** [comment]
ok thanks!
