### ISSUE TITLE
Import vs Import Static

### ISSUE THREAD

**Issue by lhy-hoyin** [nus-cs2103-AY2223S2/forum#272]
Is there a preference/rule/standard on when to use `import xxx` vs when to use `import static xxx.yyy`?

For example, in [`AddCommandTest`](https://github.com/nus-cs2103-AY2223S2/tp/blob/master/src/test/java/seedu/address/logic/commands/AddCommandTest.java)
``` java
import static java.util.Objects.requireNonNull;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static seedu.address.testutil.Assert.assertThrows;

import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.function.Predicate;

// more imports below

public class AddCommandTest {

    @Test
    public void constructor_nullPerson_throwsNullPointerException() {
        assertThrows(NullPointerException.class, () -> new AddCommand(null));
    }

    // more tests

}
```

I believe that if `import seedu.address.testutil.Assert` is used instead, then the test would look like this
```java
@Test
    public void constructor_nullPerson_throwsNullPointerException() {
        Assert.assertThrows(NullPointerException.class, () -> new AddCommand(null));
    }
```

**Comment by jiasheng59** [comment]
I think as long as the imported method name doesn't conflict with any method name within the class, it's fine to use import static... I also wonder when will one choose one over another 🤔

**Comment by jiasheng59** [comment]
The reason I can think of is that import static could be used as a shorthand for constants and methods that are used many times within the class you are working with.

**Comment by dohaduong** [comment]
agree, i think import static is mostly used to access static members (constants, etc) of other classes/interfaces, so it's up to you which one you prefer
