### ISSUE TITLE
Apache PDFBox

### ISSUE THREAD

**Issue by gwynethguo** [nus-cs2103-AY2223S2/forum#273]
## Library

[Apache PDFBox](https://pdfbox.apache.org/)

## Purpose

To generate PDF files for the users (for students' progress reports).

## License

[Apache](https://www.apache.org/licenses/LICENSE-2.0)

**Comment by gwynethguo** [comment]
Hi Prof! I looked for another alternative, and updated issue details. Thank you for the fast response!

**Comment by damithc** [comment]
Approved, @gwynethguo
