### ISSUE TITLE
Reuqest to use CalendarFX

### ISSUE THREAD

**Issue by arkobrat** [nus-cs2103-AY2223S2/forum#274]
## Library

[CalendarFX](https://github.com/dlsc-software-consulting-gmbh/CalendarFX)

## Purpose

To show a calendar view of appointments in the UI.

## License

[Apache-2.0 license](https://github.com/dlsc-software-consulting-gmbh/CalendarFX/blob/master-11/LICENSE)

**Comment by damithc** [comment]
Approved (also, duplicate of #205)
