### ISSUE TITLE
Issue with text ui test

### ISSUE THREAD

**Issue by yitong241** [nus-cs2103-AY2223S2/forum#28]
Hello, my runtest.sh only reads the first line of input.txt, may I know what I can do to fix it?

**Comment by ScorpiusSigma** [comment]
Do you have new lines between your inputs? Be sure to remove them

**Comment by hingen** [comment]
Did you perhaps write your input.txt in Windows? If so, could be an issue with difference in line ending. Try rewriting your input.txt using vim

**Comment by damithc** [comment]
@yitong241 what is the exact behavior? This can happen due to many reasons and knowing more details can help others narrow down the cause. You can even push the code to your repo and share the link here.

**Comment by yitong241** [comment]
hi prof you can check my "ip" repo, i tried with some cases, only the first line of input.txt will be read.

**Comment by damithc** [comment]
Let's see if someone can take a look at the code and point you towards the problem (my guess is it is due to the way you read user commands).

**Comment by Junyi00** [comment]
@yitong241 I believe the issue resides [here](https://github.com/yitong241/ip/blob/f14b3fd7e7c5f6c4abac27bab95df656b0790edb/src/main/java/Tasks/Monitor.java#L54-L57)

```java
// Monitor.java
public String getCommand() {
    Scanner sc = new Scanner(System.in);
    return sc.nextLine();
}
```

Typically only a single scanner instance should be reading from the input stream. I am not sure why in this instance of UI testing only then this is problematic...

**Comment by yitong241** [comment]
thx! @Junyi00 and @damithc! I think I know where the problem is!

**Comment by damithc** [comment]
> Typically only a single scanner instance should be reading from the input stream. I am not sure why in this instance of UI testing only then this is problematic...

Yup, the OS feeds the entire file to the first Scanner object, leaving nothing for the subsequent Scanner objects.
