### ISSUE TITLE
Sequence diagram

### ISSUE THREAD

**Issue by lyndonlim27** [nus-cs2103-AY2223S2/forum#281]
For sequence diagram, if the length of an operation is too long due to a lengthy command, is it okay to split it into two lines or is it incorrect? 

Reason is so that the sequence diagram would not be too wide and small

For example 

Instead of this: 
<img width="684" alt="image" src="https://user-images.githubusercontent.com/80683209/227769476-83853dd7-e8d9-4d73-878b-5dc483b74bf6.png">

Do this: 
<img width="456" alt="image" src="https://user-images.githubusercontent.com/80683209/227769493-e85bea81-d2d2-46bd-9319-5ca5632a865e.png">

**Comment by salty-flower** [comment]
Good question🤔 curious too

**Comment by damithc** [comment]
> <img alt="image" width="456" src="https://user-images.githubusercontent.com/80683209/227769493-e85bea81-d2d2-46bd-9319-5ca5632a865e.png">

@lyndonlim27 Yes, this is fine.

**Comment by lyndonlim27** [comment]
Thank you!
