### ISSUE TITLE
UG/DG pdf conversion

### ISSUE THREAD

**Issue by immanuelhume** [nus-cs2103-AY2223S2/forum#283]
The module website suggests [using gchrome](https://se-education.org/guides/tutorials/savingPdf.html) to generate the pdf. I wonder if this is a hard requirement? Or is it okay if

1. we try other conversion methods?
1. closer to the deadline, temporarily use a slightly modified version of the .md file to try and get better conversion results?

**Comment by damithc** [comment]
@immanuelhume 

> * we try other conversion methods?

Sure.

> * closer to the deadline, temporarily use a slightly modified version of the .md file to try and get better conversion results?

Sure.

Keep in mind that any issue with the PDF file (e.g., broken links) will be considered as bugs.
