### ISSUE TITLE
Must you always categorise classes with similar functionality/ behaviour together?

### ISSUE THREAD

**Issue by ChickenChiang** [nus-cs2103-AY2223S2/forum#286]
For our tP we are adding a Team, UniqueTeamList, and TeamTag class to the addressbook. Their behaviour is similar to that of the pre-existing Person, UniquePersonList, and Tag classes. 

Just because they behave similarly do we have to make it such that they both extend the same parent class/ implement the same interface? 
- Team class mirrors Person class
- UniqueTeamList mirrors UniquePersonList
- TeamTag mirrors Tag

Does this violate any coding standards, or is it sufficient to mention that they behave similarly in the DeveloperGuide and in the comments? I can't seem to find any coding priciples that it would violate in the textbook. My thinking is that it is not necessary as they are divided into their respective packages i.e. team package and person package.

Thanks in advance!

**Comment by damithc** [comment]
Good question for a OOP discussion @ChickenChiang 
Views from others welcome

**Comment by damithc** [comment]
> Does this violate any coding standards

Not according to https://se-education.org/guides/conventions/java/intermediate.html


> My thinking is that it is not necessary as they are divided into their respective packages i.e. team package and person package.

Yes, you can go with this approach first and monitor the situation. If it makes the code harder to understand/maintain, you can try other alternatives, of which inheritance is one.
