### ISSUE TITLE
Feature freeze question

### ISSUE THREAD

**Issue by potty10** [nus-cs2103-AY2223S2/forum#287]
I understand that I cannot change any features after this week due to feature freeze.

However, is it ok if I remove features?

**Comment by damithc** [comment]
@potty10 Yes, feature removal is allowed during the feature freeze. 

More info [here](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/project.html#2-start-fixing-ped-bugs-before-the-tutorial)
![image](https://user-images.githubusercontent.com/1673303/228168672-f9f1911b-8bf9-4ef5-8c94-6f9c68f20852.png)

**Comment by potty10** [comment]
Thank you!
