### ISSUE TITLE
Default window size

### ISSUE THREAD

**Issue by CarrieLi1015** [nus-cs2103-AY2223S2/forum#290]
Hello prof and peers.
May I ask if it is ok for us to adjust the DEFAULT_HEIGHT and DEFAULT_WIDTH under the GuiSettings?

**Comment by damithc** [comment]
@CarrieLi1015 The module doesn't have any restrictions on this. So, it's a question of whether that is a good behavior for the product. 
Perhaps give more specifics? Are you suggesting to automatically set the window size to a specific dimension when the application is launched?

**Comment by CarrieLi1015** [comment]
Thank you for your reply prof! The application window size is adjustable, but still we need to set a reasonable minima height and width (cannot be too large) as people using different sizes laptop. Which means, it might be the best if we could detect the screen size when the application is launched, and set application size based on that?

**Comment by damithc** [comment]
> Which means, it might be the best if we could detect the screen size when the application is launched, and set application size based on that?

@CarrieLi1015 No objections to doing so. Also note that AB3 already 'remembers' the previous Window size the next time it is used.  So, if the user adjusts the size, the adjusted size will be used next time.

**Comment by CarrieLi1015** [comment]
Noted! Thank you so much prof!
