### ISSUE TITLE
The reason of  using the name for `ReadOnlyAddressBook` interface

### ISSUE THREAD

**Issue by QQH0828** [nus-cs2103-AY2223S2/forum#291]
Hi, prof and peers,
May I ask that the reason of `ReadOnlyAddressBook` interface is used by this name is because `AddressBook` is the project name or is it a name used for storing all the person's details (readability)? My teammates and I are thinking about this question, and we have different thoughts. Regarding the UML diagram below
![image](https://user-images.githubusercontent.com/122513302/228414523-661fc961-0447-4dea-b8e1-a2493e3c88d4.png)
Model -> AddressBook and UserPrefs; AddressBook -> person's details.

Some of us think we should change `AddressBook` to our own project name, and some of us think should keep it.

**Comment by damithc** [comment]
> May I ask that the reason of `ReadOnlyAddressBook` interface is used by this name is because `AddressBook` is the project name or is it a name used for storing all the person's details (readability)?

@QQH0828 The classes are named based on what the class/component represents, not based on the product name. In this case it happens to match product name as well.

**Comment by QQH0828** [comment]
Thanks, prof!
