### ISSUE TITLE
Gradle CI workflow dependency library is down

### ISSUE THREAD

**Issue by heeeyi** [nus-cs2103-AY2223S2/forum#292]
Hi I have recent push on Github, which was failed reporting error "Could not HEAD <a gradle jar dependency>". Received status code 503 from server: Service unavailable. This is the screenshot: 

![image](https://user-images.githubusercontent.com/97591125/228540677-96a68b9d-6be3-4efb-a1a9-09a5304d7c01.png)

When I tried to follow the link for the last failed jar file, the webpage shows 404 error. Therefore, this resource is genuinely missing. In this case, how are we suppose to do our CI/CD workflow check, or should we just bypass it?

![image](https://user-images.githubusercontent.com/97591125/228540962-ef6823f1-05e8-4a69-a863-595330d5e8e6.png)

**Comment by ShiJiaAo** [comment]
I was getting the same issue too. Looks like it's a gradle problem and I believe you can check the status here:
https://status.gradle.com/

It seems like these timeouts are random. I just kept redoing the test and it worked eventually.

**Comment by damithc** [comment]
> I was getting the same issue too. Looks like it's a gradle problem and I believe you can check the status here: https://status.gradle.com/
> 
> It seems like these timeouts are random. I just kept redoing the test and it worked eventually.

Thanks for sharing this @ShiJiaAo 
Seems to be back to normal now.
