### ISSUE TITLE
UML sequence diagram ref without and sd

### ISSUE THREAD

**Issue by StanleyNeoh** [nus-cs2103-AY2223S2/forum#293]
Hello.

I am currently trying to draw a UML sequence diagram to show many if-else statements, similar to what you may see in a Command pattern.

![EventHandling](https://user-images.githubusercontent.com/95394480/228607161-986b06af-6f97-47eb-8de3-5cc79319cff1.png)

Is it okay to use refs without a sd for every ref? 

Thank you in advance

**Comment by damithc** [comment]
@StanleyNeoh Yes. In fact, you can also omit some of the ref frames as they don't seem to add much value.  Show just a few and add a note to explain how the rest are done similarly.

**Comment by StanleyNeoh** [comment]
@damithc Thank you
