### ISSUE TITLE
Fixing wrong update of UI during feature freeze

### ISSUE THREAD

**Issue by potty10** [nus-cs2103-AY2223S2/forum#297]
Hi,

Let's say I have a command that changes a part of the UI differently in various situation (Example, show A or B). However, during testing, we found that it showed A instead of B. Is fixing it considered violating the feature ~~flaw~~ freeze? We will not be changing the UI A and B itself.

During feature freeze, assume that we have to remove a feature. This will cause feature B to change UI in a different way as advertised. Will this be considered violating feature freeze?

**Comment by damithc** [comment]
@potty10 

> Let's say I have a command that changes a part of the UI differently in various situation (Example, show A or B). However, during testing, we found that it showed A instead of B. Is fixing it considered violating the feature ~flaw~ freeze? We will not be changing the UI A and B itself.

As the current behavior is incorrect (i.e., UI shows the wrong thing), it will qualify as a bug. Hence, fixing it is allowed during the feature freeze.


> During feature freeze, assume that we have to remove a feature. This will cause feature B to change UI in a different way as advertised. Will this be considered violating feature freeze?

This can be allowed too, but only to the minimal extent necessitated by the removal of the feature.

**Comment by potty10** [comment]
Thank you!
