### ISSUE TITLE
Week 1 Quiz - Question 5

### ISSUE THREAD

**Issue by jiasheng59** [nus-cs2103-AY2223S2/forum#3]
![image](https://user-images.githubusercontent.com/96868229/212346458-c0b7d765-cea9-4066-8391-4edbd758684b.png)

Is it referring to Java or all programming languages in general?

**Comment by hingen** [comment]
In general, not specific to any language

**Comment by damithc** [comment]
> In general, not specific to any language

@hingen is correct.
