### ISSUE TITLE
Accidentally starting another Quiz attempt

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#30]
I've finished Quiz 2 already, but accidentally started another attempt (which i have not filled in nor submitted)

Can i just leave it unsubmitted? Or will that attempt be autosubmitted on the deadline, and give me 0 marks since its not filled in, and its the latest attempt?

**Comment by damithc** [comment]
@EvitanRelta We take the highest score, not the latest attempt.

**Comment by zm-l** [comment]
@damithc May I ask if the "highest score" is highest number of corrects in the quiz or is it inclusive of the points you earned?

**Comment by damithc** [comment]
> @damithc May I ask if the "highest score" is highest number of corrects in the quiz or is it inclusive of the points you earned?

@zm-l The two (i.e., the quiz score and the number of correct answers) are the same

**Comment by zm-l** [comment]
@damithc Sorry I mean inclusive of the early submission points.

**Comment by damithc** [comment]
> @damithc Sorry I mean inclusive of the early submission points.

@zm-l The two are independent.

We first take the highest scoring submission. If it was done during the early submission period, you get the bonus point for early submission.
