### ISSUE TITLE
User Guide [Invalid YML front matter]

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#300]
![Screenshot 2023-03-31 at 12 40 21 PM](https://user-images.githubusercontent.com/76247607/229024158-8037970f-d1f3-48ad-8e36-26578c9c9ef9.png)

I am not sure why the GitHub pages are not updated accordingly to the markdown file that we have in Github. This seems to be the error but we are not sure what is the problem. Is there anything we can do about it?

**Comment by damithc** [comment]
@pangrwa It might help if you share the link to relevant file(s) and the CI log.

**Comment by pangrwa** [comment]
We have fixed it, it's because we didn't put the title!
