### ISSUE TITLE
Cannot load javafx library 

### ISSUE THREAD

**Issue by SHni99** [nus-cs2103-AY2223S2/forum#301]
Hi,
I am facing an issue when testing out the jar.file just now. 
I am using mac os terminal to run the jar command

![image](https://user-images.githubusercontent.com/96757889/229047662-5bfb778b-f0bf-4cfa-83bf-64b1c937503d.png)

**Comment by damithc** [comment]
@SHni99 ensure you've followed to the letter the instructions for Mac users given in https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html#programming-language

**Comment by francisyzy** [comment]
I faced this problem just now after installing PlantUML as they messed up my `java --version`.

I used https://sdkman.io to install java quickly using the following java version: `sdk install java 11.0.18.fx-zulu`

**Comment by SHni99** [comment]
Thanks Profs, it worked after I have set my java  environment version to zulu jdk 11, which I followed the simplest method using [sdkman](https://sdkman.io/) as recommended by Francis.

**Comment by damithc** [comment]
> Thanks Profs, it worked after I have set my java environment version to zulu jdk 11, which I followed the simplest method using [sdkman](https://sdkman.io/) as recommended by Francis.

Thanks @francisyzy
