### ISSUE TITLE
Question on feature freeze

### ISSUE THREAD

**Issue by swx0** [nus-cs2103-AY2223S2/forum#303]
Are we allowed to modify default data shown to users during feature freeze? 
If not, are we allowed to delete some parts of the default data?

**Comment by damithc** [comment]
> Are we allowed to modify default data shown to users during feature freeze?
> If not, are we allowed to delete some parts of the default data?

@swx0 Only bug fixing is allowed. So, you can change sample data only to fix an error in the current data.

**Comment by swx0** [comment]
Thanks prof!
