### ISSUE TITLE
My PED is not tracked for some reason

### ISSUE THREAD

**Issue by Acerizm** [nus-cs2103-AY2223S2/forum#305]
I checked my status for participation for PED and it was recorded that I did not participate but I did. Did I do something wrong? Catcher created a repo of the issues that I raised at https://github.com/Acerizm/ped/issues

**Comment by damithc** [comment]
@Acerizm where does it say you did not participate in the PED? PED participation is counted for week 12, which is not yet in the participation dashboard.
Perhaps you are referring to CATcher load testing, which was done during the lecture of the previous week (not yesterday).

**Comment by Acerizm** [comment]
Sorry prof I got confused with the week my bad!
