### ISSUE TITLE
tP feature was present in the v1.3 JAR file but was not tested during PED due to UG being "out of sync"

### ISSUE THREAD

**Issue by rexcyrio** [nus-cs2103-AY2223S2/forum#306]
Tester A: @Yufannnn
Tester B: @homuntan02
Tester C: @jinnieshin
Tester D: @zrei

At 1:47pm, [https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/105](https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/105) was closed -- the `find` command in the UG was updated to say that it performs a full text search on all fields of a contact (instead of just the name field), and the command history feature was also added to the UG. Both of these features were already present in the v1.3 JAR file.

![vivaldi_T69n9rfuRK](https://user-images.githubusercontent.com/76687125/229328958-88adc5a3-d826-427e-aa7b-19c82ac3c1f5.png)

![vivaldi_7hzy1PjcsA](https://user-images.githubusercontent.com/76687125/229328968-f3685691-b99c-4086-9f4d-28b4328244dc.png)

At 1:48pm, the GitHub pages deployment for UG was updated ([https://github.com/AY2223S2-CS2103T-W10-3/tp/deployments/activity_log?environment=github-pages](https://github.com/AY2223S2-CS2103T-W10-3/tp/deployments/activity_log?environment=github-pages))

<br>

One of our peer reviewers got the updated UG (it shows the updated `find` command in the screenshot)

- see [https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/122](https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/122)

<br>

Unfortunately, it seems like two of our peer reviewers had loaded the page before [https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/105](https://github.com/AY2223S2-CS2103T-W10-3/tp/pull/105) was deployed at 1:48pm, and got the "old" version of the UG

- see [https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/107](https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/107)
- see [https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/128](https://github.com/AY2223S2-CS2103T-W10-3/tp/issues/128)

<br>

(I'm not sure which version of the UG Tester B got -- there was no mention of this problem in Tester B's bug reports to us, so I can only assume he got the updated UG)

---

My questions:
- can my team keep the updated full-text find feature in our tP?
- can my team keep the command history feature in our tP?

<br>

I ask this as I'm not sure whether it conflicts with the idea of v1.4:

![image](https://user-images.githubusercontent.com/76687125/229329414-65aa83ff-31fb-434a-88f7-c3e5b41a2651.png)

Tagging my teammates:
@niekis
@jugheadjones10
@minosx31

**Comment by damithc** [comment]
@rexcyrio You may keep the feature if it was in the v1.3 jar already, even if it wasn't tested by some testers during the PE-D.

**Comment by rexcyrio** [comment]
Okay thank you prof!
