### ISSUE TITLE
Can we use something like Miro for DG diagram?

### ISSUE THREAD

**Issue by mmaimer33** [nus-cs2103-AY2223S2/forum#308]
The requirements for diagrams for the Developer Guide say that whatever method we use needs to be able to be version-controlled. Would it be acceptable to use an online tool like [Miro](https://miro.com) to create them and then download and replace the local files as necessary?

**Comment by damithc** [comment]
@mmaimer33 Does the format also allow incremental edits by future developers (to cater for future evolution of the design)?

**Comment by mmaimer33** [comment]
They could do it online: follow a link, make a copy of the diagram, and download it to update the file in the project.

**Comment by damithc** [comment]
@mmaimer33 If all the requirements are met, it is fine to use another tool. 
That said, this particular tool requires sign up and has a pretty restrictive free tier (which might change any time), so I don't think it is a good long-term choice or worth the effort to migrate all diagrams in the project to this tool.

**Comment by mmaimer33** [comment]
Alright, thank you prof!
