### ISSUE TITLE
Requesting Permission to use a third-party Library: PrettyTime

### ISSUE THREAD

**Issue by zrei** [nus-cs2103-AY2223S2/forum#309]
## Library

[PrettyTime](https://github.com/ocpsoft/prettytime)

## Purpose

Apologies for not requesting permission sooner, it slipped my mind. This is a library my group used in v1.3 for Natural Language Processing of date and time inputs so we could parse user inputs like "tomorrow".

## License

[Apache 2.0](https://github.com/ocpsoft/prettytime/blob/master/LICENSE)

**Comment by damithc** [comment]
Approved.
