### ISSUE TITLE
Bug related to modifying data file

### ISSUE THREAD

**Issue by StanleyNeoh** [nus-cs2103-AY2223S2/forum#312]
Hello, we received a bug that is related to the behaviour of our application when the data file has been modified and unreadable. The current behaviour is that it will ignore the data file and start with an empty application which the tester says it is a bug as his data is lost.

My question is if unintended behaviour stemming from editing the data file is considered a valid bug, and if so what can we do to fix it?

**Comment by damithc** [comment]
@StanleyNeoh If your product comply with the below, any further enhancements can be argued as 'not in scope' for the current version, unless manual edits should be given a higher priority in the context of your specific product.

![image](https://user-images.githubusercontent.com/1673303/229399138-d300b147-d67f-43fb-a2a3-1077f99a59e6.png)

In any case, this is not a bug as it is not an error in code but how the feature is currently designed to work (i.e., a feature flaw). So, tweaking this behavior will not be allowed in v1.4
