### ISSUE TITLE
Feature Freeze - Changing command name

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#313]
Below are some of the existing user commands that 'add' things in our app:

- `add`
adds an athlete to the athlete list
- `add-tag`
adds a tag to an athlete
- `create-session`
adds a session to the session list
- `student-add`
adds a student to a session

One bug report we received from the PE-D was that the naming for these commands are inconsistent and may cause confusion, preventing users from using the app properly.
We agree with this notion and intend to standardize the names for these commands as such:

- `add`
- `add-tag`
- `add-session`
- `add-student`

We will NOT change the method signature or functionality of the commands.
All we are intending to change are the names and the names only.

May I ask if this is acceptable in the v1.4 Feature Freeze?
Thank you.

**Comment by damithc** [comment]
@Tempura-Person As this is a feature flaw and not a bug, it will not be allowed during the feature freeze.

**Comment by Tempura-Person** [comment]
thank you sir, noted.
