### ISSUE TITLE
Which documents to update?

### ISSUE THREAD

**Issue by hingen** [nus-cs2103-AY2223S2/forum#316]
Hello, may I know if we have to update all documents in the `docs` folder?

Currently, my team is only updating the User Guide, Developer Guide, and other guides linked to by these 2 guides. Wondering if other documentation like the ones in the `tutorials` directory need to be updated as well? Or are they optional?

**Comment by damithc** [comment]
@hingen Only the pdf versions of the UG and the DG will be used in the PE. So, you are welcome to update the other documents but it's not required.
