### ISSUE TITLE
Missing command: functionality bug, feature flaw, or documentation bug?

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#318]
In our UG, we claimed that we have `exit` command. However, in PE, the `exit` command was not working. Do we consider this as a functionality bug (command not working), feature flaw (not having an `exit` command), or documentation bug (`exit` command should not appear on UG)?

And are we allowed to make the corresponding change in v1.4?

**Comment by damithc** [comment]
@BoAi01 the following applies:

> Describing a feature in the UG without implementing it is a UG bug. The remedy is to remove the feature from the UG.
>
>If the behavior difference is because some parts of the feature is not implemented yet, the feature is incomplete (i.e., not a bug). The remedy is to remove the feature (if it is not usable in the current form) or update the UG to match the current version of the feature.

**Comment by BoAi01** [comment]
It's UG bug then. Noted with thanks!
