### ISSUE TITLE
Changing Display Messages

### ISSUE THREAD

**Issue by eugenetangkj** [nus-cs2103-AY2223S2/forum#319]
Hello! Currently, for our team's commands involving indexes, we have the following 3 messages:
1.  Negative Index or 0 -> `The index provided is invalid.`
2.  Positive index greater than size of list -> `The index provided is out of range.`
3.  Integer overflow (both positive and negative) -> `Invalid command format!`

Can I check will it be considered a breach of the feature freeze if we were to change the message for integer overflow? Our team is planning to change the message for integer overflow (negative) to be `The index provided is invalid.` and integer overflow (positive) to be `The index provided is out of range.`.

If we are not allowed to change it, then could we just specify in our user guide that the requirements of an index is an integer, state the range of what an integer should be, so if the user enters outside of this range, then it is valid to display `Invalid command format!`?

**Comment by damithc** [comment]
@eugenetangkj As the the current error messages are not strictly _incorrect_ (although can be more specific), this will be considered an enhancement rather than a bug fix.

Yes, you can tweak the UG and also list this under planned enhancements (to avoid a penalty for this in the PE).

**Comment by eugenetangkj** [comment]
Alright, thanks for the clarifications Prof! It really helped.
