### ISSUE TITLE
Use of self-created packages to neaten codebase

### ISSUE THREAD

**Issue by vigonometry** [nus-cs2103-AY2223S2/forum#32]
Hi teaching team, is it all right for us to move our core functions to classes within a package to neaten our code base and make debugging easier?

**Comment by francisyzy** [comment]
Would like to check if you're referring to this https://nus-cs2103-ay2223s2.github.io/website/admin/ip-w3.html#a-packages? Seems like its something to be done for iP in Week 3

**Comment by wxxedu** [comment]
I think it's ok? I have already done so.

**Comment by damithc** [comment]
> Would like to check if you're referring to this https://nus-cs2103-ay2223s2.github.io/website/admin/ip-w3.html#a-packages? Seems like its something to be done for iP in Week 3

@francisyzy is correct. 
@vigonometry moving classes to packages is a task due in week 3, but it's fine if you've done it already.

**Comment by vigonometry** [comment]
Apologies for the delayed response. I'd moved some of my task classes to a package for week 2 but was not aware that it was a task for week 3. 

Thanks for your help!
