### ISSUE TITLE
Omitting some dependencies and classes from a class diagram

### ISSUE THREAD

**Issue by hingen** [nus-cs2103-AY2223S2/forum#321]
Hello. I'm editing the Model class diagram at the moment as my team made significant changes to it. After including all dependencies and classes, the diagram has gotten way too complex. By stripping out some dependencies and classes, I'm able to make the diagram much simpler and still capture the general flow of how the main classes of the package depend on each other (which is what I'm trying to communicate).

I'm wondering are we allowed to omit some dependencies and classes from a class diagram? Would it still be a class diagram or would it be something else (e.g. architecture diagram)?

For example, in the following diagram, can I exclude the components of the `Person` class? Or perhaps, can I remove the "filtered" association between `ModelManager` and `Person`?

![image](https://user-images.githubusercontent.com/31367001/229738568-215a6f4d-5880-4b12-b768-a591791c0319.png)

**Comment by damithc** [comment]
> I'm wondering are we allowed to omit some dependencies and classes from a class diagram? Would it still be a class diagram or would it be something else (e.g. architecture diagram)?
> 
> For example, in the following diagram, can I exclude the components of the `Person` class? Or perhaps, can I remove the "filtered" association between `ModelManager` and `Person`?

@hingen Yes, you may omit some elements or break the diagram into multiple parts as you see fit -- provided the result is good enough for the purpose the diagram is used for, and does not mislead the reader. You can also add a note (a UML note or just a regular note outside the diagram) to indicate some/which parts have been omitted, to keep the reader informed of the omissions.
