### ISSUE TITLE
UI Truncation

### ISSUE THREAD

**Issue by eugenetangkj** [nus-cs2103-AY2223S2/forum#322]
Hello! Sorry, I would like to ask another question regarding the feature freeze. Currently, we have a field called `CompanyName` which we specify the limit to be 50 characters.

However, on devices of smaller sizes (e.g. 14 inch laptop), inputing a value of 50 characters leads to the value to be truncated on our UI, and cannot be shown fully even when the window is maximised.

![image](https://user-images.githubusercontent.com/86542359/229742668-18797be7-ffd5-4dbd-80bc-68a04347a6cb.png)

May I check if we are allowed to fix the truncation issue? This is because inputing a value of 50 characters is within the specifications of our product, and instead of changing the limit of 50 characters (which is more of a feature change), we feel that fixing the overflow issue is more closely-related to a bug fix.

Thank you!

**Comment by damithc** [comment]
@eugenetangkj You can fix it if it fits the description of a bug given below

![image](https://user-images.githubusercontent.com/1673303/229745418-b4f76f02-4c88-4c5b-86e1-16700b4bdf40.png)

**Comment by eugenetangkj** [comment]
Alright, thanks prof for the answer!
