### ISSUE TITLE
Question regarding what bug fixes are allowed

### ISSUE THREAD

**Issue by gyulong1** [nus-cs2103-AY2223S2/forum#323]
Hi Profs,

We currently have a profile picture feature and the intended behaviour is to show a default profile picture for new employees. 
However, we did not realise that the default picture does not appear in the .jar version, so no picture appears instead.
This leads to some graphical bugs, like the wrong employee's image being displayed.

To fix this, we can either fix the default picture implementation or implement show no picture at all for new employees.

Would we be allowed to implement the default picture as a bug fix?

**Comment by damithc** [comment]
> wrong employee's image being displayed 

@gyulong1 This is definitely a bug that needs fixing. So, go ahead but choose the path that minimizes the risk of breaking other features (which is the intention of the feature freeze).

**Comment by gyulong1** [comment]
Thanks prof!
