### ISSUE TITLE
Will we be penalised on PE for feature flaws?

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#325]
or will we be only penalised for bugs?

**Comment by damithc** [comment]
@EvitanRelta Yes, but [the _Planned enhancements_ section of the DG](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/project.html#:~:text=Using%20%27Planned%20Enhancements%27%20DG%20section%20to%20counter%20known%20feature%20flaws) provides a way to avoid the penalty.
