### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by HmuuMyatMoe** [nus-cs2103-AY2223S2/forum#326]
In our PE dry run, we received a report that our UI was not intuitive enough. (Especially the numbers circled)
Can I confirm that it **IS** a violation of the feature freeze if we were to fix it to make it more intuitive, for instance, showing "Quantity: 2" instead of just "2"? Rather, we should just be clarifying what the numbers mean in the UG? Thank you!

![image](https://user-images.githubusercontent.com/88267136/229823718-59e85d55-900f-4f8e-b467-128007b0e505.png)

**Comment by damithc** [comment]
@HmuuMyatMoe Making the UI more intuitive is an enhancement  -- not allowed in v1.4

**Comment by HmuuMyatMoe** [comment]
Thank you!
