### ISSUE TITLE
Is changes to input allowed

### ISSUE THREAD

**Issue by lyndonlim27** [nus-cs2103-AY2223S2/forum#327]
Hi. Currently, for one of my features, users can only enter in alphanumeric inputs. However, I would like to ask if we are allowed to change it such that users can enter in alphanumeric + whitespace or is this not allowed(due to feature freeze).

**Comment by damithc** [comment]
@lyndonlim27 Depends on the input field. If this restriction hinders typical use of the application, it can be fixed in v1.4. Otherwise  (i.e., users can work around this restriction) it should be left as a future enhancement.

**Comment by lyndonlim27** [comment]
Currently, it is just inconvenient for users as they have to concatenate text for e.g "CloseFriends" instead of "Close friends"

**Comment by damithc** [comment]
> Currently, it is just inconvenient for users as they have to concatenate text for e.g "CloseFriends" instead of "Close friend

In that case, should not be changed during the feature freeze.

**Comment by lyndonlim27** [comment]
Okay. Thank you prof!
