### ISSUE TITLE
Question regarding wrong error message displayed

### ISSUE THREAD

**Issue by gyulong1** [nus-cs2103-AY2223S2/forum#329]
Hi Prof, we have a typo in the error message that is displayed to our users where it says "more than one" instead of "one or more". However, the behaviour is described correctly in our User Guide. 

Would changing the error message be considered fixing a bug since a misleading error message is shown or a feature enhancement since normal user usage is not affected by the bug?

**Comment by damithc** [comment]
> we have a typo in the error message that is displayed to our users where it says "more than one" instead of "one or more".

@gyulong1 This is a bug, as the information shown is incorrect. Allowed to fix.

**Comment by gyulong1** [comment]
Thanks prof!
