### ISSUE TITLE
Changing error message

### ISSUE THREAD

**Issue by HmuuMyatMoe** [nus-cs2103-AY2223S2/forum#331]
May I confirm that the following can be considered a wrong error messages and is thus a bug that can be fixed?
(We initially intended for %s to be format specifiers, but somewhere in the code, we simply printed out the message with "%s" and forgot to use String.format to replace the %s)

![image](https://user-images.githubusercontent.com/88267136/229959453-37f43e7f-441b-4126-a2d3-1e9f1109b65e.png)
![image](https://user-images.githubusercontent.com/88267136/229960092-107097af-6ed3-456b-a6a8-f378e47b4c52.png)

**Comment by damithc** [comment]
@HmuuMyatMoe this output is clearly incorrect and can be fixed in v1.4

**Comment by HmuuMyatMoe** [comment]
Thank you!
