### ISSUE TITLE
Links in PDF output

### ISSUE THREAD

**Issue by immanuelhume** [nus-cs2103-AY2223S2/forum#332]
Some parts of the DG link to other parts of the website. For example, in the screenshot from AB3's docs below, the *Setting up and getting started* section is hosted as a separate page.

<img width="421" alt="image" src="https://user-images.githubusercontent.com/47441677/230005347-96607c27-d0d1-4e05-bfa3-11711314db20.png">

I would like to clarify:

1. In the final PDF, should these remain as hyperlinks to the docs webpage? Or should we "inline" these sections into the DG?
1. If the sections remain as hyperlinks, are mistakes in their content (on the web page) penalizable in PE?

**Comment by damithc** [comment]
@immanuelhume 

> * In the final PDF, should these remain as hyperlinks to the docs webpage? Or should we "inline" these sections into the DG?

They can remain as links to other pages.

> * If the sections remain as hyperlinks, are mistakes in their content (on the web page) penalizable in PE?

No. The PE scope is limited to the content of the UG and DG pdf files only.
