### ISSUE TITLE
EditCommand FeatureFlaw or Bug

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#333]
Hi Prof, when doing further testing on my work, I've encounter a bug and not sure if it would be classified as a featureFlaw.

When editing the 'patient', the patient must show up in the filtered list or else it would show that it cannot be found. It is not intended.

This is our [UG](https://github.com/AY2223S2-CS2103-F11-3/tp/blob/d69ba11cbd28baaf74d45260fb5d35fd86fc30c0/docs/UserGuide.md#edit---edit-a-patient) before the feature freeze.  It shows that the user can edit the patient using the ID and did not mention that the patient must show up in the filtered list.

I had to fix a [similar bug](https://github.com/AY2223S2-CS2103-F11-3/tp/issues/195) for a different related command but did not catch this bug before PE-D.

Would like to check if I am able to fix this BUG or file it under [planned enhancement](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/project.html#:~:text=Using%20%27Planned%20Enhancements%27%20DG%20section%20to%20counter%20known%20feature%20flaws)

**Comment by damithc** [comment]
@francisyzy what is the exact intended behavior and the actual behavior? Also give a screenshot of the relevant UG segment. You can PM me using MSTeams if you are uncomfortable sharing those details here.

**Comment by francisyzy** [comment]
Intended behaviour: would be the patient can be edited when the patient list is filtered (patient does not show up in the current view).

Actual behaviour: will throw a `CommandException` if the patient is not currently in the filtered list. `The patient index provided is invalid`

Intended:
<img width="727" alt="image" src="https://user-images.githubusercontent.com/24467184/230027251-69616fff-a161-4888-8c90-b4d368ba95d7.png">
Actual:
<img width="639" alt="image" src="https://user-images.githubusercontent.com/24467184/230027830-3c14f8ac-56a2-4645-b23f-d1d07b41c896.png">


Screenshot of the relevant UG section before feature freeze:
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/24467184/230026943-fd26efaf-a450-49a3-ad46-c773d3c275c0.png">

**Comment by damithc** [comment]
@francisyzy There is certainly something that needs fixing -- for one thing, UG says PATIENT_ID but the error message says patient index. Are they the same thing?

**Comment by francisyzy** [comment]
@damithc Thanks for catching the error message error. It should say PATIENT_ID instead of INDEX

**Comment by damithc** [comment]
@francisyzy If it is the patient ID, and the intended behavior is that even patients not in the currently visible list should be editable by specifying the patient ID, it is a bug that you can fix in v1.4

**Comment by francisyzy** [comment]
Thanks prof for the clarification!
