### ISSUE TITLE
Multiple warnings on terminal regarding mismatch in fxml versions

### ISSUE THREAD

**Issue by ryanchua00** [nus-cs2103-AY2223S2/forum#334]
Hi Profs, 

I'm unsure if this is a functionality bug. Whenever we start the application, we receive many warnings regarding mismatched JavaFX API version and JavaFX runtime version. This was flagged to us as a functionality bug during the PED. I feel like it isn't a feature flaw as there isn't a missing component or poor design at play here. Would we be allowed to fix it?

Thanks!

![image](https://user-images.githubusercontent.com/62086995/230095978-cc73ec84-60a5-4f35-b97c-cbab63f0a4b9.png)

**Comment by damithc** [comment]
@ryanchua00 Fixing warning messages in the console can be postponed for a future version, provided they are not too alarming to the user. We can consider it as a feature flaw, as the console output can be considered a user-visible feature.

**Comment by ryanchua00** [comment]
Thanks prof!
