### ISSUE TITLE
Smoke Testing TP for Linux 

### ISSUE THREAD

**Issue by angjunkang** [nus-cs2103-AY2223S2/forum#337]
Hi all, 

Could any Linux user help to conduct a smoke test on the JAR file for my tp? During the PE Dry Run, there were issues with the JavaFX's UI in the Linux environment with our JAR file. Unfortunately, as there are no Linux users within my team, we are unable to debug and test the application in question.

I would be grateful if anyone could provide any insights and testing for this issue. Preferably, the operating system used would be Arch Linux with KDE-Plasma version 5.27.3-1. However, any other Linux distro would be welcomed as well. Additionally, if there are any issues encountered during the testing process, it would be appreciated if screenshots could be provided for reference.

Thank you all in advance!

JAR File link: https://github.com/AY2223S2-CS2103-W16-3/tp/releases/tag/v1.3

**Comment by immanuelhume** [comment]
ur team's app looks fine on my laptop (arch, i3wm)

specifically what issues r u referring to?

<img width="963" alt="image" src="https://user-images.githubusercontent.com/47441677/230137231-7ffad960-d95e-4711-b248-5baa188dff90.png">

**Comment by angjunkang** [comment]
Hi @immanuelhume,
There was initially a problem with the UI but I did some changes so I need to check if it work now. Seems to be working from your screenshot except the fact that the command bar and result display box is a little small.

Thanks for helping me to test it! I appreciate it a lot! I'll leave this thread here to see if the UI is working on other Linux distro.

**Comment by hingen** [comment]
Hi, as the one that originally reported this issue during the PE-D, your fix works great.

![image](https://user-images.githubusercontent.com/31367001/230237376-8cab8682-fd3d-4f0f-8476-6a3c7a30e780.png)

**Comment by angjunkang** [comment]
Hi @hingen,

Thank you for testing and the insights you have shared through email!

With this, I'll close this thread now since it seems to be working for at least 2 people using Linux. Thanks all!

**Comment by Beebeeoii** [comment]
tested on Manjaro. looks okay!

![image](https://user-images.githubusercontent.com/55170539/230272532-ba2ff47d-f40d-406b-a7fd-e9522688a3b3.png)

**Comment by angjunkang** [comment]
Thank you @Beebeeoii! Appreciate it!
