### ISSUE TITLE
Checking for duplicate person is case sensitive

### ISSUE THREAD

**Issue by HmuuMyatMoe** [nus-cs2103-AY2223S2/forum#338]
When we checked for duplicate persons in our application, the search is case sensitive so `Amy` will not be considered to be the same person as `amy`. (We did not state in our error message or UG that the search is case sensitive)

Since people will most likely consider `Amy` and `amy` to be the same person, may we ask if this is a bug that we can fix (by making the search case insensitive so that `Amy` and `amy` will be considered duplicates? Thank you!

**Comment by damithc** [comment]
@HmuuMyatMoe the following FAQ applies here:

>Q7: Can we tweak case-sensitivity of a feature?
>
>A: If the case-sensitivity of a feature does not follow the real world, it is considered a feature flaw (i.e, the design of the feature is not optimal). The best you can do in v1.4 is to document this behavior clearly in the UG.
An exception is when the UG clearly states the case sensitivity but the actual feature implementation doesn't follow it, in which case it is a bug and can be fixed.

**Comment by HmuuMyatMoe** [comment]
Thank you prof!
