### ISSUE TITLE
Feature Freeze - Is fixing typos and incorrect commands in help messages allowed?

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#339]
![image](https://user-images.githubusercontent.com/92144641/230271535-007c14cb-1498-4157-a917-23a031b8a342.png)

Above, is the command success message of one of the functions in our app.
It mentions 'students' (which comes from an unchanged, early iteration) even though students are never mentioned in our User Guide.
The intended fix is to change all mentions of 'students' to 'athletes'. This is to prevent users from questioning what a 'student' means in the context of our app, as they were never mentioned.

Are updating these error messages allowed?

**Comment by damithc** [comment]
@Tempura-Person Yes, this can be fixed if it is _incorrect_ to mention students in this text.

**Comment by Tempura-Person** [comment]
thank you, noted.
