### ISSUE TITLE
Switch case Fallthrough comment

### ISSUE THREAD

**Issue by lhy-hoyin** [nus-cs2103-AY2223S2/forum#34]
In the [Java Coding Standard](https://se-education.org/guides/conventions/java/intermediate.html), under [Layout](https://se-education.org/guides/conventions/java/intermediate.html#layout) (switch case), it mentioned
> The explicit `//Fallthrough` comment should be included whenever there is a case statement without a break statement.

using the example of
```java
switch (condition) {
case ABC:
    statements;
    // Fallthrough
case DEF:
    statements;
    break;
...
}
```

Currently. in my code, im doing this
```java
switch (condition) {
case ABC:
case DEF:
    statements;
    break;
}
```

Is it really necessary for `//Fallthrough` when it is obviously falling through, since there are no statements between `case ABC:` and `case DEF:`?

**Comment by lhy-hoyin** [comment]
In case you are wondering why I have 2 cases without any statements in-between, I am currently doing this
```java
switch (currentState ) {
case MARK:
case UNMARK:
     ... ... // very similar code for mark and unmark

    if (currentState == State.MARK)
        System.out.println("Nice I've marked the task(s) as done:");
    else 
        System.out.println("OK, I've marked the task(s) as not done yet:");
    ... ... // very more similar code
}
```

**Comment by lhy-hoyin** [comment]
And to adhere to the coding styling, would it be alright for me to do 
``` java
case ABC: //Fallthrough
case DEF:
    ...
 ```
 instead of
``` java
case ABC: 
    //Fallthrough
case DEF:
    ...
 ```

**Comment by damithc** [comment]
> Currently. in my code, im doing this
> 
> ```java
> switch (condition) {
> case ABC:
> case DEF:
>     statements;
>     break;
> }
> ```
> 
> Is it really necessary for `//Fallthrough` when it is obviously falling through, since there are no statements between `case ABC:` and `case DEF:`?

@lhy-hoyin No need for this case as it is pretty clear there is a fall-through.

**Comment by markusyeo** [comment]
It is interesting case that we us Java 11 which has not yet implemented the enhanced switch features that is implemented from Java 12/13 onwards. The enhanced witch introduces the possibility of having multiple values for each case which will reduce the need for fallthrough between cases which we use prior.
