### ISSUE TITLE
Future design tweaks in PPP

### ISSUE THREAD

**Issue by kohkaixun** [nus-cs2103-AY2223S2/forum#340]
If I had already written the implementation for a bug that was flagged during the PE but was then informed that it would violate the feature freeze and it was not merged as a result, would it still be alright to include it in my PPP?

**Comment by damithc** [comment]
@kohkaixun Yes. Just mention that it wasn't merged and the reason for not merging.

**Comment by kohkaixun** [comment]
Alright, thank you Prof!
