### ISSUE TITLE
Is redefine constraint for user input allowed in v1.4?

### ISSUE THREAD

**Issue by Jiayan-Lim** [nus-cs2103-AY2223S2/forum#341]
Currently, in our software, we allow users to input numbers and special characters like (), +, - for phone numbers. But there is a bug where the user can input all special characters without any number
![image](https://user-images.githubusercontent.com/122262028/230315732-884060c8-4776-4966-bd54-f35c04179529.png)
Is this considered a feature flaw or bug?

**Comment by damithc** [comment]
@Jiayan-Lim It's a feature flaw.
In any case, it is arguable if this data field should be restricted to telephone numbers only or it is better to let users decide what they want to store in that field, without any restriction. In most cases the latter makes it more useful to the user e.g., `1234-2287 (or 88)` It's rather annoying when the user has a good reason for entering some 'unusual' data for a specific field but the application won't allow it.

**Comment by Jiayan-Lim** [comment]
Thanks prof for quick reply
