### ISSUE TITLE
Include implementation in planned enhancement

### ISSUE THREAD

**Issue by potty10** [nus-cs2103-AY2223S2/forum#342]
Should we include implementation in planned enhancement? 

For example, suppose we have a feature flaw and we want to write an enhancement to solve this problem, but we need to change a method in file A. Must we write how we intend to change this method and/or include screenshots of the planned change in code?

**Comment by damithc** [comment]
@potty10 It's optional. You can describe planned features if the description of the current features is not enough to showcase your DG writing skills.
