### ISSUE TITLE
Question on canvas submission of tP

### ISSUE THREAD

**Issue by glyfy** [nus-cs2103-AY2223S2/forum#343]
Can I check is it ok for one person to submit on behalf of the whole team on canvas. For the PPP, does he submit all group members md files?

**Comment by damithc** [comment]
@glyfy 

Group submissions: any member of the team can submit on behalf of the team.

> For the PPP, does he submit all group members md files?

It's a PDF submission. Each person must submit their own file.

**Comment by glyfy** [comment]
Ok thank you for the clarification prof!
