### ISSUE TITLE
Feature Flaw or Bug?

### ISSUE THREAD

**Issue by joytqt-1202** [nus-cs2103-AY2223S2/forum#344]
I have an unmark command that works for multiple objects as well as single events. 

Upon further testing, it was realised that the error output is not the same...

___For Single Events___
`unmark vid` on an already unmarked `vid` would let the user know that no changes were made because the video was already unmarked

___For Multiple Events___
`unmark vid1, vid2` when `vid1` or `vid2` or both are already unmarked would tell the user that the command was **successful** (which technically is not wrong)

___For its opposite command `mark`___
`mark vid` and `mark vid1, vid2` will let the user know that the videos were already marked

*Question* 
Is the issue for `unmark` on multiple events considered a feature flaw or a bug? 
Can I fix it in this iteration?

Thanks!

**Comment by damithc** [comment]
@joytqt-1202 As the current behavior is not incorrect (although can be fine tuned further), this is not a bug allowed to fix during the feature freeze.

**Comment by joytqt-1202** [comment]
okay! thank you!
