### ISSUE TITLE
Bug or Feature Flaw that causes other features to malfunction

### ISSUE THREAD

**Issue by Bentimate** [nus-cs2103-AY2223S2/forum#347]
Currently, our TP's delete command supports deletion of multiple index at once, and an undo command which allows users to undo the previous command.

correct case:
![good](https://user-images.githubusercontent.com/81696093/230634070-f71e9c59-baca-4a46-9c97-3c308b924928.JPG)

However, we have a problem where if the user enters duplicated index, the program will take the first index it sees and deletes it, but the command output box will not be cleared. This is due to not accounting for duplicates in the code.
wrong case:
![bad](https://user-images.githubusercontent.com/81696093/230634370-f6273e21-1752-489c-a3cf-72865d0fbf17.JPG)

This also causes the undo command to break and unable to be used properly.

This seems like a feature flaw, but this also causes other features to malfunction. Can this then be treated as a bug, or can we only mention this in the planned enhancement?

Here are some possible fixes, unsure if they are allowed:
1. Throw new error messages to disallow duplicate index
2. Allow duplicate index, but command output will be changed

**Comment by damithc** [comment]
@Bentimate The current behavior for `delete 1 1` seems to be incorrect. Either of the proposed fixes can be allowed.

**Comment by Bentimate** [comment]
Thanks prof!
