### ISSUE TITLE
PPP Deadline

### ISSUE THREAD

**Issue by 4ndrelim** [nus-cs2103-AY2223S2/forum#348]
> This task is time-sensitive. If done later than the [deadline](https://nus-cs2103-ay2223s2.github.io/website/admin/weeklySchedule.html#:~:text=for%20exact%20dates.-,Deadline%20for%20weekly%20tasks,-The%20soft%20deadline), it will not be counted as 'done' (i.e., no grace period). Reason: This is 'an early draft'; if done late, it is the 'final version' already.

I did not notice the deadline for drafting the PPP. I'm wondering if there is any penalty for missing the draft or can it be compensated with the final version?

**Comment by damithc** [comment]
@4ndrelim Missing a few tP deliverables will not affect marks, unless you miss many.

**Comment by 4ndrelim** [comment]
thank you
