### ISSUE TITLE
Clarification on Weekly Quiz Early Submission Deadline

### ISSUE THREAD

**Issue by cyiting** [nus-cs2103-AY2223S2/forum#35]
Hi, from what I know, the course website states that the early submission deadline is within 4 days of the lecture i.e on Monday. 

I submitted the week 2 lecture quiz on Monday this week. But the participation dashboard reflects that I did not do so within the early-submission window. Can I just clarify when the deadline is again?

**Comment by damithc** [comment]
Good catch @cyiting 
I found that it was a bug, due to a difference in the way Canvas and LumiNUS report the submission times.
I've fixed the bug and updated the dashboard accordingly.
