### ISSUE TITLE
Anyone tried to do GUI tests and encountered Illegal Reflective access errors

### ISSUE THREAD

**Issue by seanfirefox** [nus-cs2103-AY2223S2/forum#350]
I attempted to use the GUI tests from [AB4](https://github.com/se-edu/addressbook-level4) and encountered illegal reflective access errors, presumably from [testfx](https://github.com/TestFX/TestFX/issues/553).

![image](https://user-images.githubusercontent.com/35872524/230708539-5fe4660e-9abf-4a2f-ac48-c72aa4de02c1.png)

Anyone knows a workaround it? I have tried to set in `build.gradle` to allow this to pass but without any success.

```
test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    systemProperties = [
            'testfx.robot': 'glass',
            'testfx.headless': 'true',
            'prism.order': 'sw',
            'prism.text': 't2k',
    ]
    jvmArgs = [
            '--add-opens', 'javafx.graphics/javafx.scene=ALL-UNNAMED',
            '--add-opens', 'javafx.controls/javafx.scene.control=ALL-UNNAMED'
    ]
}
```

**Comment by seanfirefox** [comment]
Never mind, I have resolved it by upgrading all `testfx` and `monocle` dependencies to the latest versions.

**Comment by damithc** [comment]
> Never mind, I have resolved it by upgrading all `testfx` and `monocle` dependencies to the latest versions.

Thanks for sharing this, @seanfirefox Could be useful to others attempting to use TestFx.

**Comment by seanfirefox** [comment]
Just for more sharing, I used testFxVersion `4.0.16-alpha` and used the `monocle` version below.
```
testImplementation group: 'org.testfx', name: 'openjfx-monocle', version: 'jdk-12.0.1+2'
```

Also ended up with the below code for my `build.gradle`.
```
test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
    jvmArgs "-Dheadless=${project.hasProperty('headless') ? project.headless : false}"
    systemProperties = [
            'testfx.robot': 'glass',
            'testfx.headless': 'true',
            'prism.order': 'sw',
            'prism.text': 't2k',
    ]
}
```
