### ISSUE TITLE
Is refactoring allowed in v1.4?

### ISSUE THREAD

**Issue by valerietanhx** [nus-cs2103-AY2223S2/forum#351]
Hi! My team is looking to refactor a part of our code to improve readability on our end. There will be no change in features on the user side; the refactoring only changes the path taken by user input internally. Would this be acceptable for v1.4? My thinking is that it falls under code quality, so it shouldn't be an issue, but wanted to make sure!

**Comment by damithc** [comment]
@valerietanhx That is certainly allowed (more info [here](https://nus-cs2103-ay2223s2.github.io/website/schedule/week12/project.html#:~:text=Allowed%20in%20the%20v1.4%20milestone))

**Comment by valerietanhx** [comment]
Alright, thank you!! :)
