### ISSUE TITLE
Difference between submission of v1.4 and wrapping up milestone

### ISSUE THREAD

**Issue by swxk19** [nus-cs2103-AY2223S2/forum#352]
Submission of v1.4 is on 10/4 but wrapping up the milestone for v1.4 is on 12/4. May I understand what's the difference between these 2 deadlines? Why is completing the milestone after the submission and what kinds of changes are we allowed to do after the submission on 10/4?

**Comment by damithc** [comment]
@swxk19 The extra time is for doing any leftover housekeeping on the Github e.g., close issues/PRs, close milestone
