### ISSUE TITLE
Question about omitting methods in sequence diagram

### ISSUE THREAD

**Issue by swxk19** [nus-cs2103-AY2223S2/forum#353]
Say I have the following scenario of nested calls where `one()` calls `two()` which calls `three()` which calls `four()`
<img width="135" alt="image" src="https://user-images.githubusercontent.com/45385178/230737034-76c77285-2df2-4011-baf0-909ef893d674.png">

but in my particular scenario, i only want to show `one()` and `four()`, as `two()` and `three()` are irrelevant and doesn't add much value in this specific scenario. Would it then be acceptable to show the diagram as this? :
<img width="121" alt="image" src="https://user-images.githubusercontent.com/45385178/230737149-f3361dc0-38d6-49c6-a7db-640a0fce358b.png">

**Comment by damithc** [comment]
@swxk19 Yes, it is fine, provided the omission doesn't detract from the purpose of the diagram. Typically, the purpose of SDs is to show notable interactions _between_ entities; omitting less important self-calls does not detract from that purpose.
