### ISSUE TITLE
Question about referencing code reuse (Follow-up from #350)

### ISSUE THREAD

**Issue by seanfirefox** [nus-cs2103-AY2223S2/forum#354]
I have copied and edited over multiple files from [AB4](https://github.com/se-edu/addressbook-level4) for GUI tests. Other than referencing `AB4` in the `DG`, `index.md` and declaring in the Canvas survey, I have also added it in the `JavaDocs` as shown below.

Is this enough referencing? 
![image](https://user-images.githubusercontent.com/35872524/230740456-6cc2f53f-1718-4db7-a670-c8853afbd78e.png)

**Comment by damithc** [comment]
@seanfirefox You should also use `@@author seanfirefox-reused` tags to mark code reused without any substantial changes. More info https://nus-cs2103-ay2223s2.github.io/website/admin/tools.html#tool-reposense-for-authorship-tracking

For code reused with substantial changes, you can cite the source (as in your screenshot) and also make a brief note of how the code you changed code

**Comment by seanfirefox** [comment]
Thanks for the clarification!
