### ISSUE TITLE
Declaration of code reuse in Canvas Quiz

### ISSUE THREAD

**Issue by seanfirefox** [nus-cs2103-AY2223S2/forum#357]
Asking for my teammates about the declaration of code reuse:

I have reused code from AB4, so I checked the option for 
```
I reused some content and gave credit to the original source in all cases of such reuse, as required by the module policies.
```
However, my teammates did not reuse code, so do they still check the option above?

Also, does using external libraries like `Joda-Time` consider as reused code as well such that the above option needs to be checked?

**Comment by damithc** [comment]
@seanfirefox The reuse declaration (in Canvas) applies to code that is attributed to each person. If AB4 code that was reused was not attributed (in the code dashboard) to other team members, they are not considered as reusing AB4 code.

Yes, using 3rd party libraries is considered as reuse in this context.

**Comment by seanfirefox** [comment]
@damithc Prof, so for using 3rd party libraries, is it everyone who uses an object from it needs to declare reuse or only the person who imports it needs to declare reuse in Canvas?

**Comment by damithc** [comment]
> @damithc Prof, so for using 3rd party libraries, is it everyone who uses an object from it needs to declare reuse or only the person who imports it needs to declare reuse in Canvas?

Everyone who uses the said library in their code.

**Comment by seanfirefox** [comment]
Thanks for the clarification.
