### ISSUE TITLE
Naming Conventions for Files

### ISSUE THREAD

**Issue by eugenetangkj** [nus-cs2103-AY2223S2/forum#361]
Hello! I have resubmitted a file on Canvas for my PPP, but I think Canvas automatically adds a version number at the end. For example, my file name was in the format of `[TEAM_ID][Your full Name as Given in Canvas]PPP`, but after reuploading the file, the name of the file shown on Canvas became `[TEAM_ID][Your full Name as Given in Canvas]PPP-1`.

May I check if there is any action required on my side to circumvent this issue? Thank you!

**Comment by damithc** [comment]
@eugenetangkj It should be fine. We'll work our way around such auto-added suffixes.

**Comment by eugenetangkj** [comment]
Okay, thanks for the reply Prof! Appreciate it.
