### ISSUE TITLE
Planned enhancement for more than 1 feature with the same flaw

### ISSUE THREAD

**Issue by HmuuMyatMoe** [nus-cs2103-AY2223S2/forum#362]
If we have, for instance, 2 different features (add task with deadline, add person with phone number) with the same flaw,

e.g., Our validity checks for the parameters of these different add commands are not very comprehensive (e.g., when checking for deadline, we allow deadlines like `01/01/1000` and when checking for phone numbers, we allow phone numbers to be more than 8 digits like `911111111111111`)

So, our planned enhancement for both of these feature flaws would be to improve the validity checks. 
When we write about this enhancement in the planned enhancement section, are we allowed to combine them together as one enhancement (Making all the validity checks more comprehensive)? 
Or, would they be considered 2 different enhancements (one being improving validity check for deadlines, and another being improving validity check for phone numbers)? Thank you!

**Comment by damithc** [comment]
For this case, we can follow the same logic we follow when determining duplicate bugs. If each _can_ be fixed independently of the other, they are considered two distinct enhancements. But if fixing one automatically fixes the other, they are considered the same issue, and can be counted as one.

As for validation, consider if stringent validity checks are really necessary. A user might want to record something like `1234 5678 (or 9)` as a telephone number in some contexts (depends on the application though) and it would be annoying if the application stops the user from doing so -- one can interpret that as the application designers not being able to anticipate user needs fully.

**Comment by HmuuMyatMoe** [comment]
Thank you prof!
