### ISSUE TITLE
Am I able to change my response for Canvas tP code reuse declaration survey

### ISSUE THREAD

**Issue by toh-xinyi** [nus-cs2103-AY2223S2/forum#363]
I selected the wrong option and submitted the survey... Is there any way for my to change my selected option

**Comment by damithc** [comment]
@toh-xinyi I've tweaked Canvas settings. You should be able to submit it again. Canvas surveys doesn't have an 'edit' feature, so, resubmitting is the only option.

**Comment by toh-xinyi** [comment]
Thank you prof!
