### ISSUE TITLE
Changing sample data as it is not in line with our product

### ISSUE THREAD

**Issue by toh-xinyi** [nus-cs2103-AY2223S2/forum#366]
In #303, it is stated we are only allowed to change if there are errors in the sample data,
But, are we able to change it if there are no exact errors but the tags in the sample data does not match our product at the moment? Are we able to just change the tags to match with our product as it might be misleading to users? e.g. current tags: 'friends' and 'colleagues' but our application is for keeping track of a tutor's students, so we would like to change the tags to 'primary', 'secondary', etc.

**Comment by damithc** [comment]
@toh-xinyi I think it is best to list it under planned enhancements instead, as it is not technically 'incorrect' (it is simply tweaking the sample data to better match the application i.e., an enhancement)

**Comment by toh-xinyi** [comment]
@damithc Noted, thank you prof!
