### ISSUE TITLE
.jar file follow the naming convention, cannot open without using ' '

### ISSUE THREAD

**Issue by CarrieLi1015** [nus-cs2103-AY2223S2/forum#367]
We just found out that for mac, if following in the school naming convention, like [CS2103][name].jar. The file cannot be opened.

For example, java -jar [CS2103][name].jar could not open the .jar file. One way to open it is using java -jar '[CS2103][name].jar', another is to use java -jar *.jar

Since we are not sure if it is cause by zsh set up or it is a general issue for all mac users. May we ask if we will be penalised by this? As we did not specific it inside UG and for those who does not know this might not be able to open our .jar file.

Or is it possible to make an announcement that for mac user, need to wrap the .jar file name with ' ' or use *.jar in order to open it?

**Comment by damithc** [comment]
@CarrieLi1015 hmm... we used the same naming convention in previous PEs but this issue did not come up. 

Other Mac users, are you facing similar problems?

**Comment by angjunkang** [comment]
I have similar issues on my mac as well. My guess is this might be due to the square brackets in the jar file.

**Comment by CarrieLi1015** [comment]
Hi prof, we just checked our file with a few other mac users. Some of them can open without using ' ', some of them cannot. We are not sure whether it is due to different mac model (so different shell version, I think zsh will have problem but bash will not [Terminal version](https://support.apple.com/en-us/HT208050)).

<img width="1106" alt="Screenshot 2023-04-11 at 3 10 43 PM" src="https://user-images.githubusercontent.com/97392685/231084364-fa84a7e4-a503-4a14-b438-ee3172ef21ee.png">
name wrap inside ' ' can work.
<img width="894" alt="Screenshot 2023-04-11 at 3 12 14 PM" src="https://user-images.githubusercontent.com/97392685/231084479-a3e9ba5b-21c6-42cc-b82a-6cb8649e0698.png">
After remove the square bracket can work, might because square bracket is Regex expression in Unix?

**Comment by damithc** [comment]
@CarrieLi1015 I've updated PE instructions to encourage everyone to use double quotes around the jar file name, as follows:

![image](https://user-images.githubusercontent.com/1673303/231467325-939fa31f-e8d6-4910-9466-1fb199fafbef.png)

To confirm, the above works in your shell, right?

**Comment by CarrieLi1015** [comment]
> @CarrieLi1015 I've updated PE instructions to encourage everyone to use double quotes around the jar file name, as follows:
> 
> ![image](https://user-images.githubusercontent.com/1673303/231467325-939fa31f-e8d6-4910-9466-1fb199fafbef.png)
> 
> To confirm, the above works in your shell, right?

Yes it works on my shell. Thank you prof!
