### ISSUE TITLE
Canvas demo video submission has no name

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#369]
The video file that i uploaded was named `[CS2103T-W12-2][TeachMeSenpai].mp4`. But after uploading, it's name was stripped from the Canvas assignment page.

There doesn't seem to be any way to add a name on the `tP Demo Video` Canvas assignment.

Is that ok?

![image](https://user-images.githubusercontent.com/35413456/231221343-d55ea327-7fd5-4d8f-baf5-8b57c992f7ad.png)

This is what it looks like when i click `Submission details`:

![image](https://user-images.githubusercontent.com/35413456/231222233-86c7c46b-b84d-4a98-a448-8c6bfda94e74.png)

**Comment by damithc** [comment]
@EvitanRelta it's fine; we can rename the file as necessary.
