### ISSUE TITLE
Force-pushing existing tags (Sourcetree)

### ISSUE THREAD

**Issue by axmszr** [nus-cs2103-AY2223S2/forum#37]
Hello! I've been having a couple issues with pushing existing tags to my remote (GitHub) repo when I've re-assigned them to a newer commit:
![image](https://user-images.githubusercontent.com/72402917/213848361-5b201cf4-e9b4-4566-b2bc-f06b0f8f81ca.png)
![image](https://user-images.githubusercontent.com/72402917/213848391-996ea119-6f80-47d5-bdfc-1d1282f6eab5.png)

I understand that it doesn't like pushing such 'moved' tags, and it works perfectly fine when I force push via the terminal with something like `git push origin -f Temp-Test`.

However, when I try enabling Force Push on Sourcetree (with Safe Force Push `--force-with-lease`) in order to automatically push these tags, I run into this issue:
![image](https://user-images.githubusercontent.com/72402917/213848593-6476624b-f917-4b30-9c3b-7293679ab54c.png)

Turning off the "Use Safe Force Push" option fixes this, and I plan to keep my settings this way for the time being:
![image](https://user-images.githubusercontent.com/72402917/213848666-0f28980a-932c-48e8-b30b-c3b476b77f7d.png)

Could I ask if this is safe, or if it is bad practice? I'm not sure what complications this may lead to in tP or more complex projects, and stackoverflow isn't really giving me advice I understand :P

Thank you!

**Comment by hingen** [comment]
Just speaking from past school project experience.

Is force push bad? Personally don't think so but there's a time and place for it and it should be used with caution. Force push allows you to overwrite the git history on the remote. If not careful, you could:
* cause your teammates local repo history to become out of sync with the remote (this can usually be remedied with proper application of the merge command on your teammates side provided they are familiar with how to fix it as it can be pretty complicated depending on what history you overwrote)
* overwrite and delete your teammates commits, especially if you force push a commit to a branch multiple devs are working on (e.g. merge commit to master branch)

Should you force push every single one of your commits?
* If you're the only one working on the repo, probably fine but you risk accidentally deleting commits and it's also not good practice (the overwritten commits are usually still accessible on your local repo as commits that belong to no branch)
* If you're working on a repo with a team, 100% not for the second negative implication stated above

**Comment by Junyi00** [comment]
I faced a similar issue. However to avoid any form of _force pushing_, I deleted the tags both remotely and locally, recreate it with the right commit and push the new tag.

While it essentially produces the same result if done carefully, I prefer the safer (while more troublesome) route as to avoid any potential side effect of force pushing anything at all.

**Comment by axmszr** [comment]
Thank you @hingen for the information; I'll definitely keep that in mind moving forward! Fortunately I haven't run into issues with git history or deleted commits yet in the iP, but I'll likely avoid force-pushing altogether for the upcoming tP.
And thanks @Junyi00 for the suggestion! I will follow that safer route if there is any risk involved.
