### ISSUE TITLE
PE Readiness Quiz result

### ISSUE THREAD

**Issue by tyx021** [nus-cs2103-AY2223S2/forum#370]
Hi, I noticed that it was mentioned in the quiz:

> "Please ensure you know the correct answer to every question in this quiz."

However, after I have submitted the quiz, canvas is showing neither the correct answer / how many questions I got it right. How am I supposed to know "I know the correct answer" before PE since the canvas quiz is due on the day of PE?

**Comment by damithc** [comment]
@tyx021 it was set to show answers, but Canvas being Canvas, there was another obscure setting that prevented the results from being shown. Should be OK now. Please try again and let me if you still can't see the answers.

**Comment by tyx021** [comment]
I can see the answer now :)
