### ISSUE TITLE
CS2103 disappeared from canvas

### ISSUE THREAD

**Issue by ZhuLeYao** [nus-cs2103-AY2223S2/forum#371]
How do we submit tp video or is this a glitch on canvas' side?

**Comment by damithc** [comment]
@ZhuLeYao NUS IT says Canvas issue should be fixed by noon today. If the issue is not fixed at least a few hours before the demo submission deadline, we will extend the deadline. For now, prepare the demo video and be ready to submit it when Canvas come online again.

**Comment by damithc** [comment]
@ZhuLeYao OK now? NUS IT says Canvas is back to normal now.

**Comment by ZhuLeYao** [comment]
Yes, the submission is successful. Thank you
