### ISSUE TITLE
Cannot see answer for readiness quiz

### ISSUE THREAD

**Issue by SHni99** [nus-cs2103-AY2223S2/forum#372]
![image](https://user-images.githubusercontent.com/96757889/231538942-ff588e0d-7e88-4c99-9ad4-fc8941750659.png)

Mentioned that the answers will be shown after I have submitted the quiz but turned out otherwise.

**Comment by damithc** [comment]
@SHni99 I tweaked the Canvas settings to show answers but looks like it doesn't apply to earlier submission. Perhaps you can do another empty submission and see if it shows you the answers now?

**Comment by SHni99** [comment]
Hi prof, I have submitted another one and is able to see the answers. Thank you.
