### ISSUE TITLE
Made a typo in PPP

### ISSUE THREAD

**Issue by Douglch** [nus-cs2103-AY2223S2/forum#373]
Hello Profs, I just realised I made a typo on my PPP where I wrote `edit` instead of `update` in the Update section as well as the `find` part which does not exist in the Managing Clients section and in other sections, written by my groupmates instead. Is there any additional steps I need to take in terms of notifying someone?
![image](https://user-images.githubusercontent.com/48470532/231628286-d8ada3ba-e663-4922-a10f-80876f356ea4.png)

**Comment by damithc** [comment]
@Douglch I have taken note. You can inform your team members about this, as they look at the PPP when submitting peer evaluations. Do update the online version of the PPP. There is no need to resubmit the PPP PDF though.

**Comment by Douglch** [comment]
Noted, thank you!
