### ISSUE TITLE
Bug if PlantUML notations used in diagrams?

### ISSUE THREAD

**Issue by toh-xinyi** [nus-cs2103-AY2223S2/forum#377]
Is it a bug if PlantUML notations are used in UML diagrams which are different from what we were taught in class?

For instance, private attributes of a class would typically be noted by a `-` as taught in class but private attributes in PlantUML would be shown as blank red boxes:
![image](https://user-images.githubusercontent.com/121878184/232190613-8c44bfd7-3f2c-41f6-9708-7a5f3feb1675.png)

Related to issue #411 and #2390

**Comment by damithc** [comment]
@toh-xinyi Doesn't the AB3 DG use PlantUML too but follow the standard notation for member visibility?

**Comment by toh-xinyi** [comment]
@damithc Oh, I can't seem to find any examples in AB3's DG that shows the visibility of attributes in the UML diagrams

**Comment by damithc** [comment]
@toh-xinyi Good point. Nevertheless, it can be done, which means a deviation is not justifiable.

e.g., https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/designPatterns.html#singleton-pattern

![image](https://user-images.githubusercontent.com/1673303/232196132-25371e0f-0aaf-47bb-86ae-5d2bf60b33d7.png)

**Comment by toh-xinyi** [comment]
@damithc Okay, noted. Thank you for your help prof!

**Comment by toh-xinyi** [comment]
@damithc Also, would this be a `severity.High` bug? Our tester reported it as high but I feel it would be a `severity.Low` bug since it would not hinder the reader to a large extent.

**Comment by damithc** [comment]
@toh-xinyi You can choose the severity based on how much the bug is expected to affect the reader, which depends on how important the visibility symbols are for the purpose of those diagrams.
