### ISSUE TITLE
Is "diagram too small" bug on multiple different diagrams considered duplicates?

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#378]
Or is it because "fixing 1 doesn't fix another", so they aren't duplicates?

**Comment by damithc** [comment]
> Or is it because "fixing 1 doesn't fix another", so they aren't duplicates?

Yes, they are not duplicates. If there is a high number e.g., 5+, you can request permission to combine them, but with a higher severity.
