### ISSUE TITLE
Gradle and I/O testing

### ISSUE THREAD

**Issue by LeonardYam** [nus-cs2103-AY2223S2/forum#38]
#36 Related to this

Hi all 

As my code relies on an external library, I wanted to check if it is acceptable to use Gradle to manage dependencies. (since it seems to be the suggested best practice over adding external .jar files)

In addition, using Gradle means that I am unable to use javac for the automated I/O test. Thus, I wish to clarify if the following script is also acceptable.

```
# Removing previous test output ...

# Uses gradle shadowJar to build
cd ..
./gradlew clean shadowJar
if ! [ -d "./build" ]
then
    echo "********** BUILD FAILURE **********"
    exit 1
fi

# Go back to test directory
cd text-ui-test
# run the program, feed commands from input.txt file and redirect the output to the ACTUAL.TXT
java -cp "../build/libs/ip-1.0-SNAPSHOT-all.jar:../build/classes/java/main" Main < input.txt > ACTUAL.TXT

# Comparing input and ouput files ...
```

**Comment by damithc** [comment]
@LeonardYam Adopting Gradle is one of the iP deliverables for this week. Yes, you may tweak the testing script accordingly.

**Comment by LeonardYam** [comment]
Alright, thanks Prof!
