### ISSUE TITLE
Bug stating that Adobe Acrobat cannot view DG properly

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#381]
Apparently, Adobe Acrobat has a limit of 200 x 200 inch per page _(which users have been complaining about for years_).  
However, <ins>all modern browsers</ins> can open such PDFs just fine.

As such, a tester has stated that our DG has problems viewing in Adobe Acrobat, because our UG/DG are single-page, long-scrolling PDFs. This intentionally was done because otherwise our diagrams would get broken up by page breaks.

And unlike stating that "`Java 11` is required for the app", we cannot simply state that "Viewing of our UG/DG is not supported by Adobe Acrobat" because that would require the user to be able to open it in the first place.

Should we `Accept`, `Reject` or `notInScope` this bug report?

**Comment by damithc** [comment]
@EvitanRelta The current approach of non-paginated PDF format is not ideal. You have mentioned one drawback of that already. Another is that it is not print-friendly. So, it should not be `Reject`, as the bug report has merit.

**Comment by EvitanRelta** [comment]
@damithc I presume it shouldn't be `NotInScope` too? Also, what severity do you recommend this to be?

**Comment by damithc** [comment]
@EvitanRelta We try not to recommend a specific type/severity/response to a specific bug report, as accuracy of bug triaging is graded. But in some 'unusual' cases (like this one) we can help to narrow down the options a bit (as I did above).

Nevertheless, you are welcome to raise such cases here and others are welcome to chime in with their opinions, as there is learning value in discussing such cases.
