### ISSUE TITLE
Calculation of accuracy

### ISSUE THREAD

**Issue by potty10** [nus-cs2103-AY2223S2/forum#383]
As the dev team, suppose the tester and us disagree on bug A. However, the tutor decided that the tester is correct. Will our accuracy score be adversely affected?

**Comment by damithc** [comment]
> As the dev team, suppose the tester and us disagree on bug A. However, the tutor decided that the tester is correct. Will our accuracy score be adversely affected?

@potty10 Yes, that's right (because your decision for that bug was found to be incorrect).
