### ISSUE TITLE
Textbook TOC not rending correctly on Mac render engine 

### ISSUE THREAD

**Issue by francisyzy** [nus-cs2103-AY2223S2/forum#384]
As seen in the screenshot, the left side renders properly on Firefox, right side is safari which does not render properly and the bottom is Preview, Mac built in PDF reader. The rest of the pages render properly, just the TOC being funny.

severity.Low because there is workaround.

<img width="1800" alt="Screenshot 2023-04-17 at 5 22 48 PM" src="https://user-images.githubusercontent.com/24467184/232443663-b015a981-6889-4024-9fe7-b5fd8425c53e.png">

**Comment by damithc** [comment]
@francisyzy Thanks for reporting this. I'm afraid we don't have a solution for this at the moment though :-(

**Comment by francisyzy** [comment]
Resaving the PDF using Firefox print menu helps fix the render.

[Textbook.pdf](https://github.com/nus-cs2103-AY2223S2/forum/files/11252467/Textbook.pdf)
<img width="1800" alt="Screenshot 2023-04-17 at 11 27 54 PM" src="https://user-images.githubusercontent.com/24467184/232535910-bd925a34-e7f3-415a-ad9d-694f887079b8.png">

**Comment by damithc** [comment]
> Resaving the PDF using Firefox print menu helps fix the render.
> 
> [Textbook.pdf](https://github.com/nus-cs2103-AY2223S2/forum/files/11252467/Textbook.pdf)

Ah, that's good to know. Thanks for sharing the solution/file @francisyzy
