### ISSUE TITLE
What to do if dev team is bargining for their bugs

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#388]
If the dev team I reviewed is very unreasonably dropping the severity or rejecting almost all of their bugs, can I report them?

**Comment by damithc** [comment]
@EvitanRelta There is no need to do that directly. Instead, you can object to the unreasonable decisions and explain why the team's position is unreasonable (or yours is more reasonable). If the teaching team agrees with you, your view of the bug will be chosen as the final state of the bug, and the bug assignee's accuracy level (and marks) will suffer. 
In the last phase of the PE, the teaching team will flag students who were unreasonable as either testers or developers.
