### ISSUE TITLE
Accuracy for PE

### ISSUE THREAD

**Issue by eugenetangkj** [nus-cs2103-AY2223S2/forum#389]
Hello there! May I ask a question regarding how accuracy marks are calculated in the PE? If the `severity` level that I have chosen coincides with what the dev team agrees with, but they stated that it is a `NotInScope`, would I be awarded the accuracy marks for correctly identifying the existence of such an issue? Thank you!

**Comment by damithc** [comment]
@eugenetangkj Yes.

**Comment by eugenetangkj** [comment]
Alright, thanks Prof for your help!
