### ISSUE TITLE
Broken link bugs considered independent bugs?

### ISSUE THREAD

**Issue by toh-xinyi** [nus-cs2103-AY2223S2/forum#392]
If there are multiple broken links all which are different, are they considered duplicates? 

According to [bug triaging guidelines](https://nus-cs2103-ay2223s2.github.io/website/admin/tp-pe.html#guidelines-for-bug-triaging-2), these would not be considered duplicates since technically they can only be fixable independently.

However, they are all related to the same type of bug as well, so would they be duplicates?

![image.png](https://raw.githubusercontent.com/toh-xinyi/pe/main/files/57b93d4a-5e45-43da-9fea-01c35094e273.png)

**Comment by gremmyz** [comment]
I don't think they would be considered duplicates as they are fixable independently. If there are many (>5 I think?) of these bugs reported in different places and the team wants to consider them as duplicates, they'll need to email Prof. @damithc to get approval to combine these bugs as a duplicate. After approval, it should be stated in **all** of the duplicates that there was approval to get the bugs combined.

**Comment by damithc** [comment]
> I don't think they would be considered duplicates as they are fixable independently. If there are many (>5 I think?) of these bugs reported in different places and the team wants to consider them as duplicates, they'll need to email Prof. @damithc to get approval to combine these bugs as a duplicate. After approval, it should be stated in **all** of the duplicates that there was approval to get the bugs combined.

That's correct. thanks @gremmyz

**Comment by toh-xinyi** [comment]
@gremmyz Thank you!
