### ISSUE TITLE
Broken link in Textbook

### ISSUE THREAD

**Issue by Beebeeoii** [nus-cs2103-AY2223S2/forum#394]
To reproduce:
1. Navigate to the [refactoring section of the textbook](https://nus-cs2103-ay2223s2.github.io/website/book/refactoring/how/)
2. Click on [10. Split Temporary Variable](https://refactoring.com/catalog/splitTemporaryVariable.html)

I think the link has been changed to https://refactoring.com/catalog/splitVariable.html instead

**Comment by damithc** [comment]
Thanks for the bug report, @Beebeeoii 
I've fixed it in the Module website and in the PDF file.
