### ISSUE TITLE
What does entry/exit coverage measure?

### ISSUE THREAD

**Issue by hingen** [nus-cs2103-AY2223S2/forum#398]
In the [textbook](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/testing.html#test-coverage), it is mentioned that:

> Entry/exit coverage measures coverage in terms of possible calls to and exits from the operations in the SUT.

I'm a bit confuse with what it measures exactly.

Suppose we are testing a method. By "calls to", is it referring to every possible combination of input arguments? And by "exits from", is it referring to every possible return value?

**Comment by damithc** [comment]
@hingen 
_Entry points_ refer to all places from which the method is called from the rest of the code i.e., all places where the control is handed over to the method in concern.
_Exit points_ refer to points at which the control is returned to the caller e.g., return statements, throwing of exceptions

**Comment by hingen** [comment]
I see, thanks prof!
