### ISSUE TITLE
Module Website Search Function

### ISSUE THREAD

**Issue by muhammadreyaaz** [nus-cs2103-AY2223S2/forum#399]
While using the website for revision, I often use the search function. However, I have noticed that the search function only searches for the closest word and not the exact keyword I am looking for. For instance, when I searched for the keyword `forum`, only the search results for `for` popped up. Consequently, I have to manually scroll through the contents to find the information I need. I am not sure if I am using the search function incorrectly, but I do not believe this to be the case. What do you guys think?

**Comment by damithc** [comment]
@ARPspoofing Indeed the keyword `forum` seems to search for `for` instead -- but if you search for `discussion forum`, it seems to work fine. 
perhaps an optimization misfiring on Algolia side (the search service provider we use)? 🤔

**Comment by muhammadreyaaz** [comment]
Ok thanks so much @damithc. I guess I shall workaround with some keywords for now.
