### ISSUE TITLE
The output path is not specified for module ip

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#4]
Hi all, I got this error when trying to run Duke.java on intelliJ "The output path is not specified for module ip". Im not sure what should be set for the compiler output path?

**Comment by glozxi** [comment]
I think the compiler output path is the `out` folder of the project folder `ip`. You can set it in `File > Project Structure > Project > Compiler output`.

**Comment by seadragon2000341** [comment]
yep but Im not too sure which file I should set to?

**Comment by damithc** [comment]
Perhaps someone can share a screenshot of the relevant Intellij settings?

**Comment by glozxi** [comment]
My setting:
![2023-01-14 20_27_19-Project Structure](https://user-images.githubusercontent.com/82697998/212471592-7bbee3f4-8a93-4e4f-b38d-6131119b5fb9.png)

**Comment by damithc** [comment]
@seadragon2000341 Is the issue resolved? If so, you can close this issue. If no, post more details so that others can follow up.
