### ISSUE TITLE
Associations that are not explicitly mentioned in the question

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#401]
<img width="1211" alt="Screenshot 2023-04-21 at 11 26 06 AM" src="https://user-images.githubusercontent.com/76247607/233533886-300eca06-fe32-4cbe-ae01-aa03ed95e535.png">

In this question, it was mentioned that `ActionFactory` adds `ActionX` and `ActionY` into `History`, is it possible to put an association/dependency from `History` -> `Action`. Since for `History` to be able to receive `ActionX` and `ActionY`, it should be associated to `Action` am I right?

**Comment by hingen** [comment]
`Action` implements `Repeatable`.
`Action`s are added to `History` as `Repeatable` (referring to the code snippet for `History`).

Hence, I believe the answer to your question would be no. `History` does not know about `Action`, it just knows about `Repeatable` (which `Action` implements).

**Comment by EvitanRelta** [comment]
@pangrwa where's this video from?
