### ISSUE TITLE
Optional Box for Sequence Diagrams

### ISSUE THREAD

**Issue by joyngjr** [nus-cs2103-AY2223S2/forum#403]
Hi, I was looking at this sequence diagram from the textbook, and I don't quite understand why we have the opt box extended till past the end of the activation bar of ParserFactory.

<img width="446" alt="image" src="https://user-images.githubusercontent.com/97519138/233788432-b65dbb6e-a5c7-45b4-92b7-507cc9e229c7.png">

Does this mean that the function will never return if the value is invalid and the opt path is not taken (since the return portion/end of the activation bar is within the opt box)?

**Comment by damithc** [comment]
@joyngjr Good observation. It would be more accurate to extend the activation bar beyond the edge of the opt box.
That said, this minor discrepancy does not hinder the reader from reading the interaction correctly -- this is probably why no one else raised this issue till now.

> Does this mean that the function will never return if the value is invalid and the opt path is not taken (since the return portion/end of the activation bar is within the opt box)?

We can rule out that interpretation as 'unrealistic'.
