### ISSUE TITLE
Canvas's textbook PDF & full-print website-page has collapsed sections

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#404]
For example, on page 43, the UML class diagram sections are collapsed _(and thus can't be viewed in the PDF)_ as shown below.

This is also the case on the full-printer-friendly website page: https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/print.html#class-diagrams-basics

![image](https://user-images.githubusercontent.com/35413456/233835779-8d6f1df7-a56d-47f5-85ad-210ebca2360b.png)

**Comment by damithc** [comment]
@EvitanRelta see the grey text in your screenshot :-)

**Comment by EvitanRelta** [comment]
@damithc Ah i see :^)
