### ISSUE TITLE
Object diagram for Array 

### ISSUE THREAD

**Issue by jundatan** [nus-cs2103-AY2223S2/forum#405]
![image](https://user-images.githubusercontent.com/94162414/233842456-22173fe8-e2bc-47c7-808f-e87109bb42b7.png)

How to draw the Object diagram for the `parts` attribute shown above if it contains some **Item** object?

**Comment by damithc** [comment]
@jundatan Standard containers such as Arrays and Lists are considered as merely internal mechanisms to hold multiple objects (as a normal variable can hold only one object). Therefore, they are omitted/implied in class and object diagrams. Just treat `parts` as a variable that can hold multiple objects.
