### ISSUE TITLE
Must UML diagram lines be straight?

### ISSUE THREAD

**Issue by venuslimm** [nus-cs2103-AY2223S2/forum#409]

**Comment by gremmyz** [comment]
@venuslimm I don't think they have to be straight (lines in PlantUML diagrams in the DG aren't always straight), but IMO straight lines provide more clarity ~~(so you don't have lines criss-crossing everywhere which defeats the purpose of having a diagram for comprehension)~~.

I think the main thing is that it should be clear if the line is a solid line or dashed line.

**Comment by damithc** [comment]
Yup, lines need not be straight.
![image](https://user-images.githubusercontent.com/1673303/233993410-3004d98f-37e3-4a91-9cae-4a9e6ebb2d75.png)

**Comment by venuslimm** [comment]
@gremmyz @damithc thank you for the responses!
