### ISSUE TITLE
Level 7: Record commands vs record task list state

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#41]
In `Level-7`, we are asked to load the data when `Duke` starts up, then the question is what representation we should use to save the task list. If we were to save the task list in the example given (attached below), we would need to implement another parser to deal with the text data, which is a bit redundant. 

```
T | 1 | read book
D | 0 | return book | June 6th
E | 0 | project meeting | Aug 6th 2-4pm
T | 1 | join sports club
```

Thus, what about we directly save all history commands, and re-run all commands when starting up? This way we can use the same string parser for processing user input and the data file.

Some preliminary thought: In principle, the file should save the state of the task list, instead of the procedure of creating the task list. However, in practice, given that re-running all commands is efficient, there don't seem to be a lot of drawbacks to creating the task list from scratch.

**Comment by damithc** [comment]
Interesting idea @BoAi01 A good topic for discussion i.e., pros and cons

**Comment by linustws** [comment]
Are we allowed to not save the task list like the example given, but maybe as a bunch of jibberish, as long as the 'list' command correctly displays the list as it updates? I'm thinking of using the serializable interface.

**Comment by damithc** [comment]
@linustws the format of the file is up to you. Yes, you can also save as serialized objects.
Note that unlike the iP, the [tP requires the data file to be a human editable text file](https://nus-cs2103-ay2223s2.github.io/website/admin/tp-constraints.html#constraint-human-editable-file).

**Comment by anchengyang** [comment]
If we save as serialized objects, must we save the object after every command or must we save the object only when the user types in the bye command to quit?

**Comment by damithc** [comment]
> If we save as serialized objects, must we save the object after every command or must we save the object only when the user types in the bye command to quit?

[anchengyang](https://github.com/anchengyang) That's another good question for discussion, and the question applies irrespective of the format being used for saving.

**Comment by hingen** [comment]
> However, in practice, given that re-running all commands is efficient, there don't seem to be a lot of drawbacks to creating the task list from scratch.

If the approach is to append any command that the user enters into the save file, I wonder if it could lead to a large save file over time. Hypothetically, if a user were to use the app for several years, could the save file get very big leading to higher start-up times and also larger storage usage?

For tasks that have already been deleted, the save file would still store the command for creating and deleting the task which would be redundant data. Perhaps `delete` commands should not be appended into the save file but rather remove their corresponding `add` command from the save file.

**Comment by muhammadreyaaz** [comment]
> If the approach is to append any command that the user enters into the save file, I wonder if it could lead to a large save file over time. Hypothetically, if a user were to use the app for several years, could the save file get very big leading to lower start-up times and also larger storage usage?
> 

This was my thought as well. So I decided to save into a way that can reuse the same parser instead of creating an entirely new parser. Also, I think it is quite strange to store multiple mark and unmark commands when it can essentially be one line. But I kind of modified the example way of storing to better suit by parser

**Comment by Junyi00** [comment]
I feel that the approach of storing user command history could lead to more complexity in the codebase. 

The system needs to behave exactly the same as when the user command was made in that save file. If the system requirement changes and the old data cannot be purged, the codebase needs to accommodate for the old behaviour when it is loading the save file. Eg. Previously, deadline command does not enforce parameters to be date. However after certain iterations, non-date complying parameters are rejected.

**Comment by arkarsg** [comment]
I feel that there are some merits in storing the commands of the user. For example, in Terminal, we can access previous command lines. Storing commands (maybe with temp files) would easily support this feature although it may not be in the design scope of this module.

Currently, my approach is to save at the end of the session (immediately after the user types "bye") with the Serializable interface. Initially, I thought of serialising each task and then loading it. However, I realised that an even simpler alternative is to seralize the entire Task ArrayList (or other similar implementation). Then, we just need to simply assign the ArrayList that is loaded for a new Duke session.

**Comment by BoAi01** [comment]
Thank you all for the input! I think there are different approaches with pros and cons. It is our design choice which one to use. 

I will close the issue for now.
