### ISSUE TITLE
[Spoiler: Practice Exam Part 1] Q6: Object Diagram to Class Diagrams

### ISSUE THREAD

**Issue by Bisceto** [nus-cs2103-AY2223S2/forum#410]
Here is the question with the answers:
![image](https://user-images.githubusercontent.com/88726470/233962479-b997a7d5-09ba-492e-bfa0-1a44d4783ae0.png)

I'll like to ask why the 4th option is not considered correct. Both the multiplicities between the chair and table are *, which includes the scenario that both multiplicities are 1 which follows the object diagram given. 

Does this have something to do with the multiplicity of the door being 1 i.e every table should be associated with a single door but it is not reflected in the given object diagram?

**Comment by gremmyz** [comment]
> Does this have something to do with the multiplicity of the door being 1 i.e every table should be associated with a single door but it is not reflected in the given object diagram?

Yup, I think this explanation is right, since multiplicity 1 means that it should be linked to one object at all times, it should be reflected as such in the OD.

**Comment by muhammadreyaaz** [comment]
Yes I think you are right as well. Option 4 means every Table must have a Door, which is not shown in the object diagram of the question.

**Comment by damithc** [comment]
Both @gremmyz @ARPspoofing are correct 👍

**Comment by Bisceto** [comment]
Thanks for the response everyone!
