### ISSUE TITLE
Question regarding alternative paths

### ISSUE THREAD

**Issue by lyndonlim27** [nus-cs2103-AY2223S2/forum#412]
In the textbook it says that it is acceptable for none of the alternative partitions to be executed. But I thought alternative paths is like an if else statement where it is guaranteed to execute one and only one partition.

<img width="352" alt="image" src="https://user-images.githubusercontent.com/80683209/234047443-7c51de55-efa6-441f-9d64-9e7efe8b795c.png">

**Comment by nramapurath** [comment]
I was wondering if perhaps the partitions' executions are optional to account for the scenario of an 'if-else if' without a closing 'else'? In that case, if none of the conditions match then none of the partitions would be executed.

**Comment by damithc** [comment]
@lyndonlim27 Unlike in activity diagrams in which exactly one path needs to be taken (or else the execution gets stuck), it is fine in `alt` frames to not execute any  partitions. This gives us more flexibility, as there are cases which none of the conditional code blocks are executed e.g., `switch-case` with no `default` branch (and the example @nramapurath mentioned).

**Comment by lyndonlim27** [comment]
I see. Thank you prof!
