### ISSUE TITLE
Can we update our repo?

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#413]
I presume the code freeze period is between 10-24 Apr, as mentioned in the [tP week 13 page]:

![image](https://user-images.githubusercontent.com/35413456/234159852-6fc93ece-03c1-490c-9d48-10bbcc5057b4.png)

Thus, since it's now beyong 24 Apr, are we allowed to push new commits to our tp's repo?

[tP week 13 page]: https://nus-cs2103-ay2223s2.github.io/website/admin/tp-w13.html#2-submit-deliverables-mon-apr-10th-2359:~:text=Do%20not%20update%20the%20code,after%20the%20code%2Dfreeze%20period.

**Comment by damithc** [comment]
@EvitanRelta Yes, go ahead.
