### ISSUE TITLE
Gray Box Testing

### ISSUE THREAD

**Issue by FredericChow00** [nus-cs2103-AY2223S2/forum#418]
Gray Box Testing uses some implementation knowededge, but does it use full knowledge of SUT specifications or only some?

**Comment by damithc** [comment]
@FredericChow00 Yes, we need full knowledge of the expected behavior, in all three types of test case design. What varies is how much knowledge of the internal implementation is used.

**Comment by FredericChow00** [comment]
Understood thanks prof!
