### ISSUE TITLE
Answer report on Examplify

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#419]
It seems that all my answers for the practice paper were uploaded wrongly for some reason (eg. Question not answered when I answered them, wrong answer recorded) should I be concerned about this?

**Comment by damithc** [comment]
@seadragon2000341 it is a problem if answers were not recorded. However, note that Examplify will give zero marks for questions that has a follow up question (even if you chose the correct answer for the first part), as it is unable to auto-grade the full answer.

If you still think there is a problem with the answers recorded, can you email me the answers you are seeing?
