### ISSUE TITLE
Level 7 Branching

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#42]
After I completed Level 7, I did not commit changes to that branch before creating a new branch for Level 8. So when I did git merge branch-level-7 in the end, all the changes from branch-level-8 were also pushed along with it. Is there a way I can rectify this?

**Comment by damithc** [comment]
@seadragon2000341 This means you have not yet learned how to use parallel branches properly. You can try again i.e., do some two minor changes to the code using two parallel branches. 
As for branch-level-7 and branch-level-8, it's fine as long as there are two branches with those names and they have been merged to the master branch.
