### ISSUE TITLE
[Practice Paper] UML diagram p3.07

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#420]
I have two questions about the below question and answer:
1. The constructor of the `Client` is activated, so the activation bar should connect to the `c:Client` box. Based on this, answers other than 2 and 3 should be wrong, but why is the last one correct?
2. Where is it in our textbook that mentions the lifeline of an object created earlier should start from a higher point?  

<img width="950" alt="Screenshot 2023-04-25 at 3 45 50 PM" src="https://user-images.githubusercontent.com/53465243/234209223-d717c6f8-59ca-4a15-bf82-dba0920afef0.png">

<img width="708" alt="Screenshot 2023-04-25 at 3 45 23 PM" src="https://user-images.githubusercontent.com/53465243/234209103-5e549358-79ea-48ff-837e-c34808120814.png">

**Comment by hingen** [comment]
1. Answer 1 and 4 have underlined objName:className which should not be the case for sequence diagram.
2. Not sure if it was mentioned in textbook but pretty sure it was brought up in lecture and tutorials several times

**Comment by hingen** [comment]
1. Activation bar is optional so it is not wrong to not provide it. Because s is created before c is created, we can eliminate 1, 2, and 3. Option 4 is incorrect because "c:Client" and "s:Server" are underlined. Hence, answer is the last option.

2. Not sure if it was mentioned in our textbook but pretty sure it was brought up a few times in lectures and tutorials.

**Comment by BoAi01** [comment]
Why are 2 and 3 wrong? They are the only ones that show the invocation of constructors.

**Comment by hingen** [comment]
> Why are 2 and 3 wrong? They are the only ones that show the invocation of constructors.

sry, misread ur question initially. I've edited my response.

**Comment by BoAi01** [comment]
Thanks for the explanation. But just to confirm, activation bars are optional? Could you point to somewhere in the textbook? Probably I missed it.

**Comment by SPWwj** [comment]
> Thanks for the explanation. But just to confirm, activation bars are optional? Could you point to somewhere in the textbook? Probably I missed it.


Minimal Notation

**Comment by hingen** [comment]
^ Yup, [Minimal Notation](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/uml.html#minimal-notation)

![image](https://user-images.githubusercontent.com/31367001/234217020-9564d042-bf8a-4814-82b1-62aec4d86512.png)

**Comment by BoAi01** [comment]
Great. Thank you all!
