### ISSUE TITLE
Branch coverage vs path coverage vs statement coverage

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#424]
I refer to this [article](https://stackoverflow.com/questions/15895517/path-testing-and-branch-testing) for the comparison between these three kinds of coverages, which mentions that 
> Path Testing >= Branch Testing >= Statement Testing

Based on the textbook, we shall agree that Path Testing >= any other testing, but why Branch Testing >= Statement Testing?
<img width="744" alt="Screenshot 2023-04-25 at 4 27 36 PM" src="https://user-images.githubusercontent.com/53465243/234219312-5d354d63-432d-4300-a404-ccfdd19f347b.png">

More specifically I am considering a simple example to check my basic understanding: 
```
if (a > 0) {
    b = a + 1;
} else {
    b = a - 1;
}
```
If we have one test case `a = 1`, and the `if` block is executed. What are the branch coverage rate and statement coverage rate? I think these should be 50% and 50% respectively.

**Comment by BoAi01** [comment]
I actually feel that if every statement is covered, then every branch is covered. Any counter-examples?

**Comment by SPWwj** [comment]
In this case, if the test cases only execute the scenario where the condition is true, all the statements (statement1 and statement2) will be executed, resulting in 100% statement coverage. However, branch coverage will still be 50%, as the scenario where the condition is false has not been tested.
```
if (condition) {
    statement1;
}
statement2;
```

**Comment by BoAi01** [comment]
I see. Then this makes sense now. Thanks
> Path Testing >= Branch Testing >= Statement Testing

**Comment by damithc** [comment]
Good example, @SPWwj
