### ISSUE TITLE
Practice paper Q15 (part 1) 

### ISSUE THREAD

**Issue by Zxun2** [nus-cs2103-AY2223S2/forum#429]
May i clarify why option 2 is considered correct? To my understanding, it is not true that **all** open PRs created from the fork is updated. For example, pushing to the `master` branch should only update the PRs merging from the `master` branch. 

![image](https://user-images.githubusercontent.com/63457492/234235919-89c6cd5d-9ed2-408c-b5b2-07d68824e888.png)

**Comment by damithc** [comment]
@Zxun2 You are right -- it applies only some PRs. I should refine that answer option to make it more accurate.

**Comment by Zxun2** [comment]
Thanks prof! @damithc
