### ISSUE TITLE
Cannot resolve symbol 'java' after installing Gradle

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#43]
![image](https://user-images.githubusercontent.com/92144641/213956548-9ebc4767-e50e-4ff3-9fa7-6da2684b1da5.png)

after following the steps in the Gradle tutorial on the site, (scenario 2, then scenario 1)
![image](https://user-images.githubusercontent.com/92144641/213956612-b5fff2c8-fa74-4618-a7ea-d320f07756ef.png)

I can't seem to be able to run my code as usual, nor is it detecting java in the code.
How can i fix this?

**Comment by Tempura-Person** [comment]
For context, i have tried some fixes from the internet such as:

1. File > Invalidate Caches and Restart
2.  Delete the .idea file and open the ip project again

to no avail.

**Comment by damithc** [comment]
@Tempura-Person Also try cloning the fork to a new location in your computer and applying scenario 2.

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213961283-8f3a8af1-23d0-432f-8f71-1e8e54df92d2.png)

no luck, i've tried cloning it over to the same directory (next to ip) under a different name (ip2)
and even on the D drive under a different name. same problem persists.

**Comment by damithc** [comment]
Are you able to run Gradle commands in the terminal e.g., `gradlew run` ?

**Comment by Tempura-Person** [comment]
> Are you able to run Gradle commands in the terminal e.g., `gradlew run` ?

![image](https://user-images.githubusercontent.com/92144641/213963970-6979fa66-69e8-4752-8f0b-8500648cba55.png)

it seems that it does

**Comment by damithc** [comment]
> ![image](https://user-images.githubusercontent.com/92144641/213963970-6979fa66-69e8-4752-8f0b-8500648cba55.png)
> 
> it seems that it does

Seems this one failed. Was the code working before you added Gradle?

If you can build/run/test using Gradle commands in the terminal, the problem could be something to do with Intellij.
Perhaps you can clone the initial upstream repo https://github.com/nus-cs2103-AY2223S2/ip and try to set it up in Intellij (without Gradle) to see if it still works.

**Comment by shirsho-12** [comment]
If gradlew run doesn't work can you try running ./gradlew, PowerShell doesn't work without the ./ As far as I know

**Comment by Tempura-Person** [comment]
> > ![image](https://user-images.githubusercontent.com/92144641/213963970-6979fa66-69e8-4752-8f0b-8500648cba55.png)
> > it seems that it does
> 
> Seems this one failed. Was the code working before you added Gradle?
> 
> If you can build/run/test using Gradle commands in the terminal, the problem could be something to do with Intellij. Perhaps you can clone the initial upstream repo https://github.com/nus-cs2103-AY2223S2/ip and try to set it up in Intellij (without Gradle) to see if it still works.
![image](https://user-images.githubusercontent.com/92144641/213967881-ea1f5886-fa41-4edb-b66e-05dbeabfd5e2.png)

my code was fully working, up till i merged the origin/add-gradle-support commit on sourcetree and followed the gradle setup tutorial.

**Comment by Tempura-Person** [comment]
Strange, i checked out to the commit just before i merged the gradle branch in, and now java isnt detected there, either.
What did the merge damage, exactly?

![image](https://user-images.githubusercontent.com/92144641/213968289-3c4c0202-28f4-48e4-adcf-592b76bbceef.png)

**Comment by damithc** [comment]
@Tempura-Person can you share the equivalent of these settings in your project?

![image](https://user-images.githubusercontent.com/1673303/213968406-c6f01579-9c97-4e2a-b37c-6ec0973db3d8.png)

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213968553-db80689f-0ffd-4b0c-919b-d3218e74d328.png)

**Comment by damithc** [comment]
Try changing these to see if that makes a difference:
![image](https://user-images.githubusercontent.com/1673303/213968852-bbee5c01-fd86-47f1-97f0-313e194fbdfc.png)

Also, when invalidating caches earlier, did you tick all the boxes? If not, try that too.

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213969228-db6377ff-dab8-41b4-92c6-7f511d48f505.png)

i changed these, and also invalidated caches with all boxes ticked.
yeah...

**Comment by damithc** [comment]
My guess is something went wrong with your local IDEA settings (as no one else has reported such a problem so far).
As not being able to find built in `java` package could be related to SDK settings, you can try redoing the following settings:
![image](https://user-images.githubusercontent.com/1673303/213970143-a3d8eeaf-0a47-4255-9088-9dd5bab4a00d.png)

As a last ditch drastic measure, you can also try a full uninstall-reinstall of Intellij

**Comment by Tempura-Person** [comment]
![image](https://user-images.githubusercontent.com/92144641/213972412-9dba2436-311d-48bb-abdb-9bf8891e0fe1.png)

thank you for suggesting the jdk/sdk fix, i assumed they were corrupted too, so i just deleted the entire jdk file manually and reinstalled it. now it recognises java.
