### ISSUE TITLE
Parent class more restrictive than child class?

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#430]
May I know why the parent class is more restrictive than the child class? I thought inheritance makes it more "specialized". 

![image](https://user-images.githubusercontent.com/53465243/234265666-f942c4e9-0c45-40a7-a056-17db459c8500.png)

**Comment by Zxun2** [comment]
> Derived classes must be substitutable for their base classes.

If the child class is more restrictive, substituting the parent with the child would result in unexpected behaviors. 

You can read more [here](https://nus-cs2103-ay2223s2.github.io/website/se-book-adapted/chapters/principles.html#liskov-substitution-principle)!

**Comment by BoAi01** [comment]
Alright, thanks. I would really think it depends on how we define "restrictive" though. If A can substitute B (A is a sub-class of B) means A is less restrictive, this statement makes sense, yes. 

Thanks!

**Comment by damithc** [comment]
Yup, don't equate _restrictive_ with _specialized_. The child classes can be more specialized without being more restrictive than the parent class.
