### ISSUE TITLE
Tutorial 8 Object Diagram

### ISSUE THREAD

**Issue by Nicklelodeon** [nus-cs2103-AY2223S2/forum#431]
Hi, for the question below, I was wondering if it would be acceptable to have Rating be an attribute under Review (i.e under Review, add rating = POOR), rather than drawing out the Rating object with the POOR attribute? 
<img width="571" alt="Screenshot 2023-04-25 at 7 58 41 PM" src="https://user-images.githubusercontent.com/95112058/234270498-064078f2-852d-4d04-be0b-6ea7bee7512c.png">

<img width="829" alt="Screenshot 2023-04-25 at 7 58 26 PM" src="https://user-images.githubusercontent.com/95112058/234270698-955ea5b5-021a-4e50-a509-db45836545a8.png">

**Comment by damithc** [comment]
@Nicklelodeon  Yes:
![image](https://user-images.githubusercontent.com/1673303/234281225-c493c73a-064f-4916-9b39-873da5a88336.png)

**Comment by Nicklelodeon** [comment]
@damithc thank you prof!
