### ISSUE TITLE
Practice Exam Part 2 a

### ISSUE THREAD

**Issue by joytqt-1202** [nus-cs2103-AY2223S2/forum#432]
Should `update()` in `UiWidget` be excluded since `UiWidget` extends from `ProgressWatcher` which inherits from `Watcher` which already has `update()`? 

Answer for Practice Exam Part 2 a
![image](https://user-images.githubusercontent.com/96771931/234298360-21caf929-ebf1-41ac-beee-9ce962fd521e.png)

**Comment by Zxun2** [comment]
There is a related [issue](https://github.com/nus-cs2103-AY2223S2/forum/issues/422) for this!

**Comment by joytqt-1202** [comment]
oh! thank you!
