### ISSUE TITLE
Question about citation of reused code

### ISSUE THREAD

**Issue by yitong241** [nus-cs2103-AY2223S2/forum#436]
Hello Professor, may I check how we should cite any reused code if we just found that we did not cite properly last time?

**Comment by damithc** [comment]
> Hello Professor, may I check how we should cite any reused code if we just found that we did not cite properly last time?

@yitong241 Yes, please do so by tomorrow (Thursday).

**Comment by yitong241** [comment]
Thx prof, but how should we do it now?

**Comment by damithc** [comment]
@yitong241 You can update the code as necessary and push to the team repo.

**Comment by yitong241** [comment]
Thx prof, got it! Thank you for the great semester!
