### ISSUE TITLE
Question about where to add the tag

### ISSUE THREAD

**Issue by yitong241** [nus-cs2103-AY2223S2/forum#45]
Hello!
For the tags to Level 7 and Level8, should them be added to branch-level-7 and branch-Level-8 or the master brach after merging with branch-level-7 and branch-Level-8?

**Comment by damithc** [comment]
Either way is fine @yitong241

**Comment by eugenetangkj** [comment]
Hi! I am a fellow student, and based on my understanding, the tags should be added after merging. In other words,

1. Work on Level 7 in a branch named branch-level-7.
2. Switch back to master, and create a new branch named branch-level-8 to work on Level 8.
3. Switch back to master. Merge branch-level-7. This merge will create a merge commit in master, and tag this commit as "Level-7". Push this commit to your fork.
4. In master, merge branch-level 8. This merge will again create a merge commit in master, and tag this commit as "Level-8".

Do correct me if my understanding is incorrect. Thanks!

**Comment by damithc** [comment]
@eugenetangkj is correct. The instructions specifies the tagging to be done after merging.

**Comment by yitong241** [comment]
Thx all!
