### ISSUE TITLE
Saving error when exporting iP to jar file

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#47]
![image](https://user-images.githubusercontent.com/92144641/213984953-ab8e5f6f-f2ca-4715-8eb2-8caf721f7b92.png)

as suggested by the instructions below, i exported my iP into a jar file using intelliJ's build artifacts function.
The whole thing functions properly besides the 'bye' command (which does not terminate the process) and the autosave feature failing to work (as i set up an error message to display if it happens)

![image](https://user-images.githubusercontent.com/92144641/213984998-976e77a5-acc3-43ca-b27f-da17f760f97a.png)

These bugs seem to be exclusive to the exported jar file (the project still works fine within intelliJ) and i don't know how to fix them properly.

**Comment by Tempura-Person** [comment]
for some context:
![image](https://user-images.githubusercontent.com/92144641/213985657-8d4a1df3-a202-4129-a693-4a2206a11531.png)
how 'bye' works is that all user input is handled by the Parser class.

The Parser class has a loopEnd boolean that signals when the 'bye' command has been entered, before updating it to true.

![image](https://user-images.githubusercontent.com/92144641/213986122-69c50601-3e67-4f2a-b362-1fa24dece312.png)

At the end of every command of user input, the main method (in the Duke class) updates to be the same as loopEnd in the Parser class, so when loopEnd in Parser is true, the loop to accept user input also stops in the main method.

**Comment by Tempura-Person** [comment]
as for the autosave, it is also handled by Parser automatically every time a command is handled.
![image](https://user-images.githubusercontent.com/92144641/213986302-8d89a894-a189-48a7-8d7e-3e37c803b300.png)

![image](https://user-images.githubusercontent.com/92144641/213986248-4137b496-3785-44fe-8df0-ab584e88bf57.png)

i assume the error is because the filepath "data/duke.txt" cannot be accessed, but isn't this already a relative filepath?

**Comment by hansstanley** [comment]
Check if you have handled the case where the folder doesn't exist, as the .jar file likely won't have a /data folder in the directory it is situated.

From the module website:
> Your code must handle the case where the data file doesn't exist at the start. Reason: when someone else takes your Duke and runs it for the first time, the required file might not exist in their computer. Similarly, if you expect the data file to be in as specific folder (e.g., ./data/), you must also handle the folder-does-not-exist-yet case.

**Comment by SPWwj** [comment]
try 
1.check if directory exist if not mkdir
2.check if file exist if not create files

do allow to print the original exception msg as it will give you more info during debugging.
hope this can help :）

**Comment by Tempura-Person** [comment]
that did it, i didnt check if the file and directory existed first time around, now it works in .bat autotesting and the exported .jar file.
Thanks!

**Comment by lhy-hoyin** [comment]
Hello! It appears that your issue have been resolved :D
Perhaps @Tempura-Person can mark this issue as `Close as completed`. Thank you!
(But it you think your question is still not answered, perhaps you can reiterate what you would like to clarify.)
