### ISSUE TITLE
Checkstyle not found after merged add-gradle-support

### ISSUE THREAD

**Issue by heeeyi** [nus-cs2103-AY2223S2/forum#48]
Hi I am currently doing the A-Gradle task, and has been following the tutorial provided in https://se-education.org/guides/tutorials/gradle.html.

However, when I tried to follow the tutorial in the "Checkstyle" section, namely the one at https://se-education.org/guides/tutorials/checkstyle.html, I found that the files config/checkstyle/checkstyle.xml and config/checkstyle/suppressions.xml not present in the project, nor was the directory ./config/checkstyle/ present. 

I checked the build.gradle file, and found that the plugin for checkstyle was not there. I have tried with running other gradle tasks such as clean and test, which had no issues.

I wonder if this is normal, and how could I add the checkstyle plugin to my project? Is it necessary?

I will be appreciated if anyone can help! Attached is my screenshot of the project folder and the build.gradle file.

![屏幕截图(1429)](https://user-images.githubusercontent.com/97591125/213987624-54414ed2-f481-4434-b8da-f37171c20bc1.png)

**Comment by damithc** [comment]
@heeeyi FYI, adding Checkstyle support is a [week 4 task](https://nus-cs2103-ay2223s2.github.io/website/schedule/week4/project.html).

**Comment by heeeyi** [comment]
Yes I see...however, I cannot see the files config/checkstyle/checkstyle.xml & config/checkstyle/suppressions.xml anywhere, which seems to be the pre-requisite of any possible setup of checkstyle. Where can we find these files, or will they be provided separately by then?

**Comment by damithc** [comment]
@heeeyi IIRC, https://se-education.org/guides/tutorials/checkstyle.html has tips on what to do if you don't have checkstyle config files in your project.

**Comment by Zxun2** [comment]
> Where can we find these files, or will they be provided separately by then?

You can create the directories and copy the files [here](https://github.com/se-edu/addressbook-level3/tree/master/config/checkstyle) over!

**Comment by linustws** [comment]
@heeeyi I also had to add id 'checkstyle' in plugins and this block of code:
checkstyle {
    toolVersion = '10.2'
}
for it to work.

**Comment by BoAi01** [comment]
Need to create a directory called `config`, copy over the config files, and modify `build.gradle` accordingly.

**Comment by EmilyOng** [comment]
Hello @heeeyi, I'm from your senior batch (dropping by in this forum to see if I can help you guys with tech problems). Just a gentle reminder to close the issue if your problem has been resolved :)
