### ISSUE TITLE
On MacOs, where is the .gitignore file located?

### ISSUE THREAD

**Issue by adam07018** [nus-cs2103-AY2223S2/forum#5]
Doing week 2 reading and now I am at w2.3f. I created temp.txt and ignore the file as instructed.

However,  I can't locate the .gitignore file. Is there any way to find it? I am using Mac.
<img width="769" alt="screenshot" src="https://user-images.githubusercontent.com/62133038/212508721-1a1c57e1-453e-4415-917b-65969b43df70.png">

Update: the folder itself is a hidden folder.  So I am actually showing hidden file already

**Comment by jugheadjones10** [comment]
.gitignore is a hidden file, so you need to reveal hidden files to see it. For Mac OS I think the command to see hidden files is Command + Shift + . (that's a full stop at the end) @adam07018

**Comment by BoAi01** [comment]
Agree, it is a hidden file. See this question for more details: 
```
https://stackoverflow.com/questions/11197249/show-system-files-show-git-ignore-in-osx
```

**Comment by adam07018** [comment]
> .gitignore is a hidden file, so you need to reveal hidden files to see it. For Mac OS I think the command to see hidden files is Command + Shift + . (that's a full stop at the end) @adam07018

Yah but the whole file .git is a hidden folder and I am showing hidden file already. That is why i am quite confused

**Comment by damithc** [comment]
This might be useful: [The `ls` command](https://www.technology.pitt.edu/help-desk/how-to-documents/basic-unix-commands) when used with the appropriate switch will list the hidden files in a folder. It can help you find if the file in concern is there but not shown, or missing altogether. This is a command you run in the terminal, and is independent of the 'show hidden files' setting of the file viewer.

**Comment by Merrickneo** [comment]
I normally just make use of `ls -a` to review hidden files. If my IDE doesn't show the .gitignore file, I'll just make use of vim to access the file and make edits to it.

**Comment by lhy-hoyin** [comment]
> 

I believe that the `.gitignore` file is in the **same directory** as the `.git` folder, rather than being inside the `.git` folder.

Think of the following structure:
```
...\MyRepo\.git\...
...\MyRepo\.gitignore

...\MyRepo\README.md
...\MyRepo\CONTRIBUTORS.md
...\MyRepo\text-ui-test\...
...\MyRepo\src\...
...\MyRepo\bin\...
...\MyRepo\...
```

**Comment by salty-flower** [comment]
I prefer `ls -a` too. Or even just `vim .gitignore` - trust me, it won't be very painful to edit a plain text file with vim :)

**Comment by damithc** [comment]
> I believe that the `.gitignore` file is in the **same directory** as the `.git` folder, rather than being inside the `.git` folder.

@salty-flower good point. @adam07018, based on the screenshot, perhaps you are looking in the wrong folder?

**Comment by adam07018** [comment]
Oh my bad. Actually just select add ignore entry to this repository and it will work. Previously I put it as global ignore list.
<img width="527" alt="截屏2023-01-16 10 44 31" src="https://user-images.githubusercontent.com/62133038/212587679-72d6968f-85d9-4e2d-a219-a2d8735869f1.png">
BTW, vim and ls -a works all fine. Thanks all for helping and contributing.
