### ISSUE TITLE
Strict adherence to naming of increments?

### ISSUE THREAD

**Issue by 4ndrelim** [nus-cs2103-AY2223S2/forum#50]
I understand there will be a grading script to detect our branches and tags, suppose there is some deviation from the advised name e.g 'Level-7' instead of 'branch-level-7', will this cause issues later on with the script?

**Comment by damithc** [comment]
@4ndrelim Yes, the script might not detect branches/tags that are named differently from the expected names. However, the script can be satisfied easily by simply having a merged branch with the correct name (even if the branch is empty).

**Comment by 4ndrelim** [comment]
Alright, so to resolve this, i simply create a new branch with the correct name, merge the incorrectly named branch into the correctly named one, without having to mess with master branch?

**Comment by damithc** [comment]
> Alright, so to resolve this, i simply create a new branch with the correct name, merge the incorrectly named branch into the correctly named one, without having to mess with master branch?

Yes @4ndrelim, that should work.

**Comment by 4ndrelim** [comment]
thank you!
