### ISSUE TITLE
Grading scripts detecting case-insensitive branch/tag names?

### ISSUE THREAD

**Issue by 4ndrelim** [nus-cs2103-AY2223S2/forum#53]
Hi, as i was updating my tag/branch names to align with the advised ones, i noticed branches with the same spelling but different case are treated the same (e.g 'branch-level-7' is the same as 'branch-Level-7'). 

A quick google search suggests that while git is case-sensitive, our filesystem may not be. So i'm wondering if the grading scripts would be able to detect the branches/tags regardless of case.

**Comment by damithc** [comment]
@4ndrelim IIRC, the progress tracking script is not sensitive to the case of tag/branch names.

**Comment by 4ndrelim** [comment]
okay thank you!
