### ISSUE TITLE
Forgot to tick the box when merging branch with master

### ISSUE THREAD

**Issue by thennant** [nus-cs2103-AY2223S2/forum#55]
![image](https://user-images.githubusercontent.com/97217532/214226920-393d6ec2-2ca0-4da7-ba2c-8411133c746c.png)

I forgot to tick the little box at the corner when merging my branch with the master, is that an issue? Do i have to unmerge the branch and merge it again? Or can i just merge the branch with the master again?

**Comment by damithc** [comment]
Should be fine @thennant Remember to do it in future merges.
But you are welcome to try to correct it too.

**Comment by thennant** [comment]
Ok thanks prof!
