### ISSUE TITLE
text-ui-test no longer working

### ISSUE THREAD

**Issue by valerietanhx** [nus-cs2103-AY2223S2/forum#57]
Hello! For some reason, it seems my input.txt is no longer being read, and my ACTUAL.TXT doesn't contain anything else other than the lines initially printed when Duke is first started up. I've included screenshots of my EXPECTED_UNIX.TXT, input.txt, and ACTUAL.TXT. It seems nothing is being read at all...

I'm not sure when this behaviour started; am wondering if this has to do with Level 7 and loading data in from the hard drive, or if it's another issue I should be concerned about :O Any input (haha) would be appreciated!!

Edit: if it helps, I've only done up till Level 8 for now.

<img width="700" alt="Screenshot 2023-01-25 at 1 06 40 AM" src="https://user-images.githubusercontent.com/110474344/214359955-8ad2ebec-e802-431e-be24-853494ab879a.png">
<img width="494" alt="Screenshot 2023-01-25 at 1 06 36 AM" src="https://user-images.githubusercontent.com/110474344/214359967-1a71d4cb-0350-4129-ac53-d8c4e686fafe.png">
<img width="719" alt="Screenshot 2023-01-25 at 1 06 31 AM" src="https://user-images.githubusercontent.com/110474344/214359975-6c94a6a6-8d3e-442d-a94f-c669587fa5d4.png">

**Comment by hingen** [comment]
Hi @valerietanhx, I'm unable to recreate your issue using the current code in your repo. Could you post the output from running `runtest.sh` or `runtest.bat`? Since error messages will not be written to `ACTUAL.txt`, would be helpful to see the output of the bash/batch scripts.

**Comment by valerietanhx** [comment]
Hello! @hingen it seems `runtest.sh` results in `ArrayIndexOutOfBoundsException: Index 4 out of bounds for length 4` when trying to load my data from the file saved in the hard drive. The weird thing is that the error doesn't occur if I'm just rerunning Duke normally outside of the test (i.e. the data gets read correctly). Also, even if I've deleted the old data (so it's a "fresh start" for Duke), the exact same error occurs when I try `runtest.sh`, even though the only time I have a `[4]` across all my different files is when trying to load old data.

Currently, the list of tasks is saved in the following format in the text file:
_event 28/1/2023 1700 28/1/2023 1800
project meeting_

i.e. [task type] [date] [time] [date] [time]
[desc]

Additionally, not sure if this is related, but I also have a `dos2unix: command not found` error :O it's been showing all this while if I'm not wrong and the test has been running fine till now though :")

<img width="858" alt="Screenshot 2023-01-25 at 12 42 12 PM" src="https://user-images.githubusercontent.com/110474344/214481590-c29cc013-3dc8-4636-b90e-510de7d780de.png">

**Comment by hingen** [comment]
I can't recreate the issue using the code in your repo so I can only speculate. I'm guessing it's either one of these:
1. You have an old outdated `tasks.txt` file that is perhaps not in line with the current way you save your task list. Try deleting the `<project_root>/data` directory as well as `<project_root>/text-ui-test/data` directory
2. The error is in some code that you have not pushed to your remote repo

**Comment by hingen** [comment]
I think the `dos2unix` error is likely unrelated. The command should only matter if you created `EXPECTED.txt` in Windows but you're trying to run `runtest.sh` from Mac or Linux. The command is likely there to fix any inconsistencies in line endings and other differences between DOS (Windows) and Unix like (Mac and Linux) OS.

I can't recreate the issue using the code in your repo so I can only speculate. Did you perhaps forget to delete `<project_root>/text-ui-test/data`?

Since you're likely running `runtest.sh` from within the `<project_root>/text-ui-test` directory, duke doesn't save to `<project_root>/data` but to `<project_root>/text-ui-test/data` instead.

**Comment by WillCWX** [comment]
Hello @valerietanhx ,
I also cannot replicate your issue on both windows and ubuntu linux, it seems that this is a mac specific error. I am unsure if this information will be helpful to others but could you specify the version of macOS you are using? (also apple m1/m2 or intel chip)

It does conclusively appear that the `loadData` method is causing the error. Could you add in another `if else` in line 29 such that the "event' condition is also accounted for and allows us to debug the situation where line[0] is not a task type?
```
                .... if (line[0].equals("event")) { // event
                    tasks.add(new Event(sc.nextLine(), line[1], line[2], line[3], line[4]));
                } else {
                    // this should not run!
                    System.out.println("Error! This should not run!");
                    for (int i = 0; i < line.length; i++) {
                        System.out.println(line[i]);
                    }
                }
```

Hopefully this should print out what line was read that caused the error.
Do update us on the result of debugging using this method.

**Comment by valerietanhx** [comment]
Hello!! @hingen turned out to be right; I forgot to delete `<project_root>/text-ui-test/data` :") Thanks for pointing it out!
