### ISSUE TITLE
Unable to run add-gradle-support branch on CLI

### ISSUE THREAD

**Issue by StanleyNeoh** [nus-cs2103-AY2223S2/forum#58]
Hello! I am attempting to integrate Gradle into my iP and am experimenting on the unmodified add-gradle-support branch with CLI. However, when I try to run the branch with `gradlew run`, There is a build error.

```java
~\CS2103T\ip>gradlew run

> Task :run FAILED
Error: Could not find or load main class seedu.duke.Duke
Caused by: java.lang.ClassNotFoundException: seedu.duke.Duke

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':run'.
> Process 'command 'C:\Program Files\Java\jdk-11.0.17\bin\java.exe'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
2 actionable tasks: 1 executed, 1 up-to-date

~\CS2103T\ip>
```

May I know what I am doing wrong and how I can resolve this? Thank you in advance!

**Comment by hingen** [comment]
You have to open the `build.gradle` file and set the `application.mainClassName` to refer to your main class name. In the `add-gradle-support` branch, the main class name would be `Duke`. In your branch, it would be `<the_package_containing_Duke.java>.Duke`

```gradle
// some configs

application {
    mainClassName = "Duke" // originally set to "seedu.duke.Duke" on the add-graddle-support branch
}

// some configs
```
