### ISSUE TITLE
When will participation dashboard start updating?

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#6]
[Participation dashboard](https://nus-cs2103-ay2223s2.github.io/dashboards/contents/participation.html)

**Comment by arkarsg** [comment]
At the bottom of the [link](https://nus-cs2103-ay2223s2.github.io/website/admin/participation.html#where-to-find-your-participation-marks-progress), it states that it will start tracking from week 3 onwards 👍

**Comment by BoAi01** [comment]
Issue resolved. Thank you!
