### ISSUE TITLE
Using code linters & formatters

### ISSUE THREAD

**Issue by EvitanRelta** [nus-cs2103-AY2223S2/forum#61]
To aid in following the code standard, are we allowed to use: 
- Linters, which highlights any coding-standard violations  
  _(eg. Sonarlint)_ 
- and/or formatters, which auto-formats and fixes coding-standard violations  
  _(eg. Eclipse's java formatter)_

The main concern is since formatters auto-corrects any violations, we might not learn the coding-standard.  
Which isn't a problem for projects _(in fact I think formatters are a great way to enforce coding-standards)_  
BUT, I'm afraid that we might be tested on those coding-standards in quizes/tests/exams/practicals.

**Comment by damithc** [comment]
@EvitanRelta You are welcome to use linters and formatters. Also, you are encouraged to share in here your experience of (and guidance for) using them so that others can learn them too.
