### ISSUE TITLE
runtest.bat not reading the next input

### ISSUE THREAD

**Issue by nerdyboy98** [nus-cs2103-AY2223S2/forum#62]
I got my runtest.bat to finally run but somehow the file isn't reading my next input line. As seen from the image attached, the batch file runs the first input "todo borrow book" properly but afterwards it was unable to take the next input "bye" and this causes the terminal throws a NoSuchElementException error. Can anybody comment on what can I do to allow my runtest.bat to read the subsequent input line? Thanks in advance! Attached as well is my runtest.bat configuration.

![image](https://user-images.githubusercontent.com/110829473/214524503-2f7444e4-9247-4543-b611-bef96c743d5a.png)
![image](https://user-images.githubusercontent.com/110829473/214525360-c1f52275-6534-4125-86bb-49787f6dfd8e.png)

**Comment by hingen** [comment]
Might be related to #29 which is a combination of 2 issues

Try the following:
1. Make sure that `Scanner` object is created only once throughout the execution of the app (that is do not create it inside a while loop)
2. In your `input.txt`, add a new line after bye (so there should be one blank line at the end of the file)

**Comment by nerdyboy98** [comment]
> 

ahh thanks alot, that solved my problem. Also is there a way to know if the ACTUAL output is same as the EXPECTED output? Or do I have to manually observe whats shown in the terminal :o

**Comment by hingen** [comment]
`runtest.bat` is suppose to handle that for you. It uses the `FC` command which is for comparing files. Look at your command prompt output for the details. If I'm not wrong, you should see a `FC: no differences encountered` if `ACTUAL.txt` and `EXPECTED.txt` contain the same content.

I'm on Linux using `runtest.sh` so I'm not sure what is the exact output of `runtest.bat`. Perhaps someone on Windows would be able to comment on this
