### ISSUE TITLE
Gradle cannot build/run/clean using command line.

### ISSUE THREAD

**Issue by WilliamHaiweiGu** [nus-cs2103-AY2223S2/forum#63]
So I just merged add-gradle-support branch into master branch.
The code can build & run using IJ's built-in tools.
The code can also build, run, and clean successfully by double clicking the task in gradle panel:
![image](https://user-images.githubusercontent.com/55661715/214570576-4dca09f1-98cf-40cc-a7af-ba2ca11efc85.png)
But when I tried to run these into terminal:
`gradlew build` failed with java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.vmplugin.v7.Java7.
`gradlew run` and `gradlew clean` also failed with java.lang.NoClassDefFoundError: Could not initialize class org.codehaus.groovy.runtime.InvokerHelper.
How do we build/run/clean gradle using command line? Thank you!

**Comment by damithc** [comment]
@WilliamHaiweiGu It might help if you also describe the steps you took to incorporate Gradle into the project. Just merge the branch only or did you do any additional steps?

**Comment by WilliamHaiweiGu** [comment]
> @WilliamHaiweiGu It might help if you also describe the steps you took to incorporate Gradle into the project. Just merge the branch only or did you do any additional steps?

I also changed the gradle.build file so that `application.mainClassName` and `shadowJar.archiveBaseName` are both the class with `main` method.
[build.gradle.txt](https://github.com/nus-cs2103-AY2223S2/forum/files/10499723/build.gradle.txt)

**Comment by c0j0s** [comment]
What java version are you using? I encounter this error when I was using java 16 previously. I switched back to java 11 and gradle works fine afterwards.

**Comment by damithc** [comment]
> I also changed the gradle.build file so that `application.mainClassName` and `shadowJar.archiveBaseName` are both the class with `main` method.
> [build.gradle.txt](https://github.com/nus-cs2103-AY2223S2/forum/files/10499723/build.gradle.txt)

Did you follow scenario 2 from https://se-education.org/guides/tutorials/gradle.html#adding-gradle-to-the-project ?

**Comment by EvitanRelta** [comment]
I also had same problem. Apparently, it was cause my PC's `JAVA_HOME` enviromental variable wasn't set.

>## Edit:
> Looking at the `gradlew.bat` script, it seems that if `JAVA_HOME` isn't set, it will fall back on whatever version ur commandline java is set to. U can check what version that is be entering `java --version` in ur commandline.
>
> Mines apparently set to JDK17, which is probably what's causing the problems:
>
> ![image](https://user-images.githubusercontent.com/35413456/215050004-7260ecce-e6b7-4d7a-8b01-593597ff6d17.png)


@WilliamHaiweiGu, try entering `echo %JAVA_HOME%` into ur command-line. What does it output?

It should output a JDK11 path like: `C:\Program Files\Java\jdk-11.0.14`

If it doesn't, then try setting it with these steps: https://help.sap.com/docs/SAP_BUSINESSOBJECTS_ANALYSIS,_EDITION_FOR_OLAP/c4341f1ce3324d9d9309163567effc1b/eca795926fdb101497906a7cb0e91070.html?version=4.2.7

**Comment by WilliamHaiweiGu** [comment]
> I also had same problem. Apparently, it was cause my PC's `JAVA_HOME` enviromental variable wasn't set.
> 
> > ## Edit:
> > Looking at the `gradlew.bat` script, it seems that if `JAVA_HOME` isn't set, it will fall back on whatever version ur commandline java is set to. U can check what version that is be entering `java --version` in ur commandline.
> > Mines apparently set to JDK17, which is probably what's causing the problems:
> > ![image](https://user-images.githubusercontent.com/35413456/215050004-7260ecce-e6b7-4d7a-8b01-593597ff6d17.png)
> 
> @WilliamHaiweiGu, try entering `echo %JAVA_HOME%` into ur command-line. What does it output?
> 
> It should output a JDK11 path like: `C:\Program Files\Java\jdk-11.0.14`
> 
> If it doesn't, then try setting it with these steps: https://help.sap.com/docs/SAP_BUSINESSOBJECTS_ANALYSIS,_EDITION_FOR_OLAP/c4341f1ce3324d9d9309163567effc1b/eca795926fdb101497906a7cb0e91070.html?version=4.2.7

This solved my issue. TSM!
