### ISSUE TITLE
Automating the testing of text UIs after implementing Level-7

### ISSUE THREAD

**Issue by jamieeeleow** [nus-cs2103-AY2223S2/forum#66]
Before implementing Level-7 of saving data, my text-ui-test was able to pass the runbash.sh test. However, after adding a data storage file in [project-root]/data/duke.txt, I think my input file was unable to read and access the file resulting in it printing an empty list.

May I know how to get the data read and printed? Thank you!

**Comment by hingen** [comment]
If you specify your input file path as `./data/duke.txt` in your code, then it's likely that when you run `runtest.sh`, the data file used is in `<project_root>/text-ui-test/data/duke.txt` as you are executing `runtest.sh` from the `text-ui-test` directory. Perhaps you could place the data file to be use for testing in that directory instead?
