### ISSUE TITLE
Branch and Push

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#67]
"Pushing the master branch does not automatically take the b1 branch along with it just because it is already merged to the master branch"
So if I do not push the b1 branch, I will not be able to see that branch on github? (eg. i cannot see the commits I made on that branch)

**Comment by damithc** [comment]
> So if I do not push the b1 branch, I will not be able to see that branch on github? (eg. i cannot see the commits I made on that branch)

Good question @seadragon2000341 (this gives an opportunity to look into how Git branches work). Let's see what others think.

**Comment by zrei** [comment]
If you have merged the b1 branch into the master branch locally and pushed the master branch, you will be able to see the commits you made in the b1 branch appear in the master branch on remote, but you will not be able to see the b1 branch.

When you merge b1 into master, the commits made in b1 are added into master. So when you push master, these new commits are pushed to the remote repository and therefore can be seen.

Do correct me if I've made any mistake!

**Comment by muhammadreyaaz** [comment]
If I am not wrong, you can create multiple branches locally. But once you merge that newly created local branch, it will only be a commit. You have to let the remote also know that you created a new branch, and one possible way is to push the newly created local branch. Another way is to manually create in github, iirc.

**Comment by damithc** [comment]
> If you have merged the b1 branch into the master branch locally and pushed the master branch, you will be able to see the commits you made in the b1 branch appear in the master branch on remote, but you will not be able to see the b1 branch.

Yup. As was mentioned during this week's lecture, a Git branch is implemented as _a label pointing to a commi_t, although our natural tendency is to think of a branch as _a sequence of commits_. When you merge b1 to master and push master, the commits in b1 are pushed (because they now belong to master as well). However, b1 (i.e., the branch label) exists only in your local repo, until you push the branch specifically.
