### ISSUE TITLE
Corrupted fonts in AB3, on Mac

### ISSUE THREAD

**Issue by alextang809** [nus-cs2103-AY2223S2/forum#68]
I'm on a macOS 13.1. I've:
- downloaded `addressbook.jar`
- ran via the macOS terminal the command: `java -jar addressbook.jar` 
- and this was the GUI that popped up:

<img width="955" alt="Screenshot 2023-01-26 at 5 48 30 PM" src="https://user-images.githubusercontent.com/62707493/214806499-e24a4c26-ab9d-47be-a7f8-9a06efb42fca.png">

**Comment by Skeltons** [comment]
Hi, according to the CS2103 website if you are on mac and you do not run the jar with Java 11, the text may end up garbled/unreadable.
https://nus-cs2103-ay2223s2.github.io/website/admin/programmingLanguages.html

**Comment by alextang809** [comment]
I have accidentally removed Java virtual machine in my Java folder. Does it matter?
<img width="334" alt="Screenshot 2023-01-26 at 9 40 34 PM" src="https://user-images.githubusercontent.com/62707493/214850179-2140b347-8b2a-49b0-985d-b6628135a98c.png">

**Comment by francisyzy** [comment]
Not too sure but you can try use sdkman to install java via comandline. https://sdkman.io/install

**Comment by damithc** [comment]
@alextang809 is the issue resolved?

**Comment by domlimm** [comment]
Hello @alextang809, I'm a senior from a previous batch, dropping by to look at the issues posted by you guys. Just a gentle reminder to close the issue once your problem has been resolved. Have a great day! 😄
