### ISSUE TITLE
Removal of previously implemented Extras

### ISSUE THREAD

**Issue by lhy-hoyin** [nus-cs2103-AY2223S2/forum#70]
I am currently refactoring my code and had made it such that my previously implemented `A-Enums` has been "un-implemented".  Which of the following should I do?

(A) Remove the `A-Enums` tag from my repo.
Reasoning: I no longer have this implemented in my current code.

(B) Leave the `A-Enums` tag as it is.
Reasoning: My previous commits will be able to show that I have learnt and knows how to use enums. (Implementation can be seen via commit history.)

**Comment by damithc** [comment]
@lhy-hoyin You can keep the tag, for the reason you have given.
