### ISSUE TITLE
iP progress dashboard failed to detect branch-Level-7 and tag #8

### ISSUE THREAD

**Issue by SHni99** [nus-cs2103-AY2223S2/forum#73]
<img width="983" alt="Screenshot 2023-01-27 at 11 53 16 AM" src="https://user-images.githubusercontent.com/96757889/215006174-8dafa071-4a5e-4baf-a9e3-5a5c95d381c4.png">

**Comment by SHni99** [comment]
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/96757889/215006292-b3cbbe38-b014-48ce-b451-edc0c00afd78.png">
### Tag 8

**Comment by SHni99** [comment]
<img width="945" alt="image" src="https://user-images.githubusercontent.com/96757889/215006353-f3efcf86-3ce7-4a9e-a019-f3120df7c513.png">
### Evidence of branch-Level-7

**Comment by damithc** [comment]
@SHni99 That branch doesn't seem to be merged to the master branch yet.

![image](https://user-images.githubusercontent.com/1673303/215007299-13fe179c-8eca-4aa9-b865-033776b7287e.png)

**Comment by SHni99** [comment]
> @SHni99 That branch doesn't seem to be merged to the master branch yet.
> 
> ![image](https://user-images.githubusercontent.com/1673303/215007299-13fe179c-8eca-4aa9-b865-033776b7287e.png)

Thank you for replying
Prof, can I merge the branch with my latest master branch now?
Also,  the dashboard could not detect tag #8

**Comment by damithc** [comment]
> Prof, can I merge the branch with my latest master branch now?

@SHni99 Yes, it will be detected by the dashboard after you merge it.

> Also, the dashboard could not detect tag #8

That tag is also on the unmerged branch. After the branch is merged, the tag will be detected as well.

**Comment by Hikoya** [comment]
Hello @SHni99 , I'm a senior from a previous batch, gentle reminder to close the issue if the problem has been resolved.
