### ISSUE TITLE
Reading hard disk data file using Gradle

### ISSUE THREAD

**Issue by jamieeeleow** [nus-cs2103-AY2223S2/forum#75]
Hello, when I run my code using Gradle, it is unable to read the hard disk date file where the tasks are being stored. The data file is currently in a data folder in the project root. May I know if I need to change the location of the file so that it can be read when running Gradle? Thank you

**Comment by damithc** [comment]
@jamieeeleow I think you put the body of the issue as the subject. Can you edit the subject and the body to make it more presentable?

**Comment by joellow88** [comment]
You shouldn't need to, how are you specifying the file path to where tasks are being stored?

I used the following code to check the current directory Duke is running in.
```
private static void printCurrentWorkingDirectory() {
        String userDirectory = Paths.get("")
                .toAbsolutePath()
                .toString();
        System.out.println(userDirectory);
    }
```

From there, you should be able to specify a relative path to the data file where your tasks are stored.

**Comment by damithc** [comment]
@jamieeeleow is the issue resolved?
