### ISSUE TITLE
Possible typo in Checkstyle Guide

### ISSUE THREAD

**Issue by axmszr** [nus-cs2103-AY2223S2/forum#77]
Hello! The guide at https://se-education.org/guides/tutorials/checkstyle.html suggests to use `//CODESTYLE.OFF: RuleName` and `//CODESTYLE.ON: RuleName` to suppress a rule for a portion of code. However, when I tried it, it only worked when I replaced "`CODESTYLE`" with "`CHECKSTYLE`".

Could I ask if this is an error on the site, or if `CODESTYLE` does something different that I missed? Thanks!

**Comment by damithc** [comment]
@axmszr thanks for raising this. I'll get someone to investigate.

**Comment by damithc** [comment]
Fixed (i.e., changed CODESTYLE -> CHECKSTYLE in the guide)

**Comment by axmszr** [comment]
Thank you Prof!
