### ISSUE TITLE
For IP, do we have to implement different levels in sequence?

### ISSUE THREAD

**Issue by BoAi01** [nus-cs2103-AY2223S2/forum#8]
For example, for this week's IP, can we implement the level-5 and the level-6 first, and leave A-TextUiTesting to the last?

I understand that it might be preferable if we could implement different levels in sequence, but I am wondering if the progress tracker can capture not-in-order commits.

**Comment by damithc** [comment]
@BoAi01 Yes, try to follow the given order as much as possible. No, we don't penalize if you don't follow the order.

**Comment by BoAi01** [comment]
Thank you for the prompt reply!
