### ISSUE TITLE
Wrong sequence of tagging causing Push error

### ISSUE THREAD

**Issue by nerdyboy98** [nus-cs2103-AY2223S2/forum#80]
The Level-7 and Level-8 increments required us merge with the master branch before tagging but I tagged Level-7 (without merging) and Pushed to the remote Repo. Now I'm facing this problem where it says the "Level-7" already exists when I try to Push my local repo (with Level-7 and Level-8 already merged and tagged after merging) to the remote repo. Anybody have any idea how to resolve this issue? Not sure if this will affect the grading script as well. Thanks in advance!

Edit: I removed the removed the "Level-7" tag from the branch-level-7 and tagged the commit after merging Level-7 increment, which I then encountered this error when Pushing

![image](https://user-images.githubusercontent.com/110829473/215111283-55d4dabd-29f9-40c1-911a-372b53413646.png)

**Comment by damithc** [comment]
Delete the duplicate tag in the remote repo first and try again?

**Comment by nerdyboy98** [comment]
Ahh ok it worked! Thanks prof!

**Comment by yyj-02** [comment]
You can follow the guide [here](https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/):

1. Delete the tag locally `git tag -d Level-7`
2. Delete the tag remotely `git push --delete origin Level-7`
3. Create your new tags and push them

(You can use `git log` to find the commit id)

**Comment by junianob** [comment]
You can also manually delete tags on Github  by navigating to repo name > tags > delete

![image](https://user-images.githubusercontent.com/5424422/215327900-92956e44-6bc7-45dc-8bbe-e96252c4b3ce.png)

**Comment by damithc** [comment]
@nerdyboy98 Is the issue resolved?

**Comment by nerdyboy98** [comment]
> @nerdyboy98 Is the issue resolved?

yup resolved already

**Comment by francisyzy** [comment]
Do close the issue if it is resolved!
