### ISSUE TITLE
Level-8 LocalDate object parsing of dates

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#81]
Teach Duke how to understand dates and times. For example, if the command is `deadline return book /by 2/12/2019 1800`, Duke should understand `2/12/2019 1800` as 2nd of December 2019, 6pm, instead of treating it as just a String.

`LocalDate d1 = LocalDate.parse("2019-12-01");`: Since parse takes in this format. 
Do we have to change the format of the date given to us? I also wish to ask if there is another date format randomly given by a user, how can we make our code as flexible as possible to parse in different kinds of format of the date?

**Comment by damithc** [comment]
@pangrwa You are free to change the command formats and provide more flexibility in the date format. You can go beyond the minimum requirements given to make the product better and/or increase the leaving value of the iP.


> I also wish to ask if there is another date format randomly given by a user, how can we make our code as flexible as possible to parse in different kinds of format of the date?

Good question, and a good opportunity for others to share their ideas/code on how this can be done.

**Comment by Mehvin** [comment]
@pangrwa You can definitely try to be more flexible and allow different formats of date/time. However, what I did was to be restrictive but also at the same time check and inform users of invalid formats (in the form of an error message).

**Comment by XylusChen** [comment]
What I did was to try parsing the inputs into LocalDate (or LocalTime) object. If this operation is not successful, I will simply save the date as a String like before. I think there are too many variations as to how one can input a "date" value and it would be impossible to account for all of them. 

I feel like it's acceptable to expect a strict format from the user. In existing calender apps (Apple's calender) for example, we can only add String descriptions for our event descriptions but not for dates, where we choose from a given drop-down menu (which is similar to "demanding" a fix form of input for dates and times).

**Comment by euph00** [comment]
Personally I restricted my bot to only accept a strict formatting of date and would prompt the user to re-input if improperly formatted, though I do agree with @XylusChen in that the approach of saving an unrecognised format as a String could be a good alternative. However, I wanted conformity to allow events to be filtered, searched and sorted by date cleanly.

I personally do not know of any way to specify datetime objects in arbitrary formats beyond using `DateTimeFormatter` (example [here](https://mkyong.com/java8/java-8-how-to-format-localdatetime/)). Perhaps you could use `try catch` blocks to account for a few common formats, then handle unrecognised formats as you feel make sense.

**Comment by gohyongjing** [comment]
As the others mentioned above, I handled only the required cases as it would be very difficult to flexibly accept different formats (Such as `1-2-2000`: without a fixed format, we would not know if it is `1st Feb` or `2nd Jan`). I only accepted `yyyy-mm-dd tttt` and `yyyy-mm-dd tt:tt` and made a check for whether the colon exists in the time.

I also considered to allow users to pass in their own required format such as `deadline homework /by 01-02-2024 /format dd-mm-yyyy` but this seems to be too verbose, even for fast typists.

I think the most flexibilty we could give is to also accept dates with the month format `mmm`, such as `jan`, `feb` etc, which could be done by manually checking

**Comment by damithc** [comment]
> If this operation is not successful, I will simply save the date as a String like before. I think there are too many variations as to how one can input a "date" value and it would be impossible to account for all of them.

@XylusChen A slight con of this approach: If you do this silently (i.e., without informing the user), this can result in 'unexpected' behaviors down the line. For example, if there is a find-by-date feature, some items will not show up because the dates were stored as strings instead of proper date objects.

**Comment by shittake** [comment]
For me, I informed the user of the only formats that are accepted by my bot, and refused to accept the date in any format other than YYYY-MM-DD or DD-MM-YYYY (with an error message provided). In future iterations though, I am planning to expand it such that other delimiters are accepted as well such as YYYY/MM/DD or YYYY MM DD.

**Comment by damithc** [comment]
For the more adventurous, there are third-parity libraries that can detect dates from natural language e.g., https://www.ocpsoft.org/prettytime/nlp/ but this is beyond Level-8 requirements.

**Comment by arkarsg** [comment]
I read through the some `time` documentation and there are native Java formatter from `java.time.format.DateTimeFormatter`. Following that I have
``` java
DateTimeFormatter IN_FORMT = DateTimeFormatter.ofPattern("dd/MM/yyy hhmm");
DateTimeFormatter OUT_FORMT = DateTimeFormatter.ofPattern("dd LLL, hh:mma");
...
// then to parse
LoacalDateTime deadline = LocalDateTime.parse(deadline, IN_FORMAT);

// to output
deadline.format(OUT_FORMAT);
```
I used this to display a more readable line. In my case, it is displaying `"02 Feb, 11:30am"`.

You might need to read the documentation to see what abbreviation to use (ie `LLL` instead of `MMM`). 
I am sure the `IN_FORMAT` can be changed to accept `"02 Feb 2023, 11.30am"` as well for ease of typing/ readability and let `LocalDateTime` parse.

**Comment by arkarsg** [comment]
> As the others mentioned above, I handled only the required cases as it would be very difficult to flexibly accept different formats (Such as `1-2-2000`: without a fixed format, we would not know if it is `1st Feb` or `2nd Jan`). I only accepted `yyyy-mm-dd tttt` and `yyyy-mm-dd tt:tt` and made a check for whether the colon exists in the time.
> 
> I also considered to allow users to pass in their own required format such as `deadline homework /by 01-02-2024 /format dd-mm-yyyy` but this seems to be too verbose, even for fast typists.
> 
> I think the most flexibilty we could give is to also accept dates with the month format `mmm`, such as `jan`, `feb` etc, which could be done by manually checking

There is `java.time.format.DateTimeFormatter`. Following that I have

```  java
DateTimeFormatter IN_FORMT = DateTimeFormatter.ofPattern("dd/MM/yyyy hhmm");
DateTimeFormatter OUT_FORMT = DateTimeFormatter.ofPattern("dd LLL, hh:mma");
...
// then to parse
LoacalDateTime deadline = LocalDateTime.parse(deadline, IN_FORMAT);

// to output
deadline.format(OUT_FORMAT);
```
I used this to display a more readable line. In my case, it is displaying `"02 Feb, 11:30am"` for the input `02/02/2023 1130`.

You might need to read the documentation to see what abbreviation to use (ie LLL instead of MMM).
I am sure the `IN_FORMAT` can be changed to accept `"02 Feb 2023, 11.30am"` as well for ease of typing/ readability and let `LocalDateTime` parse rather than checking each month.

**Comment by ajjajjajjajj** [comment]
> I personally do not know of any way to specify datetime objects in arbitrary formats beyond using `DateTimeFormatter` (example [here](https://mkyong.com/java8/java-8-how-to-format-localdatetime/)). Perhaps you could use `try catch` blocks to account for a few common formats, then handle unrecognised formats as you feel make sense.

I did it this way as well, and this felt like the best compromise between flexibility and making full use of DateTime. You can define the formats statically and try all of them while creating the Task. It makes it easier to incorporate extra features in the future that require using DateTime too.
