### ISSUE TITLE
Issue with Gradle CLI

### ISSUE THREAD

**Issue by seadragon2000341** [nus-cs2103-AY2223S2/forum#83]
When I run gradle CLI, it gives me the following error.

![image](https://user-images.githubusercontent.com/78403168/215267541-4ff5de27-eb46-424a-8382-b5e00e21eed0.png)

I suspect its because my cli version is java 18, so I have to downgrade it somehow. But I am confused here because my Intellij is using SDK 11, and I only have a JDK 18 in C:/Program Files/java so I'm not sure how to set the env variable to jdk 11?

Thank you for your help!

![image](https://user-images.githubusercontent.com/78403168/215267753-9a474823-0d62-453c-b545-2e5e26897436.png)

**Comment by damithc** [comment]
@seadragon2000341 Intellij settings do not apply when you run something in a terminal (e.g., powershell).
I remember someone else posted a similar problem here earlier and it was resolved eventually. Dig around in past forum issues to see if you can locate it.

**Comment by jefrai** [comment]
Yep, sounds like a similar issue to #63.

On the Project Structure menu in the second screenshot, clicking 'Edit' (or 'SDKs' on the left) should show the path of the JDK used by IntelliJ for the project.
For me it looks like `C:\Users\username\.jdks\jdk-11.0.18`. Try copying your own path and setting it as the JAVA_HOME env var.

E.g. for Powershell:
```
$env:JAVA_HOME='C:\Users\username\.jdks\jdk-11.0.18'
```
For cmd:
```
set JAVA_HOME=C:\Users\username\.jdks\jdk-11.0.18
```

See if gradlew commands work after that - if that fixes it, you can also consider setting JAVA_HOME permanently, but remember to change it back if you have anything that uses other JDK versions.

**Comment by seadragon2000341** [comment]
@jefrai this was really helpful! Thank you! :)
