### ISSUE TITLE
Code does not compile after organising classes into packages

### ISSUE THREAD

**Issue by cyiting** [nus-cs2103-AY2223S2/forum#84]
![Screenshot 2023-01-29 at 2 13 24 AM](https://user-images.githubusercontent.com/75712959/215283876-72e5a7d7-ce8d-4cc1-89df-19380fa84b8e.png)

Hi, I have organised my classes into packages. My code works fine when I run it on IntelliJ, but when I try to compile it, I run into these errors.

Why is this so, and how can I solve this? Thank you all for responding!

**Comment by Junyi00** [comment]
It's hard to tell without looking at the new structure of your codebase and/or the code itself. However, I would guess that the `cannot find symbol` problem occurs because you are missing import statements for classes like `Ui` and `Storage` as they now exists in another package (where previously they exists in the same package).

**Comment by BoAi01** [comment]
Agree with @Junyi00. Should make sure the class files begin with `package <package name>`, and when the class is used somewhere, `import <package>.<class name>` is present in that file.

**Comment by cyiting** [comment]
@Junyi00 @BoAi01 Thank you for your replies, but `Ui`, `Storage` and  `Duke` exist in the same package and I have already imported `duke.exception` in my class files. Any idea why this still happens?

**Comment by BoAi01** [comment]
The error says package `duke.exception` does not exit. Probably you need to check whether there is indeed such a package. Feel free to post the first few lines of your file for us to take a look.

**Comment by damithc** [comment]
> My code works fine when I run it on IntelliJ, but when I try to compile it, I run into these errors.

How exactly are you trying to compile the code? 

Also, delete the `out` folder (or run `./gradlew clean`) to get rid of outdated .class files generated earlier that Intellij might be using when you run the application.

**Comment by EvitanRelta** [comment]
> My code works fine when I run it on IntelliJ, but when I try to compile it, I run into these errors.

@cyiting, how are u compiling it?

If ure trying to run the `runtest.bat` (idk about `runtest.sh` cuz im on windows), u'll need to fix the compilation path in the `runtest.bat` file.

Specifically this line, which only compiles the files in the `./src/main/java` dir, but not its sub-dir like `./src/main/java/duke`, `./src/main/java/duke/exception`, etc.
```bash
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\*.java
```

It should be replaced with something like:
```bash
javac  -cp ..\src\main\java -Xlint:none -d ..\bin ..\src\main\java\duke\*.java ..\src\main\java\duke\exception\*.java ..\src\main\java\duke\YOUR_SUB_PACKAGE_DIR\*.java
```

**Comment by Junyi00** [comment]
@cyiting I would suggest that if u're not willing to push a 'dirty' commit into your master branch, you could consider branching out and pushing it. It would be easier for others to understand and learn what happened.

**Comment by cyiting** [comment]
Thank you all for your inputs.
