### ISSUE TITLE
merging add-gradle-support into main branch

### ISSUE THREAD

**Issue by pangrwa** [nus-cs2103-AY2223S2/forum#88]
For A-Gradle, I know that we have to merge the add-gradle-support into the master branch. Can I ask why` git merge add-graddle-support` will work even though there is no such branch that exists in my local repo? Although it exists in the remote repo, but how can I identify that it exists somewhere in my local repo?

**Comment by hingen** [comment]
> there is no such branch that exists in my local repo

Technically, the `add-gradle-support` branch is in the local repo just named as `remotes/origin/add-gradle-support`. When a remote repo is cloned to a local machine, all the branches get cloned along with it. Not sure how it works on Sourcetree (perhaps someone else can comment on this) but in Git CLI, you can list out these remote branches by running this command:
```
git branch -a
```
Example output:
```
* master
  remotes/origin/HEAD -> origin/master
  remotes/origin/add-gradle-support
  remotes/origin/master
```

When you switch to a branch on your local repo, Git creates a branch with the same name but without the `remote/origin/` part. When commits are made locally, they are made to the local branch and not the remote branch (the one with `remote/origin/` in it's name). I assume this is Git's way of differentiating the commits that exist on your local repo and commits that exist on the remote repo as well as the state of the branch.

**Comment by damithc** [comment]
@pangrwa there are many ways to get the outcome you want. One of the easiest is to run `git merge origin/add-gradle-support`

**Comment by damithc** [comment]
@pangrwa Is the issue resolved?
