### ISSUE TITLE
Issue while creating remote repo from source tree

### ISSUE THREAD

**Issue by alextang809** [nus-cs2103-AY2223S2/forum#9]
I have set up my personal access token and granted access to all repo. Also I can see my repo from Sourcetree locally. But when I try to create a remote repo, it appears to show the error msg below.

<img width="472" alt="Screenshot 2023-01-17 at 12 33 11 AM" src="https://user-images.githubusercontent.com/62707493/212728076-996fb0ce-39ea-41fd-afcd-7ffd33dc0b03.png">

Has anyone encountered the same issue and figured out how to solve it?

**Comment by damithc** [comment]
@alextang809 Are you simply experimenting or trying to follow a step specified somewhere in our course materials. If the latter, which step?

**Comment by alextang809** [comment]
<img width="811" alt="Screenshot 2023-01-18 at 12 14 13 AM" src="https://user-images.githubusercontent.com/62707493/212952698-c1746595-3c61-42ea-93d7-4f4f55212a68.png">

I am following the step 2, initialize a repository. And I have found out where's my problem now.

I should create a local repo rather than a remote repo. Question solved, thank you for the time!
