### ISSUE TITLE
Clarification on if checkstyle.xml fully follows the module's Java codestyle

### ISSUE THREAD

**Issue by rmj1405** [nus-cs2103-AY2223S2/forum#91]
Hi, I have installed the checkstyle and it now shows a violation for creating spaces between imports. The image is not uploading so I have reproduced it below to illustrate the issue. The module's java codestyle documentation does not provide any explicit rules on import spacing hence, I would like to enquire if this checkstyle violation should just be ignored or if it is fully reprenstative of the module codestyle and every violation the checkstyle points out should be strictly followed. Thank you!

```Java
//my current imports 
import task.TaskManager;

import ui.WelcomeUI;

import util.DukeException;
import util.FileManager;

import java.util.Scanner; 

//what checkstyle wants
import task.TaskManager;
import ui.WelcomeUI;
import util.DukeException;
import util.FileManager;
import java.util.Scanner; 

```

**Comment by chia-yh** [comment]
Hi, I noticed that for me, Intellij tends to automatically add a tab(4 spaces) in between when creating spaces, you could try and see if thats the issue that it's flagging?

**Comment by damithc** [comment]
@rmj1405 Checkstyle from where did you get the Checkstyle configuration file?

In general, you are free to modify Checkstyle rules as you wish, provided the code remains compliant with the given coding standard.

**Comment by francisyzy** [comment]
Is this a good [checkstyle.xml](https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml) to use? I've used it for my check styles

**Comment by damithc** [comment]
> Is this a good [checkstyle.xml](https://github.com/se-edu/addressbook-level3/blob/master/config/checkstyle/checkstyle.xml) to use? I've used it for my check styles

@francisyzy Yes, that's the one we use for the tP, and hence, compliant with the module's coding standard. But it might check for things that are not strictly in the coding standard too (you are free to remove them if you wish).

**Comment by rmj1405** [comment]
> @rmj1405 Checkstyle from where did you get the Checkstyle configuration file?


Hi prof, I used the one from the tP! Noted the point that we can edit the checkstyle. Thank you!

**Comment by damithc** [comment]
Our coding standard requires the import statements to be formatted 'consistently'. The tP Checkstyle config file has some additional rules on that so that the formatting remains consistent across different team members.
