### ISSUE TITLE
JavaFX Tutorial Issue Regarding DialogBox.java

### ISSUE THREAD

**Issue by Tempura-Person** [nus-cs2103-AY2223S2/forum#95]
Hi there, I am currently on Part 4 of the JavaFX tutorial (that i am doing on a separate project folder so as to preserve my current IP)
and i am having trouble with understanding what they meant under the header "Using FXML in our application".

It says, "For our custom DialogBox, we did not define a controller so let's create a controller for it."
However, DialogBox.java was already created back in Part 3, under the header "Iteration 2 – Adding Dialog Boxes"

I am confused if I am doing this right, as the method signature for the new DialogBox.java is incompatible with the old one.
![image](https://user-images.githubusercontent.com/92144641/215427805-c11f4a69-3d42-4e79-bbea-0b705d8f56bf.png)

This is how it differs between the two: (this is in MainWindow.java)
![image](https://user-images.githubusercontent.com/92144641/215428583-a7f22332-72b1-4002-9f1b-69f5c3d90056.png)

**Comment by muhammadreyaaz** [comment]
@Tempura-Person in part 3, DialogBox created is not a controller. It is just another class that extends HBox. In part 4, you will need to change the DialogBox created. The change will be adding fxml functions that "controls" the fxml file. The old DialogBox does not have any capabilities to "control" the fxml file. So, I guess you are right that the DialogBox is already created, but now got to edit it to further control the fxml file.

**Comment by jmestxr** [comment]
Yep, just replace your DialogBox.java created back in part 3 with the new one suggested in part 4 of the tutorial. DialogBox.java in part 3 builds the user interface dynamically through Java code. However this process of building UI can quickly become tedious and your code becomes difficult to read/maintain. 

That’s why part 4 suggests to use FXML which has a more appropriate and easy-to-read syntax for building components. You can later style your components easily with css and load the css file on the FXML file. DialogBox.java in part 4 loads the DialogBox.fxml file and display the components (created in the FXML file) on the scene.

Hope this helps.

**Comment by Tempura-Person** [comment]
I'm guessing after setting up FXML, the Duke.java made through the tutorial is no longer needed and i can simply attach my existing Duke.java in my actual IP onto it?

**Comment by gohyongjing** [comment]
I faced similar issue in the part 4 of the tutorial, and i figured out that the tutorial is incomplete. The tutorial doesnt show what to do with `Duke.java` after refactoring the other files with fxml.

As mentioned above by others, you should ***replace*** the entire `DialogBox.java` with their `DialogBox.java` controller, as well as removing all lines in `Duke.java`, except for `Duke`'s `getResponse` function (which should have its access modifier changed from `private` to `public`).

```java
package org.example;

public class Duke {
    public String getResponse(String input) {
        return "Duke heard: " + input;
    }
}
```
I also completed this tutorial in a separate repo, and you can have a look at it if you want:  https://github.com/gohyongjing/javaFxHelloWorld
