### ISSUE TITLE
Week 4 Quiz

### ISSUE THREAD

**Issue by jiasheng59** [nus-cs2103-AY2223S2/forum#96]
Does the 's' in the word associations matter in this question? In other words, if there can't be more than one association between two Person objects, we should choose true or false?

![week 4 quiz](https://user-images.githubusercontent.com/96868229/215472529-6cec29bb-8b73-42d5-872a-8545c46c4637.png)

**Comment by damithc** [comment]
> Does the 's' in the word associations matter in this question? In other words, if there can't be more than one association between two Person objects, we should choose true or false?

@jiasheng59 No, it doesn't play a role in the answer.
