### ISSUE TITLE
IP Code Dashboard not updated

### ISSUE THREAD

**Issue by Jnjy** [nus-cs2103-AY2223S2/forum#97]
Hi,

I went to check my IP code dashboard and found out that some of my tags and commits are not updated in the dashboard. I double checked if I have successfully merged and pushed it with the IP Progress Dashboard as well as SourceTree. It seems that I have successfully merged and pushed the code. Below are the problems that I am facing:

- For the two images below, Tag `Level-9` is present in my Progress Dashboard but not shown in code Dashboard.

![image](https://user-images.githubusercontent.com/87219903/215494191-3c061ff3-bf27-475a-96b0-33fa5a82eaa8.png)

![image](https://user-images.githubusercontent.com/87219903/215494340-e1e88ab8-6b4c-4561-8316-a1ec163af2a5.png)

- The next two images show the mismatch in my GitHub commits and the code dashboard. Commits seem to not be updated on the code dashboard as well.

![image](https://user-images.githubusercontent.com/87219903/215495242-86f76893-51a7-48ba-be94-7708ceef3de1.png)

![image](https://user-images.githubusercontent.com/87219903/215495399-e812d324-c63c-4e30-a6c5-dd1d95e4f817.png)

May I ask what could I be missing on here?

**Comment by damithc** [comment]
@Jnjy I've asked the RepoSense team to investigate. In any case, tags/commits shown in the code dashboard is not used for any grading.

**Comment by damithc** [comment]
@Jnjy an update: Currently, RepoSense ignores all merge commits as they mostly contain changes that are already reflected in earlier commits. But this is not ideal as it can also omit tags added to merge commits, and some merge commits _can_ contain additional changes (e.g., changes done while resolving merge conflicts). I've asked the RepoSense team to consider including merge commits.
In the meantime, it should not affect CS2103/T either way as we don't use RepoSense report to detect/grade tags.

**Comment by Jnjy** [comment]
Thanks Prof for clarifying!
