### ISSUE TITLE
JavaFX runtime components are missing

### ISSUE THREAD

**Issue by PROGRAMMERHAO** [nus-cs2103-AY2223S2/forum#98]
When I tried to follow the tutorial and setup javaFX, I get a "JavaFX runtime components are missing, and are required to run this application" error, what could have gone wrong?

**Comment by damithc** [comment]
@PROGRAMMERHAO It might help if you specify which procedure you used to set up JavaFX and exactly at which step of the set up process you encountered this error.

**Comment by gohyongjing** [comment]
I also received the error because i tried to place the main() function inside my app and launch it directly.
```java
// Duke.java

public class Duke extends Application {

    // Bad, causes error
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }

    public void start(Stage stage) {
        ...
    }
}
```
I moved the main function to a separate launcher.java file and it ran without issues.
```java
// Launcher.java

public class Launcher {
    
    // Good, no error
    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }
}

// Duke.java

public class Duke extends Application {

    public void start(Stage stage) {
        ...
    }
}

```

**Comment by hingen** [comment]
I experienced the same issue and solved it in the same way that @gohyongjing described
Not sure how widespread this is but I think it would be good to include as a note in the JavaFX tutorial, especially at part 2 ["Designing the Layout"](https://se-education.org/guides/tutorials/javaFxPart2.html#designing-the-layout) where the sample code sort of implies that the main method should be place inside the `Duke` class which extends `Application`

**Comment by 9fc70c892** [comment]
Another way of getting the similar error message as OP is to fill in the necessary things into Gradle settings, but not refreshing Gradle build itself (e.g. Gradle didn't install dep)

Note: writing this because @gohyongjing is not OP but has found the solution for the problem that they faced of the same category.

**Comment by PROGRAMMERHAO** [comment]
Thank you guys for helping! It indeed turned out that the problem was caused by not running main in another class, as what @gohyongjing described. Really apppreciated!

**Comment by PROGRAMMERHAO** [comment]
Sorry for troubling, but I have another issue whileusing javaFX. When I tried to call duke from the launcher like this:
```
public class Launch{

    public static void main(String[] args) {
        Application.launch(Duke.class, args);
    }

}
```

I got an error saying: java.lang.NoSuchMethodException: duke.Duke.<init>()

My Duke looks as follows:

```
public Duke(String filePath) {
        ...
}

...
 
public void start(Stage stage) {

        //The container for the content of the chat to scroll.
        scrollPane = new ScrollPane();
        dialogContainer = new VBox();
        scrollPane.setContent(dialogContainer);
        userInput = new TextField();
        sendButton = new Button("Send");
        AnchorPane mainLayout = new AnchorPane();
        mainLayout.getChildren().addAll(scrollPane, userInput, sendButton);
        scene = new Scene(mainLayout);
        stage.setScene(scene);
        stage.show();

} 


public static void main(String[] args) {
        new Duke("data/duke.txt").run();
 }
```

However, this issue does not happen when I create another Test.java file to put start method in like this:
```
public class Test extends Application {

    public void start(Stage stage) {
        Label helloWorld = new Label("Hello World!"); // Creating a new Label control
        Scene scene = new Scene(helloWorld); // Setting the scene to be our Label

        stage.setScene(scene); // Setting the stage to show our screen
        stage.show(); // Render the stage.
    }

}
```
Could anyone help me with this? Thank you so much!
